export const mockVendorExtensionFormDefinition = {
    "versionNum": null,
    "created": "2024-02-14T07:58:34.314139374Z",
    "updated": "2024-02-14T14:45:05.705262863Z",
    "createdBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "userNameCP": null,
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "103.153.166.106",
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "updatedBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "userNameCP": null,
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "103.153.166.106",
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "audit": null,
    "acl": {
        "users": [
            {
                "tenantId": "foo",
                "tenantName": "Foo Company",
                "userName": "john@foo.com",
                "userNameCP": null,
                "name": "John Doe",
                "department": null,
                "departmentCode": null,
                "departmentErpId": null,
                "groupIds": null,
                "type": "Tenant",
                "email": "john@foo.com",
                "phone": null,
                "firstName": null,
                "lastName": null,
                "api": false,
                "picture": null,
                "ip": "103.153.166.106",
                "impersonator": null,
                "connectionName": null,
                "procurementAdmin": true,
                "otp": false,
                "admin": true
            }
        ],
        "groups": [],
        "workstream": null,
        "programs": null,
        "departments": null,
        "open": false
    },
    "version": "38",
    "idGenerator": {
        "id": 10
    },
    "tenantId": "foo",
    "name": "Vendor_Header_Extension_Form",
    "title": "Vendor Header Extension Form",
    "description": "",
    "visibility": null,
    "customVisibilityConditions": null,
    "formType": "other",
    "view": {
        "sections": [
            {
                "id": "1",
                "title": null,
                "description": null,
                "displayIndex": "1",
                "grids": [
                    {
                        "id": "2",
                        "displayIndex": "1.1",
                        "level": null,
                        "fields": [
                            {
                                "id": "3",
                                "size": 12,
                                "field": {
                                    "id": "4",
                                    "name": "<p>Company Entity</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_Company_Entity__p_",
                                    "stringRegex": null,
                                    "type": "idref",
                                    "selection": null,
                                    "customFieldType": "masterdata",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.1",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": "CompanyEntity",
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": {
                                        "id": "companyEntity",
                                        "name": "Company entity",
                                        "erpId": "ProcessFieldMapping__Any__companyEntity",
                                        "empty": false
                                    },
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "assessmentSubtypeConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    }
                ],
                "visible": null,
                "hiddenForReadOnly": null,
                "layout": "twoColumn"
            }
        ]
    },
    "model": {
        "fields": [
            {
                "id": "4",
                "name": "<p>Company Entity</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_Company_Entity__p_",
                "stringRegex": null,
                "type": "idref",
                "selection": null,
                "customFieldType": "masterdata",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.1",
                "fileTypes": null,
                "documents": null,
                "masterDataType": "CompanyEntity",
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": {
                    "id": "companyEntity",
                    "name": "Company entity",
                    "erpId": "ProcessFieldMapping__Any__companyEntity",
                    "empty": false
                },
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "assessmentSubtypeConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            }
        ]
    },
    "status": "published",
    "formGlobalConditions": null,
    "validationApis": null,
    "creator": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "userNameCP": null,
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "103.153.166.106",
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "lastPublished": "2024-02-14T14:45:23.719821961Z"
}

export const mockVendorExtensionCustomFormData = {
    "_p_Company_Entity__p_": {
        "tenantId": "foo",
        "name": "Honeycomb Holdings Inc.",
        "erpId": "4",
        "id": "HH",
        "empty": false
    }
}