import {
    USER_ID_SOURCE_FIELDS, CONTACT_SOURCE_FIELDS, GROUP_ID_SOURCE_FIELDS, ID_REF_SOURCE_FIELDS, IMAGE_METADATA_SOURCE_FIELDS,
    IMAGE_SOURCE_FIELDS, MONEY_SOURCE_FIELDS, NORMALIZED_VENDOR_REF_SOURCE_FIELDS, ORG_ID_SOURCE_FIELDS, PO_REF_SOURCE_FIELDS,
    VENDOR_REF, FORM_GLOBAL_VALUE, ATTACHMENT_SOURCE_FIELDS
} from './common/fragments'

import {
    PROCESS_REQUEST_META_SOURCE_FIELDS, ENGAGEMENTS_SOURCE_FIELDS, INFO_REQUEST_SOURCE_FIELDS, PROCESS_TASK_SOURCE_FIELDS,
    PROCESS_VARIABLES_SOURCE_FIELDS, PROGRESS_SOURCE_FIELDS, CALLBACK_OUTCOME_SCOURCE_FIELDS, ENCRYPTED_DATA_SCOURCE_FIELDS, MILESTONEINFO_SOURCE_FIELDS,
    RISK_SCORE_SCOURCE_FIELDS, CHANGE_PO_SCOURCE_FIELDS, ITEM_DETAILS_SCOURCE_FIELDS, ITEM_LIST_SCOURCE_FIELDS, TAX_ITEM_SOURCE_FIELDS, TAX_SOURCE_FIELDS, ASSESSMENT_RISK_FIELDS, ASSESSMENT_SCOPE_SOURCE_FIELDS,
    ACCUMULATOR_SOURCE_FIELDS
} from './engagements/fragament'

import {
    GET_ALL_ENGAGEMENTS, GET_ENGAGEMENT, GET_ENGAGEMENTS, GET_ENGAGEMENTS_BY_NORMALIZED_SUPPLIER, GET_ENGAGEMENTS_BY_SUPPLIER,
    GET_ENGAGEMENT_CONTACTS, GET_ENGAGEMENT_TASKS, GET_PROCESS_FORMS, GET_ENGAGEMENT_FORMS, GET_ENGAGEMENT_PROGRESS_HISTORY
} from './engagements/query'

import {
    UPDATE_ENGAGEMENT_CONTACT, UPDATE_ENGAGEMENT_PROGRESS_NOTE, UPDATE_ENGAGEMENT_DESCRIPTION, SEND_ENGAGEMENT_PROGRESS_COMMENT, UPDATE_ENGAGEMENT_PROGRESS_NO_UPDATE
} from './engagements/mutation'

import {
    FORM_FIELD, FORM_CONFIGURATION
} from './Form/fragments'

import {
    GET_OROFORM_CONFIGURATION
} from './Form/query'

import {
    NODE_STEP_SOURCE_FIELDS
} from './process/fragments'

import {
    GET_PROCESS_STEPS, PREVIEW_PROCESS, GET_PROCESS_STEPS2, IS_TASK_LOCKED
} from './process/query'

import {
    BRANCH_SOURCE_FIELDS, NODE_SOURCE_FIELDS, PROCESS_DEFINITION_ID_SOURCE_FIELDS, PROCESS_INFO_SOURCE_FIELDS, PROCESS_INSTANCE_SOURCE_FIELDS,
    PROCESS_REQUEST_SOURCE_FIELDS, REQUEST_META_SOURCE_FIELDS, REQUEST_QUESTIONNAIREID_SOURCE_FIELDS, REQUEST_STEPS_SOURCE_FIELDS,
    REQUEST_STEP_ERROR_SOURCE_FIELDS, REQUEST_SUBMISSION_RESPONSE_SOURCE_FIELDS, SELECTION_SOURCE_FIELDS, SELECTOR_ENTRY_SOURCE_FIELDS,
    MILESTONE_SOURCE_FIELDS
} from './request/fragment'

import {
    GET_PROCESS_REQUEST, GET_PROCESS_REQUEST_STEP, MILESTONES
} from './request/query'

import {
    DELETE_REQUEST, EDIT_REQUEST, PROCESS_REQUEST, CREATE_MEASURE_FROM_IDEATION, REGISTER_ORBEON_QUESTIONNAIRE_FOR_REQUEST, SET_CHANGE_COMMENT, SUBMIT_REQUEST
} from './request/mutation'

import {
    PUBLISHED_REQUEST_DEFINITIONS_SOURCE_FIELDS, REQUEST_DEFINITION_SOURCE_FIELDS
} from './SupplierOnboarding/fragment'

import {
    PUBLISHED_REQUEST_DEFINITIONS
} from './SupplierOnboarding/query'

import {
    QUESTIONNAIREID_SOURCE_FIELDS, ROLE_FORMS_SOURCE_FIELDS, TASK_ASSIGNMENT_SOURCE_FIELD, TASK_CHECKLIST_SECTION_SOURCE_FIELDS,
    TASK_CHECKLIST_SOURCE_FIELDS, TASK_CHECKLIST_VALUE_SOURCE_FIELDS, TASK_DATES_INFOS_SOURCE_FIELD, TASK_DATES_SOURCE_FIELD,
    TASK_SOURCE_FIELDS, ENGAGEMENT_TASK_FIELDS, MEASURE_TASK_SOURCE_FIELDS
} from './task/fragaments'

import {
    GET_CHECKLIST_QUERY, GET_TASK_QUERY, GET_TASK_WITH_DATE_INFO_QUERY
} from './task/query'

import {
    APPROVE_TASK, POST_NOTE, REACTIVATE_NODE, REJECT_TASK, SHARE_FORMS, START_TASK, SUBMIT_TASK, TASK_ASK_FOR_INFO, UPDATE_CHECKLIST, REASSIGN_USER_QUERY, ADD_APPROVER_QUERY
} from './task/mutation'

import {
    GET_IS_CURRENT_USER_ADMIN, GET_PENDING_APPROVALS_FOR_USER, PENDING_APPROVAL_FOR_REQUESTER, PENDING_APPROVALS_FOR_TEAM
} from './user/query'

import {
    APPROVE_TEAM_REQUEST, DENY_TEAM_REQUEST, REQUEST_FOR_TEAM, UPDATE_APPROVAL_WORKSTREAM
} from './user/mutation'

export {
    GET_IS_CURRENT_USER_ADMIN, GET_PENDING_APPROVALS_FOR_USER, PENDING_APPROVAL_FOR_REQUESTER, PENDING_APPROVALS_FOR_TEAM, APPROVE_TEAM_REQUEST, DENY_TEAM_REQUEST, REQUEST_FOR_TEAM, UPDATE_APPROVAL_WORKSTREAM,
    APPROVE_TASK, POST_NOTE, REACTIVATE_NODE, REJECT_TASK, SHARE_FORMS, START_TASK, SUBMIT_TASK, REASSIGN_USER_QUERY, TASK_ASK_FOR_INFO, UPDATE_CHECKLIST,
    GET_CHECKLIST_QUERY, GET_TASK_QUERY, GET_TASK_WITH_DATE_INFO_QUERY, ADD_APPROVER_QUERY,
    QUESTIONNAIREID_SOURCE_FIELDS, ROLE_FORMS_SOURCE_FIELDS, TASK_ASSIGNMENT_SOURCE_FIELD, TASK_CHECKLIST_SECTION_SOURCE_FIELDS,
    TASK_CHECKLIST_SOURCE_FIELDS, TASK_CHECKLIST_VALUE_SOURCE_FIELDS, TASK_DATES_INFOS_SOURCE_FIELD, TASK_DATES_SOURCE_FIELD,
    TASK_SOURCE_FIELDS,
    PUBLISHED_REQUEST_DEFINITIONS,
    PUBLISHED_REQUEST_DEFINITIONS_SOURCE_FIELDS, REQUEST_DEFINITION_SOURCE_FIELDS,
    DELETE_REQUEST, EDIT_REQUEST, PROCESS_REQUEST, CREATE_MEASURE_FROM_IDEATION, REGISTER_ORBEON_QUESTIONNAIRE_FOR_REQUEST, SET_CHANGE_COMMENT, SUBMIT_REQUEST,
    GET_PROCESS_REQUEST, GET_PROCESS_REQUEST_STEP,
    BRANCH_SOURCE_FIELDS, NODE_SOURCE_FIELDS, PROCESS_DEFINITION_ID_SOURCE_FIELDS, PROCESS_INFO_SOURCE_FIELDS, PROCESS_INSTANCE_SOURCE_FIELDS,
    PROCESS_REQUEST_SOURCE_FIELDS, REQUEST_META_SOURCE_FIELDS, REQUEST_QUESTIONNAIREID_SOURCE_FIELDS, REQUEST_STEPS_SOURCE_FIELDS,
    REQUEST_STEP_ERROR_SOURCE_FIELDS, REQUEST_SUBMISSION_RESPONSE_SOURCE_FIELDS, SELECTION_SOURCE_FIELDS, SELECTOR_ENTRY_SOURCE_FIELDS,
    GET_PROCESS_STEPS, PREVIEW_PROCESS, GET_PROCESS_STEPS2, IS_TASK_LOCKED,
    NODE_STEP_SOURCE_FIELDS,
    GET_OROFORM_CONFIGURATION,
    FORM_FIELD, FORM_CONFIGURATION,
    UPDATE_ENGAGEMENT_CONTACT,
    GET_ALL_ENGAGEMENTS, GET_ENGAGEMENT, GET_ENGAGEMENTS, GET_ENGAGEMENTS_BY_NORMALIZED_SUPPLIER, GET_ENGAGEMENTS_BY_SUPPLIER,
    GET_ENGAGEMENT_CONTACTS, GET_ENGAGEMENT_TASKS, GET_PROCESS_FORMS, GET_ENGAGEMENT_FORMS,
    PROCESS_REQUEST_META_SOURCE_FIELDS, ENGAGEMENTS_SOURCE_FIELDS, INFO_REQUEST_SOURCE_FIELDS, PROCESS_TASK_SOURCE_FIELDS,
    PROCESS_VARIABLES_SOURCE_FIELDS, PROGRESS_SOURCE_FIELDS,
    USER_ID_SOURCE_FIELDS, CONTACT_SOURCE_FIELDS, GROUP_ID_SOURCE_FIELDS, ID_REF_SOURCE_FIELDS, IMAGE_METADATA_SOURCE_FIELDS,
    IMAGE_SOURCE_FIELDS, MONEY_SOURCE_FIELDS, NORMALIZED_VENDOR_REF_SOURCE_FIELDS, ORG_ID_SOURCE_FIELDS, PO_REF_SOURCE_FIELDS,
    VENDOR_REF, MILESTONE_SOURCE_FIELDS, MILESTONES, UPDATE_ENGAGEMENT_PROGRESS_NOTE, UPDATE_ENGAGEMENT_DESCRIPTION, GET_ENGAGEMENT_PROGRESS_HISTORY,
    SEND_ENGAGEMENT_PROGRESS_COMMENT, UPDATE_ENGAGEMENT_PROGRESS_NO_UPDATE, ENGAGEMENT_TASK_FIELDS,
    CALLBACK_OUTCOME_SCOURCE_FIELDS, ENCRYPTED_DATA_SCOURCE_FIELDS, MILESTONEINFO_SOURCE_FIELDS, RISK_SCORE_SCOURCE_FIELDS,
    CHANGE_PO_SCOURCE_FIELDS, ITEM_DETAILS_SCOURCE_FIELDS, ITEM_LIST_SCOURCE_FIELDS, TAX_ITEM_SOURCE_FIELDS, TAX_SOURCE_FIELDS, FORM_GLOBAL_VALUE, ASSESSMENT_RISK_FIELDS,
    ASSESSMENT_SCOPE_SOURCE_FIELDS, MEASURE_TASK_SOURCE_FIELDS, ATTACHMENT_SOURCE_FIELDS, ACCUMULATOR_SOURCE_FIELDS
}