import React, { useRef, useState } from "react";
import { StoryFn } from "@storybook/react";

import { ListType, RequestListing, RequestListingProps } from "../../lib";

export default {
  title: "ORO UI Toolkit/RequestListing",
  component: RequestListing,
};

const Template: StoryFn<RequestListingProps> = (args) => {
  const [open, setOpen] = useState(false);
  const popoverTargetElem = useRef<any>();
  return (
    <>
      <div
        onClick={() => setOpen(true)}
        ref={popoverTargetElem}
        style={{
          width: "190px",
          padding: "10px",
          border: "1px solid",
          marginTop: "40px",
        }}
      >
        Show Request List
      </div>
      <RequestListing
        {...args}
        isRequestListOpen={open}
        refTarget={popoverTargetElem}
      />
    </>
  );
};

export const requestList = Template;
requestList.args = {
  isRequestListOpen: true,
  requestList: {
    mine: [
      {
        id: 121,
        owner: {
          name: "John Doe",
          userName: "john@foo.com",
          api: false,
          groupIds: [],
          selected: false,
          tenantId: "foo",
          department: "",
          picture: "",
          firstName: "",
          lastName: "",
          email: "john@foo.com",
          isOtp: false,
        },
        sharedWith: null,
        name: "sample",
        type: "request" as ListType,
        config: {
          visiblity: "all",
        },
      },
      {
        id: 123,
        owner: {
          name: "John Doe",
          userName: "john@foo.com",
          api: false,
          groupIds: [],
          selected: false,
          tenantId: "foo",
          department: "",
          picture: "",
          firstName: "",
          lastName: "",
          email: "john@foo.com",
          isOtp: false,
        },
        sharedWith: null,
        name: "HKB",
        type: "request" as ListType,
        config: {
          requests: [
            {
              kpiUnit: "",
              hasEbit: false,
              vendorId: "",
              description: "",
              lateMilestones: 0,
              issues: [],
              currentMilestone: "",
              appType: "",
              projectAmount: {
                amount: 0,
                currency: "",
              },
              projectAmountMoney: {
                amount: 0,
                currency: "",
              },
              segment: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              members: [],
              alreadyMember: false,
              id: "342789035646974184",
              coOwners: [],
              currentRequest: {
                processName: "Test GT 0803",
                requestId: "ORO11934",
                mainProcessId: "342789218636069096",
                processStarted: "2023-08-10T15:24:30.158749915Z",
                id: "342789035433064681",
                type: "onboarding",
              },
              requester: {
                firstName: "",
                lastName: "",
                groupIds: [],
                name: "John Doe",
                tenantId: "foo",
                api: false,
                userName: "john@foo.com",
                department: "",
                isOtp: false,
                selected: false,
                picture: "",
                email: "",
              },
              upcomingMilestones: 0,
              pendingTasks: [
                {
                  lastMsgBy: "",
                  infoMsgId: "",
                  functionRole: "",
                  type: "review",
                  title: "Review",
                  assignmentType: "user",
                  lastMsgUser: "",
                  functionGroup: "",
                  groupIds: [],
                  lastMsgTime: "",
                  taskStatus: "pending",
                  owner: {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "John Doe",
                    tenantId: "foo",
                    api: false,
                    userName: "john@foo.com",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                  partnerName: "",
                  started: "2023-08-10T15:27:33Z",
                  msgClosed: false,
                  submissionComment: "",
                  completed: "",
                  users: [
                    {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "John Doe",
                      tenantId: "",
                      api: false,
                      userName: "john@foo.com",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                  ],
                  suspended: false,
                  resubmitted: false,
                  workstream: {
                    name: "",
                    erpId: "",
                    id: "",
                    refId: "",
                    version: "",
                  },
                  lateTime: "2023-08-12T15:27:33Z",
                  lastMsg: "",
                  assignedToCurrentUser: true,
                  taskId: "342789988418592104",
                },
              ],
              variables: {
                regions: [],
                businessUnit: [],
                projectTypes: [],
                sites: [],
                contracts: [],
                segments: [],
                startingSubprocessName: "",
                assesssmentScopes: [],
                processName: "",
                requestId: "",
                segment: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                projectAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                projectAmountMoneyInTenantCurrency: {
                  amount: 0,
                  currency: "",
                },
                categories: [],
                departments: [],
                callbackOutcomes: [],
                accountCode: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                requestType: "",
                impact: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                activityName: "Test GT 0803 - Lukoil",
                priority: "",
                vendorClassification: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                businessRegions: [],
                companyEntityCountryCodes: [],
                partners: [
                  {
                    selectedVendorRecord: {
                      companyEntityRef: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabledSystems: [],
                      name: "",
                      additionalCompanyEntities: [],
                      vendorId: "",
                      paymentTerm: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabled: false,
                      currencies: [],
                    },
                    countryCode: "",
                    contact: {
                      lastName: "",
                      country: "",
                      note: "",
                      address: {
                        province: "",
                        city: "",
                        streetNumber: "",
                        alpha2CountryCode: "",
                        unitNumber: "",
                        language: "",
                        postal: "",
                        line3: "",
                        line2: "",
                        line1: "",
                      },
                      role: "Account Manager",
                      emailVerification: {
                        verificationFailureReason: "",
                        domainNotExist: false,
                        emailNotDeliverable: false,
                        isFreeDomain: false,
                        verified: false,
                        email: "",
                      },
                      phoneVerified: false,
                      fullName: "Azad Shaikh",
                      title: "",
                      firstName: "",
                      emailVerified: false,
                      phone: "",
                      imageUrl: "",
                      requireBackgroundCheck: false,
                      id: "",
                      email: "azad.shaikh@orolabs.ai",
                      sharePercentage: 0,
                    },
                    name: "Lukoil",
                    vendorRecords: [],
                    sanctionList: [],
                    activationStatus: "newSupplier",
                    legalEntityLogo: {
                      metadata: [],
                      backgroundColor: "",
                    },
                    id: "342221666479106111",
                    isIndividual: false,
                    shareHolders: [],
                  },
                ],
                contractAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                paymentMethod: "",
                companyEntities: [],
                companyEntityCurrencyCode: "",
                engagementId: "",
                po: {
                  cost: 0,
                  poNumber: "",
                  currencyCode: "",
                },
              },
              infoRequests: [],
              lastStatusUpdate: "",
              currencySymbol: "",
              started: "2023-08-10T15:23:46.539459613Z",
              completed: "",
              relatedEnagements: [],
              hasChildRequests: false,
              watched: false,
              selection: {
                requester: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                businessUnits: [],
                brands: [],
                partnerRegions: [],
                regions: [],
                spendBucket: 0,
                projectLevels: [],
                isNewPartner: false,
                categories: [],
                partnerLevels: [],
              },
              amountDifferenceMoney: {
                amount: 0,
                currency: "",
              },
              name: "Test GT 0803",
              processing: false,
              progress: {
                stepsCompleted: 2,
                needsUpdate: false,
                milestoneWarning: false,
                completedTime: 2,
                submitByDate: "",
                daysToApprovalSubmiteDate: 0,
                totalEstimateTime: 3,
                tasksStarted: false,
                stepsTotal: 3,
                noUpdateDate: "",
                noUpdateLastWeek: false,
                milestoneOverdue: false,
              },
              workStream: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              milestones: [],
              engagementId: "1231456",
              updated: "2023-08-10T15:27:33.874238790Z",
              currencyCode: "",
              nextTask: {
                owner: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                lastMsgBy: "",
                partnerName: "",
                infoMsgId: "",
                functionRole: "",
                started: "",
                msgClosed: false,
                submissionComment: "",
                completed: "",
                type: "",
                title: "",
                users: [],
                assignmentType: "",
                suspended: false,
                lastMsgUser: "",
                resubmitted: false,
                functionGroup: "",
                workstream: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                lateTime: "",
                groupIds: [],
                lastMsg: "",
                assignedToCurrentUser: false,
                lastMsgTime: "",
                taskId: "",
              },
              contacts: [
                {
                  lastName: "",
                  country: "",
                  note: "",
                  address: {
                    province: "",
                    city: "",
                    streetNumber: "",
                    alpha2CountryCode: "",
                    unitNumber: "",
                    language: "",
                    postal: "",
                    line3: "",
                    line2: "",
                    line1: "",
                  },
                  role: "Account Manager",
                  emailVerification: {
                    verificationFailureReason: "",
                    domainNotExist: false,
                    emailNotDeliverable: false,
                    isFreeDomain: false,
                    verified: false,
                    email: "",
                  },
                  contactId: "",
                  phoneVerified: false,
                  fullName: "Azad Shaikh",
                  title: "",
                  firstName: "",
                  emailVerified: false,
                  selection: {
                    requester: {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "",
                      tenantId: "",
                      api: false,
                      userName: "",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                    businessUnits: [],
                    brands: [],
                    partnerRegions: [],
                    regions: [],
                    spendBucket: 0,
                    projectLevels: [],
                    isNewPartner: false,
                    categories: [],
                    partnerLevels: [],
                  },
                  phone: "",
                  supplierUserId: "",
                  imageUrl: "",
                  requireBackgroundCheck: false,
                  tenantId: "",
                  id: "",
                  engagementId: "",
                  email: "azad.shaikh@orolabs.ai",
                  sharePercentage: 0,
                },
              ],
              status: "Pending",
            },
            {
              kpiUnit: "",
              hasEbit: false,
              vendorId: "",
              description: "",
              lateMilestones: 0,
              issues: [],
              currentMilestone: "",
              appType: "",
              projectAmount: {
                amount: 0,
                currency: "",
              },
              projectAmountMoney: {
                amount: 0,
                currency: "",
              },
              segment: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              members: [],
              alreadyMember: false,
              id: "342780251876421515",
              coOwners: [],
              currentRequest: {
                processName: "Test GT 0803",
                requestId: "ORO11926",
                mainProcessId: "342780483920314680",
                processStarted: "2023-08-10T14:49:47.640966631Z",
                id: "342780251721232268",
                type: "onboarding",
              },
              requester: {
                firstName: "",
                lastName: "",
                groupIds: [],
                name: "John Doe",
                tenantId: "foo",
                api: false,
                userName: "john@foo.com",
                department: "",
                isOtp: false,
                selected: false,
                picture: "",
                email: "",
              },
              upcomingMilestones: 0,
              pendingTasks: [
                {
                  lastMsgBy: "",
                  infoMsgId: "",
                  functionRole: "",
                  type: "documentCollection",
                  title: "Document collection",
                  assignmentType: "partner",
                  lastMsgUser: "",
                  functionGroup: "",
                  groupIds: [],
                  lastMsgTime: "",
                  taskStatus: "pending",
                  owner: {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "Yuan Tung4",
                    tenantId: "foo",
                    api: false,
                    userName: "tung.yuan.tsung@gmail.com",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                  partnerName: "Yuan - 0810-1",
                  started: "2023-08-10T14:49:47.708321789Z",
                  msgClosed: false,
                  submissionComment: "",
                  completed: "",
                  users: [
                    {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "John Doe",
                      tenantId: "",
                      api: false,
                      userName: "john@foo.com",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                  ],
                  suspended: false,
                  resubmitted: false,
                  workstream: {
                    name: "",
                    erpId: "",
                    id: "",
                    refId: "",
                    version: "",
                  },
                  lateTime: "2023-08-12T14:49:47.712246128Z",
                  lastMsg: "",
                  assignedToCurrentUser: false,
                  taskId: "342780484222304568",
                },
              ],
              variables: {
                regions: [],
                businessUnit: [],
                projectTypes: [],
                sites: [],
                contracts: [],
                segments: [],
                startingSubprocessName: "",
                assesssmentScopes: [],
                processName: "",
                requestId: "",
                segment: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                projectAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                projectAmountMoneyInTenantCurrency: {
                  amount: 0,
                  currency: "",
                },
                categories: [],
                departments: [],
                callbackOutcomes: [],
                accountCode: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                requestType: "",
                impact: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                activityName: "Test GT 0803 - Yuan - 0810-1",
                priority: "",
                vendorClassification: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                businessRegions: [],
                companyEntityCountryCodes: [],
                partners: [
                  {
                    selectedVendorRecord: {
                      companyEntityRef: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabledSystems: [],
                      name: "",
                      additionalCompanyEntities: [],
                      vendorId: "",
                      paymentTerm: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabled: false,
                      currencies: [],
                    },
                    contact: {
                      lastName: "",
                      country: "",
                      note: "",
                      address: {
                        province: "",
                        city: "",
                        streetNumber: "",
                        alpha2CountryCode: "",
                        unitNumber: "",
                        language: "",
                        postal: "",
                        line3: "",
                        line2: "",
                        line1: "",
                      },
                      role: "",
                      emailVerification: {
                        verificationFailureReason: "",
                        domainNotExist: false,
                        emailNotDeliverable: false,
                        isFreeDomain: false,
                        verified: false,
                        email: "",
                      },
                      phoneVerified: false,
                      fullName: "Yuan",
                      title: "",
                      firstName: "",
                      emailVerified: false,
                      phone: "+15105746499",
                      imageUrl: "",
                      requireBackgroundCheck: false,
                      id: "",
                      email: "tung.yuan.tsung@gmail.com",
                      sharePercentage: 0,
                    },
                    name: "Yuan - 0810-1",
                    vendorRecords: [],
                    sanctionList: [],
                    activationStatus: "newSupplier",
                    legalEntityLogo: {
                      metadata: [],
                      backgroundColor: "",
                    },
                    id: "342780372328443787",
                    isIndividual: false,
                    shareHolders: [],
                  },
                ],
                contractAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                paymentMethod: "",
                companyEntities: [],
                companyEntityCurrencyCode: "",
                engagementId: "",
                po: {
                  cost: 0,
                  poNumber: "",
                  currencyCode: "",
                },
              },
              infoRequests: [],
              lastStatusUpdate: "",
              currencySymbol: "",
              started: "2023-08-10T14:48:52.328912353Z",
              completed: "",
              relatedEnagements: [],
              hasChildRequests: false,
              watched: false,
              selection: {
                requester: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                businessUnits: [],
                brands: [],
                partnerRegions: [],
                regions: [],
                spendBucket: 0,
                projectLevels: [],
                isNewPartner: false,
                categories: [],
                partnerLevels: [],
              },
              amountDifferenceMoney: {
                amount: 0,
                currency: "",
              },
              name: "Test GT 0803",
              processing: false,
              progress: {
                stepsCompleted: 0,
                needsUpdate: false,
                milestoneWarning: false,
                completedTime: 0,
                submitByDate: "",
                daysToApprovalSubmiteDate: 0,
                totalEstimateTime: 3,
                tasksStarted: false,
                stepsTotal: 3,
                noUpdateDate: "",
                noUpdateLastWeek: false,
                milestoneOverdue: false,
              },
              workStream: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              milestones: [],
              engagementId: "1231454",
              updated: "2023-08-10T14:52:02.200906922Z",
              currencyCode: "",
              nextTask: {
                owner: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                lastMsgBy: "",
                partnerName: "",
                infoMsgId: "",
                functionRole: "",
                started: "",
                msgClosed: false,
                submissionComment: "",
                completed: "",
                type: "",
                title: "Sanction list check",
                users: [],
                assignmentType: "",
                suspended: false,
                lastMsgUser: "",
                resubmitted: false,
                functionGroup: "",
                workstream: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                lateTime: "",
                groupIds: [],
                lastMsg: "",
                assignedToCurrentUser: false,
                lastMsgTime: "",
                taskId: "",
              },
              contacts: [
                {
                  lastName: "",
                  country: "",
                  note: "",
                  address: {
                    province: "",
                    city: "",
                    streetNumber: "",
                    alpha2CountryCode: "",
                    unitNumber: "",
                    language: "",
                    postal: "",
                    line3: "",
                    line2: "",
                    line1: "",
                  },
                  role: "",
                  emailVerification: {
                    verificationFailureReason: "",
                    domainNotExist: false,
                    emailNotDeliverable: false,
                    isFreeDomain: false,
                    verified: false,
                    email: "",
                  },
                  contactId: "",
                  phoneVerified: false,
                  fullName: "Yuan",
                  title: "",
                  firstName: "",
                  emailVerified: false,
                  selection: {
                    requester: {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "",
                      tenantId: "",
                      api: false,
                      userName: "",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                    businessUnits: [],
                    brands: [],
                    partnerRegions: [],
                    regions: [],
                    spendBucket: 0,
                    projectLevels: [],
                    isNewPartner: false,
                    categories: [],
                    partnerLevels: [],
                  },
                  phone: "+15105746499",
                  supplierUserId: "",
                  imageUrl: "",
                  requireBackgroundCheck: false,
                  tenantId: "",
                  id: "",
                  engagementId: "",
                  email: "tung.yuan.tsung@gmail.com",
                  sharePercentage: 0,
                },
              ],
              status: "Pending",
            },
            {
              kpiUnit: "",
              hasEbit: false,
              vendorId: "",
              description: "",
              lateMilestones: 0,
              issues: [],
              currentMilestone: "",
              appType: "",
              projectAmount: {
                amount: 0,
                currency: "",
              },
              projectAmountMoney: {
                amount: 0,
                currency: "",
              },
              segment: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              members: [],
              alreadyMember: false,
              id: "342776825602228536",
              coOwners: [],
              currentRequest: {
                processName: "Test Auto Approval",
                requestId: "ORO11924",
                mainProcessId: "342776899016912779",
                processStarted: "2023-08-10T14:35:32.942124563Z",
                id: "342776825442844985",
                type: "onboarding",
              },
              requester: {
                firstName: "",
                lastName: "",
                groupIds: [],
                name: "John Doe",
                tenantId: "foo",
                api: false,
                userName: "john@foo.com",
                department: "",
                isOtp: false,
                selected: false,
                picture: "",
                email: "",
              },
              upcomingMilestones: 0,
              pendingTasks: [
                {
                  lastMsgBy: "",
                  infoMsgId: "",
                  functionRole: "",
                  type: "manual",
                  title: "To do",
                  assignmentType: "request_owners",
                  lastMsgUser: "",
                  functionGroup: "",
                  groupIds: [],
                  lastMsgTime: "",
                  taskStatus: "inreview",
                  owner: {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "John Doe",
                    tenantId: "foo",
                    api: false,
                    userName: "john@foo.com",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                  partnerName: "",
                  started: "2023-08-10T14:35:32Z",
                  msgClosed: false,
                  submissionComment: "",
                  completed: "",
                  users: [
                    {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "John Doe",
                      tenantId: "",
                      api: false,
                      userName: "john@foo.com",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                  ],
                  suspended: false,
                  resubmitted: false,
                  workstream: {
                    name: "",
                    erpId: "",
                    id: "",
                    refId: "",
                    version: "",
                  },
                  lateTime: "2023-08-12T14:35:32Z",
                  lastMsg: "",
                  assignedToCurrentUser: true,
                  taskId: "342776899239210891",
                },
              ],
              variables: {
                regions: [],
                businessUnit: [],
                projectTypes: [],
                sites: [],
                contracts: [],
                segments: [],
                startingSubprocessName: "",
                assesssmentScopes: [],
                processName: "",
                requestId: "",
                segment: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                projectAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                projectAmountMoneyInTenantCurrency: {
                  amount: 0,
                  currency: "",
                },
                categories: [],
                departments: [],
                callbackOutcomes: [],
                accountCode: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                requestType: "",
                impact: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                activityName: "Test Auto Approval - Apple",
                priority: "",
                vendorClassification: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                businessRegions: [],
                companyEntityCountryCodes: [],
                partners: [
                  {
                    selectedVendorRecord: {
                      companyEntityRef: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabledSystems: [],
                      name: "",
                      additionalCompanyEntities: [],
                      vendorId: "",
                      paymentTerm: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabled: false,
                      currencies: [],
                    },
                    legalEntityId: "88868992675233957",
                    countryCode: "IN",
                    contact: {
                      lastName: "",
                      country: "",
                      note: "",
                      address: {
                        province: "",
                        city: "",
                        streetNumber: "",
                        alpha2CountryCode: "",
                        unitNumber: "",
                        language: "",
                        postal: "",
                        line3: "",
                        line2: "",
                        line1: "",
                      },
                      role: "",
                      emailVerification: {
                        verificationFailureReason: "",
                        domainNotExist: false,
                        emailNotDeliverable: false,
                        isFreeDomain: false,
                        verified: false,
                        email: "",
                      },
                      phoneVerified: false,
                      fullName: "",
                      title: "",
                      firstName: "",
                      emailVerified: false,
                      phone: "",
                      imageUrl: "",
                      requireBackgroundCheck: false,
                      id: "",
                      email: "",
                      sharePercentage: 0,
                    },
                    name: "Apple",
                    vendorRecords: [],
                    sanctionList: [],
                    activationStatus: "duplicate",
                    legalEntityLogo: {
                      metadata: [
                        {
                          path: "oro/images/small/88868992675233957.png",
                          width: 100,
                          height: 100,
                        },
                        {
                          path: "oro/images/large/88868992675233957.png",
                          width: 200,
                          height: 200,
                        },
                      ],
                      backgroundColor: "",
                    },
                    id: "89113807414099968",
                    isIndividual: false,
                    shareHolders: [],
                  },
                ],
                contractAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                paymentMethod: "",
                companyEntities: [],
                companyEntityCurrencyCode: "",
                engagementId: "",
                po: {
                  cost: 0,
                  poNumber: "",
                  currencyCode: "",
                },
              },
              infoRequests: [],
              lastStatusUpdate: "",
              currencySymbol: "",
              started: "2023-08-10T14:35:15.441510150Z",
              completed: "",
              relatedEnagements: [],
              hasChildRequests: false,
              watched: false,
              selection: {
                requester: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                businessUnits: [],
                brands: [],
                partnerRegions: [],
                regions: [],
                spendBucket: 0,
                projectLevels: [],
                isNewPartner: false,
                categories: [],
                partnerLevels: [],
              },
              amountDifferenceMoney: {
                amount: 0,
                currency: "",
              },
              name: "Test Auto Approval",
              processing: false,
              progress: {
                stepsCompleted: 0,
                needsUpdate: false,
                milestoneWarning: false,
                completedTime: 0,
                submitByDate: "",
                daysToApprovalSubmiteDate: 0,
                totalEstimateTime: 3,
                tasksStarted: false,
                stepsTotal: 3,
                noUpdateDate: "",
                noUpdateLastWeek: false,
                milestoneOverdue: false,
              },
              workStream: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              milestones: [],
              engagementId: "1231452",
              updated: "2023-08-10T14:35:54.695520062Z",
              currencyCode: "",
              nextTask: {
                owner: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                lastMsgBy: "",
                partnerName: "",
                infoMsgId: "",
                functionRole: "",
                started: "",
                msgClosed: false,
                submissionComment: "",
                completed: "",
                type: "",
                title: "Review",
                users: [],
                assignmentType: "group",
                suspended: false,
                lastMsgUser: "",
                resubmitted: false,
                functionGroup: "",
                workstream: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                lateTime: "",
                groupIds: [
                  {
                    groupName: "admin",
                    groupId: "admin",
                    tenantId: "",
                    selected: false,
                  },
                ],
                lastMsg: "",
                assignedToCurrentUser: false,
                lastMsgTime: "",
                taskId: "",
              },
              contacts: [],
              status: "Pending",
            },
          ],
          visiblity: "all",
        },
      },
      {
        id: 124,
        owner: {
          name: "John Doe",
          userName: "john@foo.com",
          api: false,
          groupIds: [],
          selected: false,
          tenantId: "foo",
          department: "",
          picture: "",
          firstName: "",
          lastName: "",
          email: "john@foo.com",
          isOtp: false,
        },
        sharedWith: null,
        name: "sample2",
        type: "request" as ListType,
        config: {
          requests: [
            {
              kpiUnit: "",
              hasEbit: false,
              vendorId: "",
              description: "",
              lateMilestones: 0,
              issues: [],
              currentMilestone: "",
              appType: "",
              projectAmount: {
                amount: 0,
                currency: "",
              },
              projectAmountMoney: {
                amount: 0,
                currency: "",
              },
              segment: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              members: [],
              alreadyMember: false,
              id: "340050104075241011",
              coOwners: [],
              currentRequest: {
                processName: "Doc Collection",
                requestId: "ORO11771",
                mainProcessId: "340050573724042803",
                processStarted: "2023-08-03T02:02:06.329649577Z",
                id: "340050103857137204",
                type: "onboarding",
              },
              requester: {
                firstName: "",
                lastName: "",
                groupIds: [],
                name: "John Doe",
                tenantId: "foo",
                api: false,
                userName: "john@foo.com",
                department: "",
                isOtp: false,
                selected: false,
                picture: "",
                email: "",
              },
              upcomingMilestones: 0,
              pendingTasks: [
                {
                  lastMsgBy: "",
                  infoMsgId: "",
                  functionRole: "",
                  type: "documentCollection",
                  title: "Document collection",
                  assignmentType: "partner",
                  lastMsgUser: "",
                  functionGroup: "",
                  groupIds: [],
                  lastMsgTime: "",
                  taskStatus: "pending",
                  owner: {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "John Doe",
                    tenantId: "foo",
                    api: false,
                    userName: "john@foo.com",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                  partnerName: "IBM",
                  started: "2023-08-03T02:02:06.374137195Z",
                  msgClosed: false,
                  submissionComment: "",
                  completed: "",
                  users: [
                    {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "John Doe",
                      tenantId: "",
                      api: false,
                      userName: "john@foo.com",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                  ],
                  suspended: false,
                  resubmitted: false,
                  workstream: {
                    name: "",
                    erpId: "",
                    id: "",
                    refId: "",
                    version: "",
                  },
                  lateTime: "2023-08-05T02:02:06.377542843Z",
                  lastMsg: "",
                  assignedToCurrentUser: false,
                  taskId: "340050573925369395",
                },
              ],
              variables: {
                regions: [
                  {
                    name: "United States",
                    erpId: "",
                    id: "19-21-US",
                    refId: "",
                    version: "",
                  },
                ],
                businessUnit: [],
                projectTypes: [],
                sites: [],
                contracts: [],
                segments: [],
                startingSubprocessName: "",
                assesssmentScopes: [],
                processName: "",
                requestId: "",
                segment: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                projectAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                projectAmountMoneyInTenantCurrency: {
                  amount: 0,
                  currency: "",
                },
                categories: [
                  {
                    name: "Apparel and Luggage and Personal Care Products",
                    erpId: "",
                    id: "53",
                    refId: "",
                    version: "",
                  },
                ],
                departments: [],
                callbackOutcomes: [],
                accountCode: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                requestType: "",
                impact: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                activityName: "Supplier onboarding",
                priority: "",
                vendorClassification: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                businessRegions: [],
                companyEntityCountryCodes: [],
                partners: [
                  {
                    selectedVendorRecord: {
                      companyEntityRef: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabledSystems: [],
                      name: "",
                      additionalCompanyEntities: [],
                      vendorId: "",
                      paymentTerm: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabled: false,
                      currencies: [],
                    },
                    legalEntityId: "86900080084648685",
                    countryCode: "US",
                    contact: {
                      firstName: "",
                      lastName: "",
                      emailVerified: false,
                      address: {
                        province: "",
                        city: "",
                        streetNumber: "",
                        alpha2CountryCode: "",
                        unitNumber: "",
                        language: "",
                        postal: "",
                        line3: "",
                        line2: "",
                        line1: "",
                      },
                      role: "Account Manager",
                      phone: "",
                      phoneVerified: false,
                      imageUrl: "",
                      fullName: "Yuan Tung",
                      id: "",
                      title: "",
                      email: "yuan.tung@orolabs.ai",
                    },
                    name: "IBM",
                    vendorRecords: [],
                    activationStatus: "requiresActivation",
                    legalEntityLogo: {
                      metadata: [
                        {
                          path: "oro/images/small/87124277144322048.png",
                          width: 0,
                          height: 0,
                        },
                        {
                          path: "oro/images/large/87124277144322048.png",
                          width: 0,
                          height: 0,
                        },
                      ],
                      backgroundColor: "",
                    },
                    id: "87124277144322048",
                    isIndividual: false,
                  },
                ],
                contractAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                paymentMethod: "",
                companyEntities: [
                  {
                    name: "Honeycomb Holdings Inc.",
                    erpId: "4",
                    id: "HH",
                    refId: "",
                    version: "",
                  },
                ],
                companyEntityCurrencyCode: "",
                engagementId: "",
                po: {
                  cost: 0,
                  poNumber: "",
                  currencyCode: "",
                },
              },
              infoRequests: [],
              lastStatusUpdate: "",
              currencySymbol: "",
              started: "2023-08-03T02:00:14.366405774Z",
              completed: "",
              relatedEnagements: [],
              hasChildRequests: false,
              watched: false,
              selection: {
                requester: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                businessUnits: [],
                brands: [],
                partnerRegions: [],
                regions: [],
                spendBucket: 0,
                projectLevels: [],
                isNewPartner: false,
                categories: [],
                partnerLevels: [],
              },
              amountDifferenceMoney: {
                amount: 0,
                currency: "",
              },
              name: "Doc Collection",
              processing: false,
              progress: {
                stepsCompleted: 0,
                needsUpdate: false,
                milestoneWarning: false,
                completedTime: 0,
                submitByDate: "",
                daysToApprovalSubmiteDate: 0,
                totalEstimateTime: 2,
                tasksStarted: false,
                stepsTotal: 2,
                noUpdateDate: "",
                noUpdateLastWeek: false,
                milestoneOverdue: false,
              },
              workStream: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              milestones: [],
              engagementId: "1231348",
              updated: "2023-08-03T06:11:34.154919685Z",
              currencyCode: "",
              nextTask: {
                owner: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                lastMsgBy: "",
                partnerName: "",
                infoMsgId: "",
                functionRole: "",
                started: "",
                msgClosed: false,
                submissionComment: "",
                completed: "",
                type: "",
                title: "Approval",
                users: [
                  {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "Rohit Ingle",
                    tenantId: "",
                    api: false,
                    userName: "rohit@orolabs.ai",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                ],
                assignmentType: "user",
                suspended: false,
                lastMsgUser: "",
                resubmitted: false,
                functionGroup: "",
                workstream: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                lateTime: "",
                groupIds: [],
                lastMsg: "",
                assignedToCurrentUser: false,
                lastMsgTime: "",
                taskId: "",
              },
              contacts: [
                {
                  lastName: "",
                  note: "",
                  address: {
                    province: "",
                    city: "",
                    streetNumber: "",
                    alpha2CountryCode: "",
                    unitNumber: "",
                    language: "",
                    postal: "",
                    line3: "",
                    line2: "",
                    line1: "",
                  },
                  role: "Account Manager",
                  contactId: "",
                  phoneVerified: false,
                  fullName: "Yuan Tung",
                  title: "",
                  firstName: "",
                  emailVerified: false,
                  selection: {
                    requester: {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "",
                      tenantId: "",
                      api: false,
                      userName: "",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                    businessUnits: [],
                    brands: [],
                    partnerRegions: [],
                    regions: [],
                    spendBucket: 0,
                    projectLevels: [],
                    isNewPartner: false,
                    categories: [],
                    partnerLevels: [],
                  },
                  phone: "",
                  supplierUserId: "",
                  imageUrl: "",
                  tenantId: "",
                  id: "",
                  engagementId: "",
                  email: "yuan.tung@orolabs.ai",
                },
              ],
              status: "Pending",
            },
            {
              kpiUnit: "",
              hasEbit: false,
              vendorId: "",
              description: "",
              lateMilestones: 0,
              issues: [],
              currentMilestone: "",
              appType: "",
              projectAmount: {
                amount: 0,
                currency: "",
              },
              projectAmountMoney: {
                amount: 0,
                currency: "",
              },
              segment: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              members: [],
              alreadyMember: false,
              id: "340048701441263155",
              coOwners: [],
              currentRequest: {
                processName: "Doc Collection",
                requestId: "ORO11770",
                mainProcessId: "340048986485505078",
                processStarted: "2023-08-03T01:55:47.902377841Z",
                id: "340048701281879604",
                type: "onboarding",
              },
              requester: {
                firstName: "",
                lastName: "",
                groupIds: [],
                name: "John Doe",
                tenantId: "foo",
                api: false,
                userName: "john@foo.com",
                department: "",
                isOtp: false,
                selected: false,
                picture: "",
                email: "",
              },
              upcomingMilestones: 0,
              pendingTasks: [
                {
                  lastMsgBy: "",
                  infoMsgId: "",
                  functionRole: "",
                  type: "documentCollection",
                  title: "Document collection",
                  assignmentType: "partner",
                  lastMsgUser: "",
                  functionGroup: "",
                  groupIds: [],
                  lastMsgTime: "",
                  taskStatus: "pending",
                  owner: {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "Azad Shaikh",
                    tenantId: "foo",
                    api: false,
                    userName: "azad.rocku@gmail.com",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                  partnerName: "Apple Inc",
                  started: "2023-08-03T01:57:49.013773139Z",
                  msgClosed: false,
                  submissionComment: "",
                  completed: "",
                  users: [
                    {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "John Doe",
                      tenantId: "",
                      api: false,
                      userName: "john@foo.com",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                  ],
                  suspended: false,
                  resubmitted: true,
                  workstream: {
                    name: "",
                    erpId: "",
                    id: "",
                    refId: "",
                    version: "",
                  },
                  lateTime: "2023-08-05T01:57:49.016418236Z",
                  lastMsg: "",
                  assignedToCurrentUser: false,
                  taskId: "340049494475097651",
                },
              ],
              variables: {
                regions: [
                  {
                    name: "United States",
                    erpId: "",
                    id: "19-21-US",
                    refId: "",
                    version: "",
                  },
                ],
                businessUnit: [],
                projectTypes: [],
                sites: [],
                contracts: [],
                segments: [],
                startingSubprocessName: "",
                assesssmentScopes: [],
                processName: "",
                requestId: "",
                segment: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                projectAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                projectAmountMoneyInTenantCurrency: {
                  amount: 0,
                  currency: "",
                },
                categories: [
                  {
                    name: "Apparel and Luggage and Personal Care Products",
                    erpId: "",
                    id: "53",
                    refId: "",
                    version: "",
                  },
                ],
                departments: [],
                callbackOutcomes: [],
                accountCode: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                requestType: "",
                impact: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                activityName: "Supplier onboarding",
                priority: "",
                vendorClassification: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                businessRegions: [],
                companyEntityCountryCodes: [],
                partners: [
                  {
                    selectedVendorRecord: {
                      companyEntityRef: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabledSystems: [],
                      name: "",
                      additionalCompanyEntities: [],
                      vendorId: "",
                      paymentTerm: {
                        name: "",
                        erpId: "",
                        id: "",
                        refId: "",
                        version: "",
                      },
                      enabled: false,
                      currencies: [],
                    },
                    legalEntityId: "197472170988429316",
                    countryCode: "US",
                    contact: {
                      firstName: "",
                      lastName: "",
                      emailVerified: false,
                      address: {
                        province: "",
                        city: "",
                        streetNumber: "",
                        alpha2CountryCode: "",
                        unitNumber: "",
                        language: "",
                        postal: "",
                        line3: "",
                        line2: "",
                        line1: "",
                      },
                      role: "Infosec",
                      phone: "",
                      phoneVerified: false,
                      imageUrl: "",
                      fullName: "Azad Shaikh",
                      id: "",
                      title: "",
                      email: "azad.rocku@gmail.com",
                    },
                    name: "Apple Inc",
                    vendorRecords: [],
                    activationStatus: "newSupplier",
                    legalEntityLogo: {
                      metadata: [
                        {
                          path: "oro/images/large/197472170988429316.png",
                          width: 200,
                          height: 200,
                        },
                        {
                          path: "oro/images/small/197472170988429316.png",
                          width: 100,
                          height: 100,
                        },
                      ],
                      backgroundColor: "",
                    },
                    id: "202885259988041728",
                    isIndividual: false,
                  },
                ],
                contractAmountMoney: {
                  amount: 0,
                  currency: "",
                },
                paymentMethod: "",
                companyEntities: [
                  {
                    name: "Honeycomb Holdings Inc.",
                    erpId: "4",
                    id: "HH",
                    refId: "",
                    version: "",
                  },
                ],
                companyEntityCurrencyCode: "",
                engagementId: "",
                po: {
                  cost: 0,
                  poNumber: "",
                  currencyCode: "",
                },
              },
              infoRequests: [],
              lastStatusUpdate: "",
              currencySymbol: "",
              started: "2023-08-03T01:54:39.953046323Z",
              completed: "",
              relatedEnagements: [],
              hasChildRequests: false,
              watched: false,
              selection: {
                requester: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                businessUnits: [],
                brands: [],
                partnerRegions: [],
                regions: [],
                spendBucket: 0,
                projectLevels: [],
                isNewPartner: false,
                categories: [],
                partnerLevels: [],
              },
              amountDifferenceMoney: {
                amount: 0,
                currency: "",
              },
              name: "Doc Collection",
              processing: false,
              progress: {
                stepsCompleted: 0,
                needsUpdate: false,
                milestoneWarning: false,
                completedTime: 0,
                submitByDate: "",
                daysToApprovalSubmiteDate: 0,
                totalEstimateTime: 2,
                tasksStarted: false,
                stepsTotal: 2,
                noUpdateDate: "",
                noUpdateLastWeek: false,
                milestoneOverdue: false,
              },
              workStream: {
                name: "",
                erpId: "",
                id: "",
                refId: "",
                version: "",
              },
              milestones: [],
              engagementId: "1231347",
              updated: "2023-08-03T01:59:26.503213841Z",
              currencyCode: "",
              nextTask: {
                owner: {
                  firstName: "",
                  lastName: "",
                  groupIds: [],
                  name: "",
                  tenantId: "",
                  api: false,
                  userName: "",
                  department: "",
                  isOtp: false,
                  selected: false,
                  picture: "",
                  email: "",
                },
                lastMsgBy: "",
                partnerName: "",
                infoMsgId: "",
                functionRole: "",
                started: "",
                msgClosed: false,
                submissionComment: "",
                completed: "",
                type: "",
                title: "Approval",
                users: [
                  {
                    firstName: "",
                    lastName: "",
                    groupIds: [],
                    name: "Rohit Ingle",
                    tenantId: "",
                    api: false,
                    userName: "rohit@orolabs.ai",
                    department: "",
                    isOtp: false,
                    selected: false,
                    picture: "",
                    email: "",
                  },
                ],
                assignmentType: "user",
                suspended: false,
                lastMsgUser: "",
                resubmitted: false,
                functionGroup: "",
                workstream: {
                  name: "",
                  erpId: "",
                  id: "",
                  refId: "",
                  version: "",
                },
                lateTime: "",
                groupIds: [],
                lastMsg: "",
                assignedToCurrentUser: false,
                lastMsgTime: "",
                taskId: "",
              },
              contacts: [
                {
                  lastName: "",
                  note: "",
                  address: {
                    province: "",
                    city: "",
                    streetNumber: "",
                    alpha2CountryCode: "",
                    unitNumber: "",
                    language: "",
                    postal: "",
                    line3: "",
                    line2: "",
                    line1: "",
                  },
                  role: "Infosec",
                  contactId: "",
                  phoneVerified: false,
                  fullName: "Azad Shaikh",
                  title: "",
                  firstName: "",
                  emailVerified: false,
                  selection: {
                    requester: {
                      firstName: "",
                      lastName: "",
                      groupIds: [],
                      name: "",
                      tenantId: "",
                      api: false,
                      userName: "",
                      department: "",
                      isOtp: false,
                      selected: false,
                      picture: "",
                      email: "",
                    },
                    businessUnits: [],
                    brands: [],
                    partnerRegions: [],
                    regions: [],
                    spendBucket: 0,
                    projectLevels: [],
                    isNewPartner: false,
                    categories: [],
                    partnerLevels: [],
                  },
                  phone: "",
                  supplierUserId: "",
                  imageUrl: "",
                  tenantId: "",
                  id: "",
                  engagementId: "",
                  email: "azad.rocku@gmail.com",
                },
              ],
              status: "Pending",
            },
          ],
          visiblity: "all",
        },
      },
    ],
    sharedWithMe: [],
  },
};
