import React from "react";
import { StoryFn } from "@storybook/react";

import {
  BankInfoFormData,
  BankInfoFormProps,
  NewBankInfoForm,
} from "./../../lib";
import { bankKeys } from "../mocks/bankKeys";
import { getI18NInstance } from "./../../lib/i18n";

const formData: BankInfoFormData = {
  businessEmail: "yuan.tung@orolabs.ai",
  instruction: "Instruction testing",
  companyEntityCountryCode: "DE",
  intermediaryBankInformation: null,
  // "new": false,
  // "edited": false,
  bankInformation: {
    accountHolderAddress: {
      province: "SE-Stockholms län",
      streetNumber: "12",
      city: "Stockholm",
      unitNumber: "Skeppsbron",
      alpha2CountryCode: "SE",
      language: "",
      postal: "111 30",
      line3: "",
      line2: "Södermalm",
      line1: "",
    },
    // "accountHolderAddress": {
    //   "province": "",
    //   "streetNumber": "",
    //   "city": "",
    //   "unitNumber": "",
    //   "alpha2CountryCode": "SE",
    //   "language": "",
    //   "postal": "",
    //   "line3": "",
    //   "line2": "",
    //   "line1": ""
    // },
    bankCode: "1234567",
    encryptedBankCode: undefined,
    omitInternalAccountNUmber: false,
    // "currencyCodeStr": "SEK",
    bankName: "Publ",
    accountNumber: {
      data: "",
      maskedValue: "",
      unencryptedValue: "",
      version: "",
      iv: "",
    },
    encryptedInternationalBankCode: undefined,
    internationalCodeEncrypted: false,
    accountHolder: "Yuan ",
    bankCodeEncrypted: false,
    internationalKey: "swift",
    internationalCode: "",
    internationalCodeError: false,
    omitAccountNumber: true,
    bankCodeError: false,
    currencyCode: {
      displayName: "Swedish Krona (SEK)",
      // "erpId": "",
      id: "SEK",
      path: "SEK",
    },
    key: "bankgiro",
  },
  intermediaryBankRequired: false,
};

export default {
  title: "ORO UI Toolkit/Form/BankInfo Form",
  component: NewBankInfoForm,
};
getI18NInstance(true);

export const TemplateForm = {
  args: {
    fields: [
      {
        booleanValue: true,
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "account",
        instruction: null,
        modifiable: false,
        order: 1,
        requirement: "required",
        sectionTitle: null,
        title: "Account",
        type: "string",
      },
      {
        booleanValue: true,
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "abaRoutingNumber",
        instruction: null,
        modifiable: false,
        order: 1,
        requirement: "required",
        sectionTitle: null,
        title: "Aba Routing Number",
        type: "string",
      },
    ],
    formData,
    countryOptions: [
      {
        displayName: "Sweden",
        // "erpId": "",
        id: "SE",
        path: "SE",
        selectable: true,
      },
    ],
    currencyOptions: [
      {
        displayName: "Swedish Krona (SEK)",
        // "erpId": "",
        id: "SEK",
        path: "SEK",
      },
    ],
    bankKeys,
    isCrossBorder: true,
    domesticKeyOptions: [
      {
        bankKey: "bankgiro",
        bankCodeEncrypted: false,
        omitAccountNumber: true,
      },
      { bankKey: "iban", bankCodeEncrypted: true, omitAccountNumber: true },
    ],
    submitLabel: "Submit",
    cancelLabel: "cancel",
    onReady: () => {},
    existingBankInfo: [
      {
        id: "299623495127080886",
        externalId: null,
        created: "2023-04-13T12:38:12.886153039Z",
        currencyCodeStr: "USD",
        currencyCode: {
          id: "USD",
          name: "US Dollar",
        },
        bankName: "Test Bank",
        accountHolder: "Account name",
        accountHolderAddress: {
          line1: "9913 US Hwy 41 S, Concerned Citizens of Gibsonton Area",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Gibsonton",
          province: "Florida",
          alpha2CountryCode: "US",
          postal: "33534",
          language: "",
        },
        key: "abaRoutingNumber",
        bankCodeEncrypted: false,
        omitAccountNumber: false,
        bankCode: "121000248",
        bankCodeError: false,
        accountNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "NOUrMjfZaKT/JYnLYSklSQ==",
          iv: "+Ag2VOOTBPXiREvOgWQoHA==",
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: "********",
          setBy: {
            tenantId: "foo",
            tenantName: "Foo Company",
            userName: "john@foo.com",
            name: "John Doe",
            department: null,
            departmentCode: null,
            departmentErpId: null,
            groupIds: null,
            type: "Tenant",
            email: "john@foo.com",
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: "103.149.127.82",
            impersonator: null,
            admin: true,
            otp: false,
            procurementAdmin: true,
          },
        },
        encryptedBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalKey: null,
        internationalCode: null,
        internationalCodeEncrypted: false,
        omitInternalAccountNUmber: false,
        encryptedInternationalBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalCodeError: false,
        bankAddress: null,
        companyEntityRef: {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
        },
        customFields: null,
        intermediaryBankInfo: {
          bankCodeError: false,
        },
        bankAccountType: null,
        paymentInstruction: null,
        idString: "299623495127080886",
      },
      {
        id: "299623495127080886",
        externalId: null,
        created: "2023-04-13T12:38:12.886153039Z",
        currencyCodeStr: "USD",
        currencyCode: {
          id: "USD",
          name: "US Dollar",
        },
        bankName: "Test Bank 2",
        accountHolder: "Account name",
        accountHolderAddress: {
          line1: "9913 US Hwy 41 S, Concerned Citizens of Gibsonton Area",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Gibsonton",
          province: "Florida",
          alpha2CountryCode: "US",
          postal: "33534",
          language: "",
        },
        key: "abaRoutingNumber",
        bankCodeEncrypted: false,
        omitAccountNumber: false,
        bankCode: "121000248",
        bankCodeError: false,
        accountNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "NOUrMjfZaKT/JYnLYSklSQ==",
          iv: "+Ag2VOOTBPXiREvOgWQoHA==",
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: "********",
          setBy: {
            tenantId: "foo",
            tenantName: "Foo Company",
            userName: "john@foo.com",
            name: "John Doe",
            department: null,
            departmentCode: null,
            departmentErpId: null,
            groupIds: null,
            type: "Tenant",
            email: "john@foo.com",
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: "103.149.127.82",
            impersonator: null,
            admin: true,
            otp: false,
            procurementAdmin: true,
          },
        },
        encryptedBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalKey: null,
        internationalCode: null,
        internationalCodeEncrypted: false,
        omitInternalAccountNUmber: false,
        encryptedInternationalBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          restrainDecryptData: true,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalCodeError: false,
        bankAddress: null,
        companyEntityRef: {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
        },
        customFields: null,
        intermediaryBankInfo: {
          bankCodeError: false,
        },
        bankAccountType: null,
        paymentInstruction: null,
        idString: "299623495127080886",
      },
    ],
  },
};
