import React from "react";
import { StoryFn } from "@storybook/react";
import { BankCallbackFormReadOnly } from "../../lib";
import { BankCallbackFormProps } from "../../lib/Form/types";

const mockCallBackToOptions = [
  {
    id: "corporate",
    displayName: "Corporate",
    path: "corporate",
    selected: false,
    selectable: true,
  },
  {
    id: "ignoreBankAccount",
    displayName: "Ignore Bank Account",
    path: "ignoreBankAccount",
    selected: false,
    selectable: true,
  },
  {
    id: "verified",
    displayName: "Verified",
    path: "verified",
    selected: false,
    selectable: true,
  },
];

const mockCallbackOptions = [
  {
    id: "SOC",
    displayName: "Source of Contact",
    path: "sourceContact",
    selected: false,
    selectable: true,
  },
  {
    id: "SIM",
    displayName: "SIM / Existing Vendor Master",
    path: "vendorMaster",
    selected: false,
    selectable: true,
  },
  {
    id: "PI",
    displayName: "Past Invoices",
    path: "pastInvoice",
    selected: false,
    selectable: true,
  },
  {
    id: "COR",
    displayName: "Corporate Website",
    path: "corporateWebsite",
    selected: false,
    selectable: true,
  },
  {
    id: "BO",
    displayName: "Business Owners",
    path: "businessOwners",
    selected: false,
    selectable: true,
  },
  {
    id: "EV",
    displayName: "Email From Vendor",
    path: "emailFromVendor",
    selected: false,
    selectable: true,
  },
];

const finalOutcomeOptions = [
  {
    id: "verified",
    displayName: "Account verified",
    path: "accountverified",
    selected: false,
    selectable: true,
  },
  {
    id: "contigencyPlanApplied",
    displayName: "Contigency Plan Applied",
    path: "contigencyPlan",
    selected: false,
    selectable: true,
  },
  {
    id: "exception",
    displayName: "Exception Required",
    path: "exceptionRequired",
    selected: false,
    selectable: true,
  },
  {
    id: "fraudDetected",
    displayName: "Possible fraud detected",
    path: "potentialfraud",
    selected: false,
    selectable: true,
  },
  {
    id: "supplierUnavailable",
    displayName: "Supplier unavailable",
    path: "supplierunavailable",
    selected: false,
    selectable: true,
  },
  {
    id: "ignoreBankAccount",
    displayName: "Ignore bank account",
    path: "ignorebankaccount",
    selected: false,
    selectable: true,
  },
];

export default {
  title: "ORO UI Toolkit/Form/Bank CallbackForm ReadOnly",
  component: BankCallbackFormReadOnly,
};

export const TemplateForm = {
  args: {
    formData: {
      outcomes: [
        {
          index: 0,
          accountNumber: {
            data: "",
            maskedValue: "********90",
            unencryptedValue: "12345",
            version: "",
            iv: "",
          },
          code: "verified",
        },
        {
          index: 1,
          accountNumber: {
            data: "",
            maskedValue: "********90",
            unencryptedValue: null,
            version: "",
            iv: "",
          },
          code: "ignoreBankAccount",
        },
      ],
      callbackHistory: [
        {
          callback: "Corporate",
          email: "c.mango@cmdigital.com",
          notes: "No response via email",
          creationTime: "2022-03-16T05:45:57.754863Z",
          userId: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Doe",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        {
          callback: "Corporate",
          phone: "+1 893 456 7884",
          notes: "No response via phone",
          creationTime: "2022-03-17T05:45:57.754863Z",
          userId: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-gandharva@orolabs.ai",
            name: "Lisa Smith",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        {
          callback: "Corporate",
          email: "c.mango@cmdigital.com",
          notes: "Incorrect contact, email bounced",
          creationTime: "2022-03-18T05:45:57.754863Z",
          userId: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Wick",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
      ],
      callbackEvents: [
        {
          callbackTo: "Corporate",
          method: "email",
          email: "c.mango@cmdigital.com",
          note: "No response via email",
          contactSources: [
            { erpId: "", id: "sourceContact", name: "Source Contact" },
            { erpId: "", id: "emailFromVendor", name: "Email From Vendor" },
          ],
          callbackTime: "2022-03-16T05:45:57.754863Z",
          noteAttachments: [
            {
              date: null,
              expiration: null,
              filename: "a.csv",
              mediatype: "text/csv",
              name: null,
              note: null,
              path: "attachment/65099653170855936/a.csv",
              reference: null,
              size: 185,
            },
            {
              date: null,
              expiration: null,
              filename: "sadasdasdasa.csv",
              mediatype: ".pdf",
              name: null,
              note: null,
              path: "attachment/65099653170855936/a.csv",
              reference: null,
              size: 185,
            },
          ],
          requester: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Doe",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        {
          callbackTo: "Corporate",
          method: "phone",
          phoneNumber: "+1 893 456 7884",
          contactSources: [
            { erpId: "", id: "corporateWebsite", name: "Corporate website" },
          ],
          note: "I got in touch with Steve from thier finance team. He is yet to submit past 12 months IT bank statements. But all other details are intact.",
          callbackTime: "2022-03-17T05:45:57.754863Z",
          requester: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-gandharva@orolabs.ai",
            name: "Lisa Smith",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        {
          callbackTo: "Corporate",
          method: "email",
          email: "c.mango@cmdigital.com",
          note: "I got in touch with Steve from thier finance team. He is yet to submit past 12 months IT bank statements. But all other details are intact.",
          contactSources: [
            { erpId: "", id: "pastInvoice", name: "Past Invoice" },
          ],
          callbackTime: "2022-03-18T05:45:57.754863Z",
          requester: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Wick",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
      ],
    },
    callBackToOptions: mockCallBackToOptions,
    callBackOptions: mockCallbackOptions,
    outcomeOptions: finalOutcomeOptions,
  },
};
