import React from "react";
import { StoryFn } from "@storybook/react";
import { ChatGPTChatBotForm } from "../../lib";
import { ChatGPTFormProps } from "../../lib/Form/ChatGPT";
import {
  mockCategory,
  mockCurrencyOptions,
  mockOptionsRegion,
  mockUser,
} from "../MultiLevelSelect/mocks";
import { DEFAULT_CURRENCY } from "../../lib/util";

const mockChatGPTResponse = {
  suggestedCategories: [
    {
      id: "_Category__Any__130",
      displayName: "Logistics services",
      path: "ALL-10-130",
      customData: {
        id: "Category__Any__130",
        description: "Logistics services",
        longDescription: "Logistics services",
        codePath: "ALL-10-130",
        code: "130",
        origCode: "130",
        erpId: "130",
        parentCode: "10",
        ancestorNames: [],
        level: 3,
        order: null,
        other: {
          currencyId: "",
          currencyCode: "",
          contractType: "",
          countryCode: "",
          domestic: "",
          international: "",
          documents: "",
        },
      },
      icon: "",
      selected: false,
      selectable: true,
    },
    {
      id: "_Category__Any__120",
      displayName: "Regional Transportation & Storage",
      path: "ALL-10-120",
      customData: {
        id: "Category__Any__120",
        description: "Regional Transportation & Storage",
        longDescription: "Regional Transportation & Storage",
        codePath: "ALL-10-120",
        code: "120",
        origCode: "120",
        erpId: "120",
        parentCode: "10",
        ancestorNames: [],
        level: 3,
        order: null,
        other: {
          currencyId: "",
          currencyCode: "",
          contractType: "",
          countryCode: "",
          domestic: "",
          international: "",
          documents: "",
        },
      },
      icon: "",
      selected: false,
      selectable: true,
    },
  ],
  gptSuggestion: {
    Intent: "Create Purchase Order (PO)",
    Product_name: "3d printer",
    commodity_list: [
      "IT | Application / Consulting | Time & Material | Development advancement customizing (IT)",
      "IT | Application / Consulting | Managed Project",
    ],
    commodity_code_list: ["T10 | 150 | 158 | 25240600", "T10 | 150 | 157"],
    total_budget: "20000 USD",
    country_code: "option5",
    "PR Suppliers": [
      {
        commodity_id: "27260000",
        company_code: "2001-P2R",
        erp_supplier: "RS Components GmbH",
        erp_supplier_id: 4883480,
        requester_user_id: "User21003",
        requisition_title: "Polymaker TPU 95A 3D-Drucker Filament, ...",
        "sum(PO Spend)": 5475,
        supplier_status: "Preferred",
      },
      {
        commodity_id: "27260000",
        company_code: "2001-P2R",
        erp_supplier: "RS Components GmbH",
        erp_supplier_id: 4883480,
        requester_user_id: "User21003",
        requisition_title: "BASF Ultrafuse PP 3D-Drucker Filament zur ...",
        "sum(PO Spend)": 26830,
        supplier_status: "Preferred",
      },
      {
        commodity_id: "27260000",
        company_code: "0347-P69",
        erp_supplier: "RS Components GmbH",
        erp_supplier_id: 4883480,
        requester_user_id: "User4377",
        requisition_title: "Ersatzteile 3D Drucker",
        "sum(PO Spend)": 19826,
        supplier_status: "Preferred",
      },
      {
        commodity_id: "27260000",
        company_code: "2001-P2R",
        erp_supplier: "RS Components GmbH",
        erp_supplier_id: 4883480,
        requester_user_id: "User20997",
        requisition_title: "3D Drucker Material",
        "sum(PO Spend)": 18894,
        supplier_status: "Preferred",
      },
      {
        commodity_id: "27260000",
        company_code: "2001-P2R",
        erp_supplier: "RS Components GmbH",
        erp_supplier_id: 4883480,
        requester_user_id: "User20997",
        requisition_title: "Polymaker Robustes PLA 3D-Drucker Filament, ...",
        "sum(PO Spend)": 26898,
        supplier_status: "Preferred",
      },
      {
        commodity_id: "32010000",
        company_code: "2001-P2R",
        erp_supplier: "Fisher Scientific GmbH",
        erp_supplier_id: 8568903,
        requester_user_id: "User25513",
        requisition_title: "3D-Druck",
        "sum(PO Spend)": 13515,
        supplier_status: "Preferred",
      },
    ],
  },
};

const mockData = {
  categories: [
    {
      id: "IT | Application / Consulting | Time & Material | Development advancement customizing (IT)",
      displayName: "Development advancement customizing (IT)",
      path: "T10 | 150 | 158 | 25240600",
      selected: true,
      selectable: true,
      pathDisplayName: "IT ,  Application / Consulting ,  Time & Material",
    },
    {
      id: "IT | Application / Consulting | Managed Project",
      displayName: "Managed Project",
      path: "T10 | 150 | 157",
      selected: true,
      selectable: true,
      pathDisplayName: "IT ,  Application / Consulting",
    },
  ],
  regions: [
    {
      id: "option5",
      path: "option5",
      displayName: "option5",
      customData: {
        erpId: "option5",
      },
      selectable: true,
      selected: false,
    },
  ],
  departments: [],
  supplierSuggestions: [],
};

const mockSuppliers = [
  {
    supplierName: "Fisher Scientific GmbH",
    address: {
      alpha2CountryCode: "DE",
      city: "Unna",
      language: "",
      line1: "Im Heiligen Feld 17",
      line2: "",
      line3: "",
      postal: "",
      province: "DE-NW",
      streetNumber: "",
      unitNumber: "",
    },
    email: "",
    phoneNumber: "",
    website: "https://www.thermofisher.com/",
    duns: "",
    vendorId: "365271035872756481",
    legalEntity: {
      active: true,
      forbesGlobal: false,
      fortune500: false,
      legalEntityName: "Fisher Scientific GmbH",
      id: "365231411782738839",
      numSubsidiaries: 0,
      otherNames: [],
      name: {
        active: false,
        language: null,
        name: null,
        source: null,
        type: null,
      },
      parent: false,
      ultimateParent: false,
      logo: {
        metadata: [
          {
            path: "oro/images/large/365231411782738839.svg",
            height: 0,
            width: 0,
          },
        ],
      },
      commonName: {
        active: true,
        language: "en",
        name: "Fisher Scientific GmbH",
        source: null,
        type: "trading_or_operating",
      },
      legalName: {
        active: true,
        language: "en",
        name: "Fisher Scientific GmbH",
        source: null,
        type: "legal",
      },
      description:
        "Fisher Scientific GmbH is a subsidiary of Thermo Fisher Scientific, a globally recognized leader in the provision of scientific equipment, consumables, and services for laboratories, research, and healthcare institutions. Fisher Scientific GmbH, operating in Germany, is an integral part of this extensive network.The company offers a wide range of products and solutions that cater to the needs of scientific and research communities, including laboratory equipment, chemicals, reagents, consumables, and analytical instruments. These items are essential for conducting experiments, diagnostics, and research in various scientific fields, such as biology, chemistry, and healthcare.",
      numEmployees: {
        value: 0,
      },
      duns: "",
      regId: "",
      regAuthorityCode: "",
      ein: "",
      tin: "",
      vat: "",
      tinCountryCode: "",
      vatCountryCode: "",
      revenue: {
        money: {
          amount: 0,
          currency: "USD",
        },
      },
      address: {
        email: [],
        fax: [],
        phone: [],
        address: [
          {
            alpha2CountryCode: "DE",
            city: "Unna",
            language: "",
            line1: "Im Heiligen Feld 17",
            line2: "",
            line3: "",
            postal: "",
            province: "DE-NW",
            streetNumber: "",
            unitNumber: "",
          },
        ],
      },
      addresses: [],
      website: "https://www.thermofisher.com/",
      shortDescription: "",
      vendorId: "365271035872756481",
      industryCode: "",
      vendorRecordRefs: [
        {
          id: "365271034991952676",
          vendorId: "8568903",
          enabled: true,
          paymentTerm: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          name: "",
          additionalCompanyEntities: [],
          companyEntityRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          currencies: [],
          enabledSystems: [],
        },
      ],
      supplierStatus: "",
      supplierSegmentation: "",
      supplierDimensions: [],
      segmentationDetails: [
        {
          id: "365447585356605906",
          name: "",
          dimension: {
            programs: [],
            regions: [],
            categories: [
              {
                id: "19-1911-191112-19111214-19111214306",
                name: "Small Laboratory Equipment (32010000)",
                erpId: "32010000",
                refId: null,
                version: "",
              },
              {
                id: "TC0-C40-C42-32010000",
                name: "Small Laboratory Equipment",
                erpId: "32010000",
                refId: null,
                version: "",
              },
            ],
            products: [],
            productStages: [],
            sites: [],
            departments: [],
            companyEntities: [],
          },
          segmentation: "preferred",
          description: "",
          latestUse: null,
        },
        {
          id: "365825147498571898",
          name: "",
          dimension: {
            programs: [],
            regions: [],
            categories: [
              {
                id: "TC0-C40",
                name: "Laboratory Supplies",
                erpId: "C40",
                refId: null,
                version: "",
              },
            ],
            products: [],
            productStages: [],
            sites: [],
            departments: [],
            companyEntities: [],
          },
          segmentation: "preferred",
          description: "",
          latestUse: null,
        },
      ],
      highlighters: {
        vendorId: "",
        legalName: "",
        commonName: "",
        aliases: "",
      },
      individual: false,
      activeErpRecord: true,
      engagementReferences: [],
      parentName: "",
      ultimateParentName: "",
      parentRef: {
        id: "311288916007494090",
        name: "Thermo Fisher Scientific",
        erpId: "",
        refId: null,
        version: "",
      },
      ultimateParentRef: {
        id: "311288916007494090",
        name: "Thermo Fisher Scientific",
        erpId: "",
        refId: null,
        version: "",
      },
      parentVendorRef: {
        id: "",
        name: "",
        erpId: "",
        refId: null,
        version: "",
      },
      otherIds: [],
      activationStatus: "",
    },
    nda: null,
    msa: null,
    msaInFile: false,
    ndaInFile: false,
    selectedVendorRecord: null,
    vendorRecords: [],
    activationStatus: "newSupplier",
    potentialMatches: null,
    potentialMatchIgnore: null,
    segmentationDetails: [
      {
        id: "365447585356605906",
        name: "",
        dimension: {
          programs: [],
          regions: [],
          categories: [
            {
              id: "19-1911-191112-19111214-19111214306",
              name: "Small Laboratory Equipment (32010000)",
              erpId: "32010000",
              refId: null,
              version: "",
            },
            {
              id: "TC0-C40-C42-32010000",
              name: "Small Laboratory Equipment",
              erpId: "32010000",
              refId: null,
              version: "",
            },
          ],
          products: [],
          productStages: [],
          sites: [],
          departments: [],
          companyEntities: [],
        },
        segmentation: "preferred",
        description: "",
        latestUse: null,
      },
      {
        id: "365825147498571898",
        name: "",
        dimension: {
          programs: [],
          regions: [],
          categories: [
            {
              id: "TC0-C40",
              name: "Laboratory Supplies",
              erpId: "C40",
              refId: null,
              version: "",
            },
          ],
          products: [],
          productStages: [],
          sites: [],
          departments: [],
          companyEntities: [],
        },
        segmentation: "preferred",
        description: "",
        latestUse: null,
      },
    ],
  },
  {
    supplierName: "RS Components GmbH",
    address: {
      alpha2CountryCode: "DE",
      city: "Frankfurt am Main",
      language: "",
      line1: "Mainzer Landstraße 180. 60327",
      line2: "",
      line3: "",
      postal: "",
      province: "DE-HE",
      streetNumber: "",
      unitNumber: "",
    },
    email: "",
    phoneNumber: "",
    website: "https://de.rs-online.com/",
    duns: "",
    vendorId: "364869532641937109",
    legalEntity: {
      active: true,
      forbesGlobal: false,
      fortune500: false,
      legalEntityName: "RS Components GmbH",
      id: "364844656561556357",
      numSubsidiaries: 0,
      otherNames: [],
      name: {
        active: false,
        language: null,
        name: null,
        source: null,
        type: null,
      },
      parent: false,
      ultimateParent: false,
      logo: {
        metadata: [
          {
            path: "oro/images/large/364844656561556357.jpg",
            height: 0,
            width: 0,
          },
        ],
      },
      commonName: {
        active: true,
        language: "en",
        name: "RS Components GmbH",
        source: null,
        type: "trading_or_operating",
      },
      legalName: {
        active: true,
        language: "en",
        name: "RS Components GmbH",
        source: null,
        type: "legal",
      },
      description:
        "RS Components GmbH is a prominent distributor of electronic, electrical, and industrial components, serving a diverse range of industries. With a strong presence in Europe and beyond, RS Components GmbH offers an extensive catalog of products, including semiconductors, connectors, automation and control components, and maintenance, repair, and operations (MRO) supplies. They provide essential solutions to engineers, maintenance professionals, and procurement specialists, facilitating access to a vast array of high-quality components and equipment. RS Components GmbH is renowned for its commitment to innovation, sustainability, and customer support, making them a trusted partner for businesses and individuals seeking reliable solutions for their technical needs.",
      numEmployees: {
        value: 0,
      },
      duns: "",
      regId: "",
      regAuthorityCode: "",
      ein: "",
      tin: "",
      vat: "",
      tinCountryCode: "",
      vatCountryCode: "",
      revenue: {
        money: {
          amount: 0,
          currency: "USD",
        },
      },
      address: {
        email: [],
        fax: [],
        phone: [],
        address: [
          {
            alpha2CountryCode: "DE",
            city: "Frankfurt am Main",
            language: "",
            line1: "Mainzer Landstraße 180. 60327",
            line2: "",
            line3: "",
            postal: "",
            province: "DE-HE",
            streetNumber: "",
            unitNumber: "",
          },
        ],
      },
      addresses: [],
      website: "https://de.rs-online.com/",
      shortDescription: "",
      vendorId: "364869532641937109",
      industryCode: "1417",
      vendorRecordRefs: [
        {
          id: "364869532415444693",
          vendorId: "0004883480",
          enabled: false,
          paymentTerm: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          name: "",
          additionalCompanyEntities: [],
          companyEntityRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          currencies: [],
          enabledSystems: [],
        },
        {
          id: "365271034991952662",
          vendorId: "4883480",
          enabled: false,
          paymentTerm: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          name: "",
          additionalCompanyEntities: [],
          companyEntityRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          currencies: [],
          enabledSystems: [],
        },
      ],
      supplierStatus: "",
      supplierSegmentation: "",
      supplierDimensions: [],
      segmentationDetails: [
        {
          id: "365113134408195743",
          name: "",
          dimension: {
            programs: [],
            regions: [],
            categories: [
              {
                id: "20-2015-201510",
                name: "Electrical Equipment",
                erpId: "201510",
                refId: null,
                version: "",
              },
            ],
            products: [],
            productStages: [],
            sites: [],
            departments: [],
            companyEntities: [],
          },
          segmentation: "preferred",
          description: "",
          latestUse: null,
        },
      ],
      highlighters: {
        vendorId: "",
        legalName: "",
        commonName: "",
        aliases: "",
      },
      individual: false,
      activeErpRecord: true,
      engagementReferences: [],
      parentName: "",
      ultimateParentName: "",
      parentRef: {
        id: "342466094392938712",
        name: "RS Group plc",
        erpId: "",
        refId: null,
        version: "",
      },
      ultimateParentRef: {
        id: "342466094392938712",
        name: "RS Group plc",
        erpId: "",
        refId: null,
        version: "",
      },
      parentVendorRef: {
        id: "",
        name: "",
        erpId: "",
        refId: null,
        version: "",
      },
      otherIds: [],
      activationStatus: "",
    },
    nda: null,
    msa: null,
    msaInFile: false,
    ndaInFile: false,
    selectedVendorRecord: null,
    vendorRecords: [],
    activationStatus: "newSupplier",
    potentialMatches: null,
    potentialMatchIgnore: null,
    segmentationDetails: [
      {
        id: "365113134408195743",
        name: "",
        dimension: {
          programs: [],
          regions: [],
          categories: [
            {
              id: "20-2015-201510",
              name: "Electrical Equipment",
              erpId: "201510",
              refId: null,
              version: "",
            },
          ],
          products: [],
          productStages: [],
          sites: [],
          departments: [],
          companyEntities: [],
        },
        segmentation: "preferred",
        description: "",
        latestUse: null,
      },
    ],
  },
];

export default {
  title: "ORO UI Toolkit/Form/Chat GPT Request Form",
  component: ChatGPTChatBotForm,
};

export const TemplateForm = {
  args: {
    fields: [
      {
        fieldName: "categories",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Categories",
        type: "idref",
        __typename: "FormField",
      },
      {
        fieldName: "intents",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "User intents",
        type: "idref",
        __typename: "FormField",
      },
      {
        fieldName: "regions",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Regions",
        type: "idref",
        __typename: "FormField",
      },
      {
        fieldName: "departments",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Departments",
        type: "idref",
        __typename: "FormField",
      },
      {
        fieldName: "upperAmount",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Upper amount",
        __typename: "FormField",
      },
      {
        fieldName: "taxAmount",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Lower amount",
        __typename: "FormField",
      },
    ],
    formData: null,
    categoryOptions: mockCategory,
    regionOptions: mockOptionsRegion,
    currencyOptions: mockCurrencyOptions,
    signedInUserDetails: mockUser,
    defaultCurrency: DEFAULT_CURRENCY,
    searchQuery:
      "Buy 3D Printer for research purposes, creating medicines tailored to specifications.",
    submitLabel: "Submit",
    cancelLabel: "cancel",
    getAISuggestions: (query) => {
      return Promise.resolve(mockChatGPTResponse);
    },
    getNormalizedVendors: () => {
      return Promise.resolve(mockSuppliers);
    },
    onSubmit: () => {
      return Promise.resolve(mockData);
    },
  },
};
