import React from "react";
import { StoryFn } from "@storybook/react";

import {
  ActivationStatus,
  ClosePoForm,
  ClosePoFormData,
  ClosePoFormProps,
} from "./../../lib";
import { ItemType } from "../../lib/Types/common";
import { mockPos } from "../mocks/POs";
import { DEFAULT_CURRENCY } from "../../lib/util";

const formData: ClosePoFormData = {
  purchaseOrder: {
    activityName: "Freshdesk PO",
    poNumber: "PO-123",
    normalizedVendorRef: {
      id: "",
      vendorRecordId: "",
      name: "Freshworks, Inc.",
      countryCode: "US",
      legalEntityId: "",
      legalEntityLogo: { metadata: [] },
      contact: {
        fullName: "",
        email: "",
        role: "",
        phone: "",
      },
      activationStatus: ActivationStatus.active,
    },
    companyEntityRef: { id: "", name: "Episerver Inc.", erpId: "" },
    start: "12-19-2022",
    end: "12-19-2022",
    cost: 12000,
    currencyCode: "EUR",
    itemList: {
      items: [
        {
          lineNumber: 231,
          erpItemId: { id: "1", name: "name", erpId: "1" },
          name: "Item 1",
          quantity: 4,
          description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          unitForQuantity: { id: "each", name: "each", erpId: "each" },
          price: { amount: 1000000, currency: DEFAULT_CURRENCY },
          totalPrice: { amount: 50000000, currency: DEFAULT_CURRENCY },
          startDate: "12-11-2023",
          endDate: "12-13-2023",
          type: ItemType.goods,
          accountCodeIdRef: { id: "1", name: "name", erpId: "1" },
          trackCode: [{ id: "101", name: "Book Club", erpId: "101" }],
        },
      ],
    },
    expenseItemList: {
      items: [
        {
          lineNumber: 313,
          erpItemId: { id: "1", name: "name", erpId: "1" },
          name: "Item 3",
          quantity: 3,
          description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          unitForQuantity: { id: "each", name: "each", erpId: "each" },
          price: { amount: 250, currency: DEFAULT_CURRENCY },
          totalPrice: { amount: 750, currency: DEFAULT_CURRENCY },
          startDate: "12-11-2023",
          endDate: "12-13-2023",
          type: ItemType.goods,
          accountCodeIdRef: { id: "1", name: "name", erpId: "1" },
          trackCode: [{ id: "101", name: "Book Club", erpId: "101" }],
        },
      ],
    },
  },
  poRef: {
    id: "325601482560307547",
    name: "ORDA4192",
    erpId: "Apple",
  },
};

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Form/ClosePO Form/Edit",
  component: ClosePoForm,
};

export const TemplateForm = {
  args: {
    formData,
    fields: [
      {
        fieldName: "reason",
        requirement: "required",
      },
      {
        fieldName: "poRef",
        requirement: "required",
      },
    ],
    getPO: () => Promise.resolve(mockPos),
    searchObjects: () =>
      Promise.resolve({
        total: 5,
        objs: [
          {
            poNumber: "ORDA4192",
            id: "325601482560307547",
            requestorName: "John Doe",
            requestorUsername: "john@foo.com",
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
            },
            departmentRef: null,
            accountRef: {
              id: "5122",
              name: "Miscellaneous Expense",
              erpId: "83",
              refId: "",
            },
            paymentTermsRef: null,
            memo: null,
            activityName: null,
            currencyCode: "USD",
            cost: 11,
            start: null,
            end: null,
            engagementRefs: [
              {
                id: "325594717986816347",
                name: null,
                erpId: null,
                refId: "A4192",
              },
            ],
            created: "2023-06-24T05:06:34.545783246Z",
            itemList: null,
            normalizedVendorRef: {
              id: "89113807414099968",
              vendorRecordId: null,
              name: "Apple",
              countryCode: "US",
              legalEntityId: "88868992675233957",
              legalEntityLogo: {
                metadata: [
                  {
                    path: "oro/images/small/88868992675233957.png",
                    height: 100,
                    width: 100,
                    __typename: "ImageMetadata",
                  },
                  {
                    path: "oro/images/large/88868992675233957.png",
                    height: 200,
                    width: 200,
                    __typename: "ImageMetadata",
                  },
                ],
                __typename: "Image",
              },
              selectedVendorRecord: {
                id: "91277523404455936",
                vendorId: "01234",
                enabled: false,
                paymentTerm: {
                  id: "",
                  name: "",
                  erpId: "",
                  refId: "",
                },
                __typename: "VendorRef",
              },
              contact: {
                fullName: "nitesh Jadhav",
                firstName: null,
                lastName: null,
                email: "nitesh@orolabs.ai",
                phone: "",
                role: "Account Manager",
                note: null,
                imageUrl: null,
                __typename: "Contact",
              },
              activationStatus: "active",
              isIndividual: false,
              __typename: "NormalizedVendorRef",
            },
            contractType: null,
            contract: null,
            noteObjects: [
              {
                id: "85bda098-a0ae-4f38-aafb-b740629630bf",
                owner: {
                  tenantId: "foo",
                  userName: "customeradmin+foo@orolabs.ai",
                  firstName: null,
                  lastName: null,
                  name: "Oro Admin",
                  department: null,
                  __typename: "UserId",
                },
                taskStatus: null,
                comment: "can you see this?",
                documents: null,
                created: "2023-06-27T16:57:16.395348168Z",
                updated: "2023-06-27T16:57:16.395347864Z",
                __typename: "Note",
              },
            ],
            status: null,
            erpCreatedDate: null,
            erpUpdatedDate: null,
            expenseItemList: {
              items: [
                {
                  name: null,
                  description: null,
                  categories: [
                    {
                      id: "tax",
                      name: "Tax",
                      erpId: null,
                      refId: null,
                    },
                  ],
                  departments: [],
                  type: "service",
                  materialId: null,
                  quantity: null,
                  unitForQuantity: null,
                  lineNumber: null,
                  priceMoney: null,
                  supplierPartId: null,
                  manufacturerPartId: null,
                  accountCodeIdRef: null,
                  url: null,
                  erpItemId: null,
                  startDate: null,
                  endDate: null,
                  tax: {
                    amountObject: null,
                    items: [
                      {
                        taxCode: {
                          id: "vat",
                          name: "VAT",
                          erpId: null,
                          refId: null,
                        },
                        percentage: 18,
                        taxableAmountObject: {
                          currency: "EUR",
                          amount: 1000,
                          __typename: "MoneyObject",
                        },
                        amountObject: {
                          currency: "EUR",
                          amount: 180,
                          __typename: "MoneyObject",
                        },
                        __typename: "TaxItem",
                      },
                    ],
                    __typename: "Tax",
                  },
                  accumulator: null,
                  itemIds: null,
                  lineOfBusiness: null,
                  trackCode: null,
                  location: null,
                  projectCode: null,
                  expenseCategory: null,
                  dataJson: null,
                  __typename: "Item",
                },
              ],
              __typename: "ItemList",
            },
            __typename: "PurchaseOrder",
          },
          {
            poNumber: "ORDA4178",
            id: "324955614791137001",
            requestorName: "John Doe",
            requestorUsername: "john@foo.com",
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
            },
            departmentRef: null,
            accountRef: {
              id: "6070",
              name: "Dues & Subscriptions",
              erpId: "74",
              refId: "",
            },
            paymentTermsRef: null,
            memo: null,
            activityName: null,
            currencyCode: "USD",
            cost: 300,
            start: null,
            end: null,
            engagementRefs: [
              {
                id: "324899524636957004",
                name: null,
                erpId: null,
                refId: "A4178",
              },
            ],
            created: "2023-06-22T10:20:07.669771290Z",
            itemList: null,
            normalizedVendorRef: {
              id: "89113807414099968",
              vendorRecordId: null,
              name: "Apple",
              countryCode: "US",
              legalEntityId: "88868992675233957",
              legalEntityLogo: {
                metadata: [
                  {
                    path: "oro/images/small/88868992675233957.png",
                    height: 100,
                    width: 100,
                    __typename: "ImageMetadata",
                  },
                  {
                    path: "oro/images/large/88868992675233957.png",
                    height: 200,
                    width: 200,
                    __typename: "ImageMetadata",
                  },
                ],
                __typename: "Image",
              },
              selectedVendorRecord: {
                id: "91277523404455936",
                vendorId: "01234",
                enabled: false,
                paymentTerm: {
                  id: "",
                  name: "",
                  erpId: "",
                  refId: "",
                },
                __typename: "VendorRef",
              },
              contact: {
                fullName: "nitesh Jadhav",
                firstName: null,
                lastName: null,
                email: "nitesh@orolabs.ai",
                phone: "",
                role: "Account Manager",
                note: null,
                imageUrl: null,
                __typename: "Contact",
              },
              activationStatus: "active",
              isIndividual: false,
              __typename: "NormalizedVendorRef",
            },
            contractType: null,
            contract: null,
            noteObjects: null,
            status: null,
            erpCreatedDate: null,
            erpUpdatedDate: null,
            expenseItemList: {
              items: [
                {
                  name: null,
                  description: null,
                  categories: [
                    {
                      id: "tax",
                      name: "Tax",
                      erpId: null,
                      refId: null,
                    },
                  ],
                  departments: [],
                  type: "service",
                  materialId: null,
                  quantity: null,
                  unitForQuantity: null,
                  lineNumber: null,
                  priceMoney: null,
                  supplierPartId: null,
                  manufacturerPartId: null,
                  accountCodeIdRef: null,
                  url: null,
                  erpItemId: null,
                  startDate: null,
                  endDate: null,
                  tax: {
                    amountObject: null,
                    items: [
                      {
                        taxCode: {
                          id: "vat",
                          name: "VAT",
                          erpId: null,
                          refId: null,
                        },
                        percentage: 18,
                        taxableAmountObject: {
                          currency: "EUR",
                          amount: 1000,
                          __typename: "MoneyObject",
                        },
                        amountObject: {
                          currency: "EUR",
                          amount: 180,
                          __typename: "MoneyObject",
                        },
                        __typename: "TaxItem",
                      },
                    ],
                    __typename: "Tax",
                  },
                  accumulator: null,
                  itemIds: null,
                  lineOfBusiness: null,
                  trackCode: null,
                  location: null,
                  projectCode: null,
                  expenseCategory: null,
                  dataJson: null,
                  __typename: "Item",
                },
              ],
              __typename: "ItemList",
            },
            __typename: "PurchaseOrder",
          },
          {
            poNumber: "ORDA4172",
            id: "324602784449443883",
            requestorName: "John Doe",
            requestorUsername: "john@foo.com",
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
            },
            departmentRef: null,
            accountRef: {
              id: "6055",
              name: "Miscellaneous Expense",
              erpId: "83",
              refId: "",
            },
            paymentTermsRef: null,
            memo: null,
            activityName: null,
            currencyCode: "USD",
            cost: 75,
            start: null,
            end: null,
            engagementRefs: [
              {
                id: "324601327444703275",
                name: null,
                erpId: null,
                refId: "A4172",
              },
            ],
            created: "2023-06-21T10:58:06.360326620Z",
            itemList: null,
            normalizedVendorRef: {
              id: "89113807414099968",
              vendorRecordId: null,
              name: "Apple",
              countryCode: "US",
              legalEntityId: "88868992675233957",
              legalEntityLogo: {
                metadata: [
                  {
                    path: "oro/images/small/88868992675233957.png",
                    height: 100,
                    width: 100,
                    __typename: "ImageMetadata",
                  },
                  {
                    path: "oro/images/large/88868992675233957.png",
                    height: 200,
                    width: 200,
                    __typename: "ImageMetadata",
                  },
                ],
                __typename: "Image",
              },
              selectedVendorRecord: {
                id: "91277523404455936",
                vendorId: "01234",
                enabled: false,
                paymentTerm: {
                  id: "",
                  name: "",
                  erpId: "",
                  refId: null,
                },
                __typename: "VendorRef",
              },
              contact: null,
              activationStatus: "active",
              isIndividual: false,
              __typename: "NormalizedVendorRef",
            },
            contractType: null,
            contract: null,
            noteObjects: null,
            status: null,
            erpCreatedDate: null,
            erpUpdatedDate: null,
            expenseItemList: {
              items: [
                {
                  name: null,
                  description: null,
                  categories: [
                    {
                      id: "tax",
                      name: "Tax",
                      erpId: null,
                      refId: null,
                    },
                  ],
                  departments: [],
                  type: "service",
                  materialId: null,
                  quantity: null,
                  unitForQuantity: null,
                  lineNumber: null,
                  priceMoney: null,
                  supplierPartId: null,
                  manufacturerPartId: null,
                  accountCodeIdRef: null,
                  url: null,
                  erpItemId: null,
                  startDate: null,
                  endDate: null,
                  tax: {
                    amountObject: null,
                    items: [
                      {
                        taxCode: {
                          id: "vat",
                          name: "VAT",
                          erpId: null,
                          refId: null,
                        },
                        percentage: 18,
                        taxableAmountObject: {
                          currency: "EUR",
                          amount: 1000,
                          __typename: "MoneyObject",
                        },
                        amountObject: {
                          currency: "EUR",
                          amount: 180,
                          __typename: "MoneyObject",
                        },
                        __typename: "TaxItem",
                      },
                    ],
                    __typename: "Tax",
                  },
                  accumulator: null,
                  itemIds: null,
                  lineOfBusiness: null,
                  trackCode: null,
                  location: null,
                  projectCode: null,
                  expenseCategory: null,
                  dataJson: null,
                  __typename: "Item",
                },
              ],
              __typename: "ItemList",
            },
            __typename: "PurchaseOrder",
          },
          {
            poNumber: "ORDA4170",
            id: "324556959860380231",
            requestorName: "John Doe",
            requestorUsername: "john@foo.com",
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
            },
            departmentRef: null,
            accountRef: {
              id: "6050",
              name: "1421 - Software - Cost",
              erpId: "72",
              refId: "",
            },
            paymentTermsRef: null,
            memo: null,
            activityName: null,
            currencyCode: "USD",
            cost: 25,
            start: null,
            end: null,
            engagementRefs: [
              {
                id: "324544731737898896",
                name: null,
                erpId: null,
                refId: "A4170",
              },
            ],
            created: "2023-06-21T07:56:00.927518062Z",
            itemList: null,
            normalizedVendorRef: {
              id: "89113807414099968",
              vendorRecordId: null,
              name: "Apple",
              countryCode: "US",
              legalEntityId: "88868992675233957",
              legalEntityLogo: {
                metadata: [
                  {
                    path: "oro/images/small/88868992675233957.png",
                    height: 100,
                    width: 100,
                    __typename: "ImageMetadata",
                  },
                  {
                    path: "oro/images/large/88868992675233957.png",
                    height: 200,
                    width: 200,
                    __typename: "ImageMetadata",
                  },
                ],
                __typename: "Image",
              },
              selectedVendorRecord: {
                id: "91277523404455936",
                vendorId: "01234",
                enabled: false,
                paymentTerm: {
                  id: "",
                  name: "",
                  erpId: "",
                  refId: null,
                },
                __typename: "VendorRef",
              },
              contact: null,
              activationStatus: "active",
              isIndividual: false,
              __typename: "NormalizedVendorRef",
            },
            contractType: null,
            contract: null,
            noteObjects: null,
            status: null,
            erpCreatedDate: null,
            erpUpdatedDate: null,
            expenseItemList: {
              items: [
                {
                  name: null,
                  description: null,
                  categories: [
                    {
                      id: "tax",
                      name: "Tax",
                      erpId: null,
                      refId: null,
                    },
                  ],
                  departments: [],
                  type: "service",
                  materialId: null,
                  quantity: null,
                  unitForQuantity: null,
                  lineNumber: null,
                  priceMoney: null,
                  supplierPartId: null,
                  manufacturerPartId: null,
                  accountCodeIdRef: null,
                  url: null,
                  erpItemId: null,
                  startDate: null,
                  endDate: null,
                  tax: null,
                  accumulator: null,
                  itemIds: null,
                  lineOfBusiness: null,
                  trackCode: null,
                  location: null,
                  projectCode: null,
                  expenseCategory: null,
                  dataJson: null,
                  __typename: "Item",
                },
              ],
              __typename: "ItemList",
            },
            __typename: "PurchaseOrder",
          },
          {
            poNumber: "ORDA4166",
            id: "324541593566302791",
            requestorName: "John Doe",
            requestorUsername: "john@foo.com",
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
            },
            departmentRef: null,
            accountRef: null,
            paymentTermsRef: null,
            memo: null,
            activityName: null,
            currencyCode: "USD",
            cost: 15,
            start: null,
            end: null,
            engagementRefs: [
              {
                id: "324483039467656182",
                name: null,
                erpId: null,
                refId: "A4166",
              },
            ],
            created: "2023-06-21T06:54:57.317700562Z",
            itemList: null,
            normalizedVendorRef: {
              id: "89113807414099968",
              vendorRecordId: null,
              name: "Apple",
              countryCode: "US",
              legalEntityId: "88868992675233957",
              legalEntityLogo: {
                metadata: [
                  {
                    path: "oro/images/small/88868992675233957.png",
                    height: 100,
                    width: 100,
                    __typename: "ImageMetadata",
                  },
                  {
                    path: "oro/images/large/88868992675233957.png",
                    height: 200,
                    width: 200,
                    __typename: "ImageMetadata",
                  },
                ],
                __typename: "Image",
              },
              selectedVendorRecord: {
                id: "91277523404455936",
                vendorId: "01234",
                enabled: false,
                paymentTerm: {
                  id: "",
                  name: "",
                  erpId: "",
                  refId: "",
                },
                __typename: "VendorRef",
              },
              contact: {
                fullName: "nitesh Jadhav",
                firstName: null,
                lastName: null,
                email: "nitesh@orolabs.ai",
                phone: "",
                role: "Account Manager",
                note: null,
                imageUrl: null,
                __typename: "Contact",
              },
              activationStatus: "active",
              isIndividual: false,
              __typename: "NormalizedVendorRef",
            },
            contractType: null,
            contract: null,
            noteObjects: null,
            status: null,
            erpCreatedDate: null,
            erpUpdatedDate: null,
            expenseItemList: {
              items: [
                {
                  name: null,
                  description: null,
                  categories: [
                    {
                      id: "tax",
                      name: "Tax",
                      erpId: null,
                      refId: null,
                    },
                  ],
                  departments: [],
                  type: "service",
                  materialId: null,
                  quantity: null,
                  unitForQuantity: null,
                  lineNumber: null,
                  priceMoney: null,
                  supplierPartId: null,
                  manufacturerPartId: null,
                  accountCodeIdRef: null,
                  url: null,
                  erpItemId: null,
                  startDate: null,
                  endDate: null,
                  tax: {
                    amountObject: null,
                    items: [
                      {
                        taxCode: {
                          id: "vat",
                          name: "VAT",
                          erpId: null,
                          refId: null,
                        },
                        percentage: 18,
                        taxableAmountObject: {
                          currency: "EUR",
                          amount: 1000,
                          __typename: "MoneyObject",
                        },
                        amountObject: {
                          currency: "EUR",
                          amount: 180,
                          __typename: "MoneyObject",
                        },
                        __typename: "TaxItem",
                      },
                    ],
                    __typename: "Tax",
                  },
                  accumulator: null,
                  itemIds: null,
                  lineOfBusiness: null,
                  trackCode: null,
                  location: null,
                  projectCode: null,
                  expenseCategory: null,
                  dataJson: null,
                  __typename: "Item",
                },
              ],
              __typename: "ItemList",
            },
            __typename: "PurchaseOrder",
          },
        ],
      }),
  },
};
