import React from "react";
import { StoryFn } from "@storybook/react";

import {
  CompanyInfoFormV2,
  CompanyInfoV2FormData,
  CompanyInfoV2FormProps,
} from "./../../lib";
import {
  mockCountryOptions,
  mockOptionsDefault,
} from "../MultiLevelSelect/mocks";
import { mockCsvFile } from "../mocks/file.mock";
import { getI18NInstance } from "./../../lib/i18n";

const foreignTaxClassificationOptions = [
  {
    tenantId: null,
    id: "null__null__null__foreignCompany",
    code: "foreignCompany",
    type: null,
    app: null,
    name: "Foreign company",
    displayName: "Foreign company",
    codePath: null,
    path: "foreignCompany",
    level: 1,
    active: false,
    parentCode: null,
    desc: null,
    image: null,
    preferred: false,
    children: null,
    owner: null,
    other: null,
    recommended: false,
    order: null,
    lc: null,
  },
  {
    tenantId: null,
    id: "null__null__null__foreignPartnership",
    code: "foreignPartnership",
    type: null,
    app: null,
    name: "Foreign partnership, simple trust or a grantor trust (and not claiming treaty benefits)or if your company is acting as an intermediary",
    displayName:
      "Foreign partnership, simple trust or a grantor trust (and not claiming treaty benefits)or if your company is acting as an intermediary",
    codePath: null,
    path: "foreignPartnership",
    level: 1,
    active: false,
    parentCode: null,
    desc: null,
    image: null,
    preferred: false,
    children: null,
    owner: null,
    other: null,
    recommended: false,
    order: null,
    lc: null,
  },
];

const taxKeys = [
  {
    code: "vies",
    name: "VAT Registration Number",
    description: null,
  },
  {
    code: "tin",
    name: "Income tax id",
    description: null,
  },
  {
    code: "utr",
    name: "Unique Taxpayer Reference Number",
    description:
      "UTR Number is issued by HMRC and used for filing taxes. (10 Digits) ",
  },
  {
    code: "ecn",
    name: "Vietnam Enterprise ID or ECN Code Number",
    description: null,
  },
  {
    code: "PAN",
    name: "Permanent Account Number",
    description: null,
  },
  {
    code: "ABN",
    name: "Australian Business Number",
    description: null,
  },
  {
    code: "gst_hst",
    name: "Federal Business Number",
    description:
      "9 digit Identification number issued by Canada Revenue Agency and used for filing business taxes",
  },
  {
    code: "ein",
    name: "US Tax Identification/ EIN Number",
    description:
      "Enter the EIN number for your company’s federal tax filing with IRS",
  },
  {
    code: "uen",
    name: "Unique Entity Number",
    description:
      "Identification number issued by government agency (e.g. ACRA, ROS)",
  },
];

const taxFormKeys = [
  {
    code: "w_8bene",
    name: "VAT Registration Number",
    description:
      "Non-US business entities that have US-sourced income are required to complete a W-8BEN-E form.",
    linkText:
      "You can find the W-8BENE Tax form and the instructions on the IRS website.",
    link: "https://www.irs.gov/forms-pubs/about-form-w-8-ben-e",
  },
  {
    code: "w_8imy",
    name: "Income tax id",
    description:
      "Non-US business entities that are a foreign partnership, a foreign simple trust or a foreign grantor trust (and not claiming treaty benefits) or the payee is an individual acting as Intermediary are required to complete the W-8IMY form.",
    linkText:
      "You can find the W-8IMY Tax form and instructions on the IRS website.",
    link: "https://www.irs.gov/forms-pubs/about-form-w-8-imy",
  },
  {
    code: "w_9",
    name: "Unique Taxpayer Reference Number",
    description: null,
    linkText: "You can find the IRS W-9 Tax form here",
    link: "https://www.irs.gov/pub/irs-pdf/fw9.pdf",
  },
  {
    code: "certificateIncorporation",
    name: "Certificate of incorporation",
    description: null,
    linkText: null,
    link: null,
  },
];

const formData = {
  companyEntityCountryCode: "US",
  encryptedExemptionTaxCode: {
    version: "",
    data: "",
    iv: "",
    unencryptedValue: null,
    restrainDecryptData: false,
    unmaskSize: 2,
    maskedValue: "",
    setBy: null,
  },
  indirectTaxCodeError: false,
  exemptionTaxCodeError: false,
  companyName: "Microsoft Corporation",
  exemptionTaxCodeValidationTimeout: false,
  useCompanyName: true,
  taxFormKey: null,
  reincarnationId: null,
  usCompanyEntityType: {
    id: "c_corporation",
    name: "C-Corporation",
    erpId: "",
  },
  encryptedIndirectTaxCode: {
    version: "",
    data: "",
    iv: "",
    unencryptedValue: null,
    restrainDecryptData: false,
    unmaskSize: 2,
    maskedValue: "",
    setBy: null,
  },
  legalName: "Microsoft Corporation",
  specialTaxStatus: true,
  exemptionTaxKeysList: ["usein", "other"],
  encryptedTaxCode: {
    version: "",
    data: "",
    iv: "",
    unencryptedValue: null,
    restrainDecryptData: false,
    unmaskSize: 2,
    maskedValue: "",
    setBy: null,
  },
  taxFormKeysList: ["w_9"],
  indirectTaxKey: null,
  taxCodeError: false,
  taxForm: null,
  taxAddress: {
    line1: "1 Microsoft Way",
    line2: "",
    line3: "",
    streetNumber: "",
    unitNumber: "",
    city: "Redmond",
    province: "US-WA",
    alpha2CountryCode: "US",
    postal: "98052",
    language: "",
  },
  indirectTaxKeysList: [],
  specialTaxNote: null,
  email: null,
  useCompanyAddress: true,
  tax1099: null,
  taxCodeValidationTimeout: false,
  website: "microsoft.com",
  duns: "12-045-3672",
  address: {
    line1: "1 Microsoft Way",
    line2: "",
    line3: "",
    streetNumber: "",
    unitNumber: "",
    city: "Redmond",
    province: "US-WA",
    alpha2CountryCode: "US",
    postal: "98052",
    language: "",
  },
  edited: false,
  specialTaxAttachment: null,
  exemptionTaxKey: "xyz",
  tax1099Required: true,
  usTaxDeclarationForm: null,
  foreignTaxClassification: null,
  foreignTaxFormKey: "abc",
  taxKey: null,
  taxKeysList: ["usein", "other"],
  registryQuestion: "This is a registry question being passed by caller?",
  phone: null,
  previousVersion: null,
  indirectTaxCodeValidationTimeout: false,
  paymentContactEmail: null,
  usTaxDeclarationFormKey: "w_8bene",
  primary: {
    primary: true,
    emailVerified: false,
    phoneVerified: false,
  },
};

export default {
  title: "ORO UI Toolkit/Form/CompanyInfoV2 Form",
  component: CompanyInfoFormV2,
};

getI18NInstance(true);

export const TemplateForm = {
  args: {
    fields: [
      {
        fieldName: "companyName",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Company name",
        __typename: "FormField",
      },
      {
        booleanValue: true,
        customLabel: "",
        fieldName: "excludeAddressSuggestion",
        intValue: null,
        itemConfig: null,
        questionnaireId: null,
        requirement: "optional",
        stringValue: "",
        title: "Exclude address suggestion",
      },
      {
        fieldName: "email",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Email",
        __typename: "FormField",
      },
      {
        fieldName: "phone",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Phone",
        __typename: "FormField",
      },
      {
        fieldName: "legalName",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Legal name",
        __typename: "FormField",
      },
      {
        fieldName: "website",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "website",
        __typename: "FormField",
      },
      {
        fieldName: "duns",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "DUNS number",
        __typename: "FormField",
      },
      {
        fieldName: "address",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Address",
        __typename: "FormField",
      },
      {
        fieldName: "primary",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Primary contact",
        __typename: "FormField",
      },
      {
        fieldName: "paymentContactEmail",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Payment contacty email",
        __typename: "FormField",
      },
      {
        fieldName: "taxAddress",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Tax address",
        __typename: "FormField",
      },
      {
        fieldName: "usCompanyEntityType",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Company type",
        __typename: "FormField",
      },
      {
        fieldName: "taxKey",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Tax key",
        __typename: "FormField",
      },
      {
        fieldName: "encryptedTaxCode",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Tax id",
        __typename: "FormField",
      },
      {
        fieldName: "indirectTaxKey",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Indirect Tax key",
        __typename: "FormField",
      },
      {
        fieldName: "encryptedIndirectTaxCode",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Indirect Tax id",
        __typename: "FormField",
      },
      {
        fieldName: "taxFormKey",
        requirement: "optional",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Tax form type",
        __typename: "FormField",
      },
      {
        fieldName: "usTaxDeclarationFormKey",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "US Tax declaration form type",
        __typename: "FormField",
      },
      {
        fieldName: "foreignTaxClassification",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Foreign company type",
        __typename: "FormField",
      },
      {
        fieldName: "specialTaxStatus",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Special tax status",
        __typename: "FormField",
      },
      {
        fieldName: "specialTaxNote",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Special tax note",
        __typename: "FormField",
      },
      {
        fieldName: "exemptionTaxKey",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Exemption Tax key",
        __typename: "FormField",
      },
      {
        fieldName: "encryptedExemptionTaxCode",
        requirement: "required",
        booleanValue: null,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Exemption Tax id",
        __typename: "FormField",
      },
    ],
    formData,
    countryOptions: mockCountryOptions,
    usCompanyEntityTypeOptions: mockOptionsDefault,
    usForeignTaxClassificationOptions: foreignTaxClassificationOptions,
    taxKeys: taxKeys,
    taxFormKeys: taxFormKeys,
    submitLabel: "Submit",
    cancelLabel: "cancel",
    onReady: () => {},
    loadDocument: () => Promise.resolve(mockCsvFile),
  },
};
