import React from "react";
import { StoryFn } from "@storybook/react";

import { CompanyInfoV3FormData, CompanyInfoV3FormReadOnly } from "../../lib";
import { mockCsvFile } from "../mocks/file.mock";
import { getI18NInstance } from "../../lib/i18n";

const foreignTaxClassificationOptions = [
  {
    tenantId: null,
    id: "null__null__null__foreignCompany",
    code: "foreignCompany",
    type: null,
    app: null,
    name: "Foreign company",
    displayName: "Foreign company",
    codePath: null,
    path: "foreignCompany",
    level: 1,
    active: false,
    parentCode: null,
    desc: null,
    image: null,
    preferred: false,
    children: null,
    owner: null,
    other: null,
    recommended: false,
    order: null,
    lc: null,
  },
  {
    tenantId: null,
    id: "null__null__null__foreignPartnership",
    code: "foreignPartnership",
    type: null,
    app: null,
    name: "Foreign partnership, simple trust or a grantor trust (and not claiming treaty benefits)or if your company is acting as an intermediary",
    displayName:
      "Foreign partnership, simple trust or a grantor trust (and not claiming treaty benefits)or if your company is acting as an intermediary",
    codePath: null,
    path: "foreignPartnership",
    level: 1,
    active: false,
    parentCode: null,
    desc: null,
    image: null,
    preferred: false,
    children: null,
    owner: null,
    other: null,
    recommended: false,
    order: null,
    lc: null,
  },
];

const taxKeys = [
  {
    code: "vies",
    name: "VAT Registration Number",
    description: null,
  },
  {
    code: "tin",
    name: "Income tax id",
    description: null,
  },
  {
    code: "utr",
    name: "Unique Taxpayer Reference Number",
    description:
      "UTR Number is issued by HMRC and used for filing taxes. (10 Digits) ",
  },
  {
    code: "ecn",
    name: "Vietnam Enterprise ID or ECN Code Number",
    description: null,
  },
  {
    code: "PAN",
    name: "Permanent Account Number",
    description: null,
  },
  {
    code: "ABN",
    name: "Australian Business Number",
    description: null,
  },
  {
    code: "gst_hst",
    name: "Federal Business Number",
    description:
      "9 digit Identification number issued by Canada Revenue Agency and used for filing business taxes",
  },
  {
    code: "ein",
    name: "US Tax Identification/ EIN Number",
    description:
      "Enter the EIN number for your company’s federal tax filing with IRS",
  },
  {
    code: "uen",
    name: "Unique Entity Number",
    description:
      "Identification number issued by government agency (e.g. ACRA, ROS)",
  },
];

const taxFormKeys = [
  {
    code: "w_8bene",
    name: "VAT Registration Number",
    description:
      "Non-US business entities that have US-sourced income are required to complete a W-8BEN-E form.",
    linkText:
      "You can find the W-8BENE Tax form and the instructions on the IRS website.",
    link: "https://www.irs.gov/forms-pubs/about-form-w-8-ben-e",
  },
  {
    code: "w_8imy",
    name: "Income tax id",
    description:
      "Non-US business entities that are a foreign partnership, a foreign simple trust or a foreign grantor trust (and not claiming treaty benefits) or the payee is an individual acting as Intermediary are required to complete the W-8IMY form.",
    linkText:
      "You can find the W-8IMY Tax form and instructions on the IRS website.",
    link: "https://www.irs.gov/forms-pubs/about-form-w-8-imy",
  },
  {
    code: "w_9",
    name: "Unique Taxpayer Reference Number",
    description: null,
    linkText: "You can find the IRS W-9 Tax form here",
    link: "https://www.irs.gov/pub/irs-pdf/fw9.pdf",
  },
  {
    code: "certificateIncorporation",
    name: "Certificate of incorporation",
    description: null,
    linkText: null,
    link: null,
  },
];

const formData = {
  edited: false,
  reincarnationId: null,
  previousVersion: null,
  companyName: "Applee",
  email: "nitesh@orolabs.ai",
  phone: "+917020857979",
  fax: "150483782",
  useCompanyName: false,
  legalName: "Applee",
  website: "a@c.com",
  address: {
    line1: "Railway station, Agarkar Nagar",
    line2: "",
    line3: "",
    streetNumber: "",
    unitNumber: "",
    city: "Pune",
    province: "IN-MH",
    alpha2CountryCode: "IN",
    postal: "411001",
    language: "",
  },
  duns: "150483782",
  primary: {
    fullName: "nitesh Jadhav",
    email: "nitesh@orolabs.ai",
    role: "Account Manager",
    phone: "",
    requireBackgroundCheck: false,
    primary: false,
    emailVerified: false,
    phoneVerified: false,
  },
  paymentContactEmail: "",
  useCompanyAddress: false,
  taxAddress: {
    line1: "Railway station, Agarkar Nagar",
    line2: "",
    line3: "",
    streetNumber: "",
    unitNumber: "",
    city: "Pune",
    province: "IN-MH",
    alpha2CountryCode: "IN",
    postal: "411001",
    language: "",
  },
  companyEntityCountryCodes: ["US"],
  usCompanyEntityType: {
    id: "string",
    name: "string",
    erpId: "string",
  },
  tax: {
    taxKeysList: ["inpan", "other"],
    taxKey: "inpan",
    encryptedTaxCode: {
      version: "07a39728-2315-493a-9b18-eaee29618e3b",
      data: "7Bw6CFWfOnFLiVDLMUyc4g==",
      iv: "xwgngHFeXq7/4AglyHLJ6g==",
      unencryptedValue: "Avnpj7593Fj",
      restrainDecryptData: false,
      unmaskSize: 4,
      maskedValue: "********93Fj",
      setBy: null,
    },
    taxCodeError: false,
    taxCodeValidationTimeout: false,
  },
  indirectTax: {
    taxKeysList: ["ingstin"],
    taxKey: "ingstin",
    encryptedTaxCode: {
      version: "07a39728-2315-493a-9b18-eaee29618e3b",
      data: "u3EOtfPZyOKlQgWSftcsPA==",
      iv: "mXE+to/K9lrsQ+YihGaozg==",
      unencryptedValue: "Avnpj7593f",
      restrainDecryptData: false,
      unmaskSize: 4,
      maskedValue: "********593f",
      setBy: null,
    },
    taxCodeError: false,
    taxCodeValidationTimeout: false,
  },
  taxForm: {
    ocrInfo: {
      companyInfo: {
        name: "asdasd",
        ein: "asdasd",
        companyEntityType: "asdasd",
        address: {
          line1: "Railway station, Agarkar Nagar",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Latur",
          province: "IN-MH",
          alpha2CountryCode: "IN",
          postal: "411001",
          language: "",
        },
      },
    },
    taxFormKeysList: ["pancard"],
    taxFormKey: "pancard",
    taxForm: {
      filename: "fw9.png",
      mediatype: "image/png",
      size: "0",
      path: "attachment/2023/9/11/354324010986668763/fw9.png",
      sourceUrl: "",
      reference: "",
      date: null,
      expiration: null,
      name: "",
      note: "",
      eid: null,
      asyncPutUrl: null,
      asyncGetUrl: null,
      created: null,
      issueDate: null,
      contentKind: "CustomerPrivate",
    },
  },
  indirectTaxForm: {
    taxFormKeysList: ["gst_certificate"],
    taxFormKey: "gst_certificate",
    taxForm: {
      filename: "image__4_.png",
      mediatype: "image/png",
      size: "0",
      path: "attachment/2023/9/11/354324162489123547/image__4_.png",
      sourceUrl: "",
      reference: "",
      date: null,
      expiration: null,
      name: "",
      note: "",
      eid: null,
      asyncPutUrl: null,
      asyncGetUrl: null,
      created: null,
      issueDate: null,
      contentKind: "CustomerPrivate",
    },
  },
  additionalDocsList: ["pancard", "msme"],
  additionalDocuments: [
    {
      taxFormKeysList: ["pancard"],
      taxFormKey: "pancard",
      taxForm: {
        filename: "fw9.png",
        mediatype: "image/png",
        size: "0",
        path: "attachment/2023/9/11/354324010986668763/fw9.png",
        sourceUrl: "",
        reference: "",
        date: null,
        expiration: null,
        name: "",
        note: "",
        eid: null,
        asyncPutUrl: null,
        asyncGetUrl: null,
        created: null,
        issueDate: null,
        contentKind: "CustomerPrivate",
      },
    },
  ],
  usTaxDeclarationFormKey: "w_8bene",
  usTaxDeclarationForm: {
    filename: "ORO-W9.png",
    mediatype: "image/png",
    size: "0",
    path: "attachment/2023/9/10/353966928350524101/ORO-W9.png",
    sourceUrl: "",
    reference: "",
    date: null,
    expiration: null,
    name: "",
    note: "",
    eid: null,
    asyncPutUrl: null,
    asyncGetUrl: null,
    created: null,
    issueDate: null,
    contentKind: "CustomerPrivate",
  },
  usTaxDeclarationFormOcrInfo: {
    companyInfo: {
      name: "asdasd",
      ein: "asdasd",
      companyEntityType: "asdasd",
      address: {
        line1: "Railway station, Agarkar Nagar",
        line2: "",
        line3: "",
        streetNumber: "",
        unitNumber: "",
        city: "Latur",
        province: "IN-MH",
        alpha2CountryCode: "IN",
        postal: "411001",
        language: "",
      },
    },
  },
  foreignTaxClassification: {
    id: "foreignCompany",
    name: "Foreign company",
    erpId: "",
    refId: "",
    empty: false,
  },
  tax1099: true,
  tax1099Required: true,
  specialTaxStatus: true,
  specialTaxNote: "notes",
  specialTaxAttachments: [
    {
      filename: "image__4_.png",
      mediatype: "image/png",
      size: "0",
      path: "attachment/2023/9/11/354324663519707867/image__4_.png",
      sourceUrl: "",
      reference: "",
      date: null,
      expiration: null,
      name: "",
      note: "",
      eid: null,
      asyncPutUrl: null,
      asyncGetUrl: null,
      created: null,
      issueDate: null,
      contentKind: "CustomerPrivate",
    },
    {
      filename: "Screenshot_2023-09-09_at_8.05.31_PM.png",
      mediatype: "image/png",
      size: "0",
      path: "attachment/2023/9/11/354324748215288539/Screenshot_2023-09-09_at_8.05.31_PM.png",
      sourceUrl: "",
      reference: "",
      date: null,
      expiration: null,
      name: "",
      note: "",
      eid: null,
      asyncPutUrl: null,
      asyncGetUrl: null,
      created: null,
      issueDate: null,
      contentKind: "CustomerPrivate",
    },
  ],
  multiLingualAddresses: null,
  instruction: "instruction",
};
const fields = [
  {
    __typename: "FormField",
    fieldName: "companyName",
    requirement: "required",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Company name",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "email",
    requirement: "required",
    booleanValue: null,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Email",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "phone",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Phone",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "fax",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Fax number",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "legalName",
    requirement: "required",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Legal name",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "website",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "website",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "address",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Address",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "duns",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "DUNS",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "primary",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Primary contact",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "paymentContactEmail",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Payment contact email",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "taxAddress",
    requirement: "required",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Tax address",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "usCompanyEntityType",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Company type",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "tax",
    requirement: "required",
    booleanValue: null,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Tax key",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "indirectTax",
    requirement: "required",
    booleanValue: null,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Indirect Tax key",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "taxForm",
    requirement: "required",
    booleanValue: null,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Tax form type",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "indirectTaxForm",
    requirement: "required",
    booleanValue: null,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Indirect Tax form type",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "additionalDocsList",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Supplier additional docs domestic supplier",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "usTaxDeclarationFormKey",
    requirement: "required",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "US Tax declaration form type",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "foreignTaxClassification",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Foreign company type",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "specialTaxStatus",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Special tax status",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "specialTaxNote",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Special tax note",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "multiLingualAddresses",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "International Name and Address",
    questionnaireId: null,
  },
  {
    __typename: "FormField",
    fieldName: "instruction",
    requirement: "optional",
    booleanValue: true,
    stringValue: null,
    intValue: null,
    itemConfig: null,
    title: "Instruction",
    questionnaireId: null,
  },
];
//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Form/Company info V3 Form Read Only",
  component: CompanyInfoV3FormReadOnly,
};
getI18NInstance(true);

export const TemplateForm = {
  args: {
    data: formData,
    taxKeys: taxKeys,
    taxFormKeys: taxFormKeys,
    isValidationSupported: true,
    isOcrEnabled: true,
    usCompanyEntityTypeOptions: foreignTaxClassificationOptions,
    loadDocument: () => Promise.resolve(mockCsvFile),
    fields: fields,
  },
};
