import React from "react";
import { StoryFn } from "@storybook/react";
import { ContractNegotiationForm } from "../../lib";
import { ContractFormProps } from "../../lib/Form/types";
import {
  mockCurrencyOptions,
  mockDocumentTypeOptions,
  mockMsaDocument,
  mockPaymentTerms,
  mockSlaDocumment,
} from "../MultiLevelSelect/mocks";
import {
  mockAnnualContractFields,
  mockAnnualSunscriptionContractFields,
  mockContractTypeFieldDefinition,
  mockContractTypeOptions,
  mockExistingContracts,
  mockFixedContractFields,
  mockFixedFields,
  mockMonthlyContractFields,
} from "../mocks/contractNegotiation";
import { DEFAULT_CURRENCY } from "../../lib/util";

export default {
  title: "ORO UI Toolkit/Form/Contract Negotiation Form",
  component: ContractNegotiationForm,
};

export const TemplateForm = {
  args: {
    formData: {
      revisions: [
        {
          proposalDescription: "Test Proposal",
          contractType: { id: "annual", name: "Annual", erpId: "" },
          duration: 1,
          fixedSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
          variableSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
          recurringSpend: { amount: 1200, currency: "GBP" },
          tenantRecurringSpend: { amount: 1455.12, currency: DEFAULT_CURRENCY },
          oneTimeCost: { amount: 1000, currency: DEFAULT_CURRENCY },
          totalValue: { amount: 1000, currency: "GBP" },
          tenantTotalValue: { amount: 1212.58, currency: DEFAULT_CURRENCY },
          negotiatedSavings: { amount: 500, currency: DEFAULT_CURRENCY },
          quantity: "2 users",
          billingCycle: "Annual",
          startDate: "2021-12-01",
          endDate: "2022-11-30",
          autoRenew: true,
          autoRenewNoticePeriod: 15,
          includesLateFees: true,
          lateFeeDays: 2,
          lateFeesPercentage: 5,
          terminationOfConvenience: true,
          terminationOfConvenienceDays: 2,
          liabilityLimitation: true,
          liabilityLimitationMultiplier: 3,
          liabilityLimitationCap: { amount: 10, currency: "GBP" },
          tenantLiabilityLimitationCap: {
            amount: 12.13,
            currency: DEFAULT_CURRENCY,
          },
          confidentialityClause: false,
          yearlySplits: [
            {
              year: 2021,
              totalValue: { amount: 10, currency: "GBP" },
              tenantTotalValue: { amount: 12.13, currency: DEFAULT_CURRENCY },
            },
            {
              year: 2022,
              totalValue: { amount: 12, currency: "GBP" },
              tenantTotalValue: { amount: 14.55, currency: DEFAULT_CURRENCY },
            },
          ],
        },
        {
          proposalDescription:
            "Second Proposal Second Proposal Second ProposalSecond Proposal",
          contractType: { id: "annual", name: "Annual", erpId: "" },
          duration: 22,
          fixedSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
          variableSpend: { amount: 2000, currency: DEFAULT_CURRENCY },
          recurringSpend: { amount: 3000, currency: DEFAULT_CURRENCY },
          oneTimeCost: { amount: 2000, currency: DEFAULT_CURRENCY },
          totalValue: { amount: 2000, currency: DEFAULT_CURRENCY },
          quantity: "4 users",
        },
      ],
      slaDocument: mockSlaDocumment,
      slaAttachment: mockSlaDocumment.attachment,
      msaDocument: mockMsaDocument,
      msaAttachment: mockMsaDocument.attachment,
      supplierName: "IBM",
      companyEntity: {
        displayName: "Honeycomb Mfg.",
        id: "HH-HM",
        path: "HH-HM",
      },
      savingsLink: "",
      relatedContracts: [
        { id: "C-278", name: "Figma", erpId: "" },
        { id: "C-279", name: "Apple", erpId: "" },
      ],
      businessOwners: [
        {
          tenantId: "",
          tenantName: null,
          userName: "johndoe@foo.ai",
          name: "John Doe",
          department: "",
          departmentCode: null,
          groupIds: null,
          type: null,
          email: null,
          phone: null,
          firstName: null,
          lastName: null,
          api: false,
          picture: null,
          ip: null,
          admin: false,
        },
        {
          tenantId: "",
          tenantName: null,
          userName: "jane@foo.ai",
          name: "Jane Doe",
          department: "",
          departmentCode: null,
          groupIds: null,
          type: null,
          email: null,
          phone: null,
          firstName: null,
          lastName: null,
          api: false,
          picture: null,
          ip: null,
          admin: false,
        },
      ],
    },
    fields: [
      {
        __typename: "FormField",
        fieldName: "allowDecimal",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Allow Decimal",
        questionnaireId: null,
      },
    ],
    submitLabel: "Submit",
    supplierName: "IBM",
    currencies: mockCurrencyOptions,
    paymentTermOptions: mockPaymentTerms,
    documentTypeOptions: mockDocumentTypeOptions,
    contractTypeOptions: mockContractTypeOptions,
    contractFields: mockAnnualContractFields,
    contractTypeDefinition: mockContractTypeFieldDefinition,
    existingContracts: mockExistingContracts,
    duration: 2,
    recurringSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
    variableSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
    oneTimeCost: { amount: 1000, currency: DEFAULT_CURRENCY },
    totalValue: { amount: 1000, currency: DEFAULT_CURRENCY },
    quantity: 2,
  },
};
