import React from "react";
import { StoryFn } from "@storybook/react";
import { ContractFinalisationForm, getI18NInstance } from "../../lib";
import { ContractFormProps } from "../../lib/Form/types";
import {
  mockCurrencyOptions,
  mockDocumentTypeOptions,
  mockMsaDocument,
  mockPaymentTerms,
  mockSlaDocumment,
} from "../MultiLevelSelect/mocks";
import {
  mockAnnualContractFields,
  mockContractTypeFieldDefinition,
  mockContractTypeOptions,
  mockExistingContracts,
  mockFixedContractFields,
  mockMonthlyContractFields,
} from "../mocks/contractNegotiation";
import { DEFAULT_CURRENCY } from "../../lib/util";

export default {
  title: "ORO UI Toolkit/Form/Contract Finalisation Form",
  component: ContractFinalisationForm,
};

getI18NInstance(true);

export const TemplateForm = {
  args: {
    formData: {
      // revisions: [],
      revisions: [
        {
          proposalDescription: "Test Proposal",
          duration: 6,
          contractType: { id: "annual", name: "Annual", erpId: "" },
          fixedSpend: { amount: 100, currency: DEFAULT_CURRENCY },
          variableSpend: { amount: 100, currency: DEFAULT_CURRENCY },
          recurringSpend: { amount: 200, currency: "GBP" },
          tenantRecurringSpend: { amount: 700, currency: DEFAULT_CURRENCY },
          oneTimeCost: { amount: 100, currency: DEFAULT_CURRENCY },
          totalValue: { amount: 100, currency: "GBP" },
          tenantTotalValue: { amount: 500, currency: DEFAULT_CURRENCY },
          negotiatedSavings: { amount: 50, currency: DEFAULT_CURRENCY },
          quantity: "2 users",
          billingCycle: "Annual",
          autoRenew: true,
        },
        {
          contractDescription: "Test Product",
          proposalDescription: "Second Proposal",
          contractType: { id: "annual", name: "Annual", erpId: "" },
          duration: 12,
          fixedSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
          variableSpend: { amount: 2000, currency: DEFAULT_CURRENCY },
          recurringSpend: { amount: 3000, currency: "GBP" },
          tenantRecurringSpend: { amount: 7000, currency: DEFAULT_CURRENCY },
          oneTimeCost: { amount: 2000, currency: DEFAULT_CURRENCY },
          totalValue: { amount: 3000, currency: DEFAULT_CURRENCY },
          tenantTotalValue: { amount: 8000, currency: "GBP" },
          negotiatedSavings: { amount: 300, currency: DEFAULT_CURRENCY },
          renewalAnnualValue: { amount: 2500, currency: DEFAULT_CURRENCY },
          quantity: "4 users",
          paymentTerms: { erpId: "1", id: "1", name: "Net 15" },
          autoRenew: true,
          autoRenewNoticePeriod: 3,
          includesPriceCap: false,
          priceCapIncrease: null,
          includesCancellation: false,
          cancellationDeadline: "",
          includesOptOut: true,
          optOutDeadline: "2022-01-31",
          billingCycle: "Annual",
          startDate: "2021-12-01",
          endDate: "2022-11-30",
        },
        {
          contractType: { id: "contractor", name: "Contractor", erpId: "" },
          duration: 12,
          recurringSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
          totalValue: { amount: 1500, currency: DEFAULT_CURRENCY },
        },
      ],
      supplierName: "IBM",
      companyEntity: {
        id: "HH-HM",
        displayName: "Honeycomb Mfg.",
        path: "HH-HM",
      },
      currency: {
        id: "id1",
        displayName: DEFAULT_CURRENCY,
        path: DEFAULT_CURRENCY,
      },
      savingsLink: "",
      relatedContracts: [
        { id: "C-278", name: "Figma", erpId: "" },
        { id: "C-279", name: "Apple", erpId: "" },
      ],
      businessOwners: [
        {
          tenantId: "",
          tenantName: null,
          userName: "johndoe@foo.ai",
          name: "John Doe",
          department: "",
          departmentCode: null,
          groupIds: null,
          type: null,
          email: null,
          phone: null,
          firstName: null,
          lastName: null,
          api: false,
          picture: null,
          ip: null,
          admin: false,
        },
        {
          tenantId: "",
          tenantName: null,
          userName: "jane@foo.ai",
          name: "Jane Doe",
          department: "",
          departmentCode: null,
          groupIds: null,
          type: null,
          email: null,
          phone: null,
          firstName: null,
          lastName: null,
          api: false,
          picture: null,
          ip: null,
          admin: false,
        },
      ],
      contractDescription: "Test Description",
      proposalDescription: "Second Proposal",
      contractType: { id: "annual", name: "Annual", erpId: "" },
      duration: 12,
      fixedSpend: { amount: 1000, currency: DEFAULT_CURRENCY },
      variableSpend: { amount: 2000, currency: DEFAULT_CURRENCY },
      recurringSpend: null, // {amount: 3000, currency: 'GBP'},
      tenantRecurringSpend: { amount: 7000, currency: DEFAULT_CURRENCY },
      oneTimeCost: { amount: 2000, currency: DEFAULT_CURRENCY },
      totalValue: null, // {amount: 3000, currency: 'GBP'},
      tenantTotalValue: { amount: 7000, currency: DEFAULT_CURRENCY },
      negotiatedSavings: { amount: 300, currency: DEFAULT_CURRENCY },
      renewalAnnualValue: { amount: 2500, currency: DEFAULT_CURRENCY },
      paymentTerms: null, // {id: "1", displayName: "Net 15", path: '1'},
      autoRenew: true,
      autoRenewNoticePeriod: 3,
      includesPriceCap: false,
      priceCapIncrease: null,
      includesCancellation: false,
      cancellationDeadline: "",
      includesOptOut: true,
      optOutDeadline: "2023-01-31",
      billingCycle: "Annual",
      startDate: null, // '2021-12-01',
      endDate: null,
      yearlySplits: [
        { year: 2021, annualSpend: { amount: 10, currency: DEFAULT_CURRENCY } },
        { year: 2022, annualSpend: { amount: 12, currency: DEFAULT_CURRENCY } },
      ],
      selectedRevisionIndex: 2,
    },
    fields: [
      {
        __typename: "FormField",
        fieldName: "documentsRequired",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Documents required",
        questionnaireId: null,
      },
      {
        __typename: "FormField",
        fieldName: "basicInfoVisible",
        requirement: "optional",
        booleanValue: false,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Basic information visible",
        questionnaireId: null,
      },
      {
        __typename: "FormField",
        fieldName: "documentsVisible",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Documents visible",
        questionnaireId: null,
      },
      {
        __typename: "FormField",
        fieldName: "allowDecimal",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Allow Decimal",
        questionnaireId: null,
      },
    ],
    submitLabel: "Submit",
    supplierName: "IBM",
    currencies: mockCurrencyOptions,
    paymentTermOptions: mockPaymentTerms,
    documentTypeOptions: mockDocumentTypeOptions,
    contractTypeOptions: mockContractTypeOptions,
    contractFields: mockAnnualContractFields,
    existingContracts: mockExistingContracts,
    contractTypeDefinition: mockContractTypeFieldDefinition,
  },
};
