import React from "react";
import { StoryFn } from "@storybook/react";
import { ContractUpdateSummaryForm } from "../../lib";
import { ContractUpdateSummaryFormProps } from "../../lib/Form/types";

export default {
  title: "ORO UI Toolkit/Form/Contract Update Summary Form",
  component: ContractUpdateSummaryForm,
};

export const TemplateForm = {
  args: {
    formData: {
      supplier: {
        supplierName: "Testing One",
        contactName: "",
        contactNote: "",
        email: "",
        phoneNumber: "",
        vendorId: "271942947746054181",
        website: "",
        duns: "",
        legalEntity: {
          active: false,
          forbesGlobal: false,
          fortune500: false,
          legalEntityName: "",
          id: null,
          numSubsidiaries: 0,
          otherNames: [],
          name: {
            active: false,
            language: null,
            name: null,
            source: null,
            type: null,
          },
          parent: false,
          ultimateParent: false,
          logo: {
            metadata: [],
          },
          commonName: {
            active: false,
            language: null,
            name: null,
            source: null,
            type: null,
          },
          legalName: {
            active: false,
            language: null,
            name: null,
            source: null,
            type: null,
          },
          description: "",
          numEmployees: {
            value: 0,
          },
          duns: "",
          regId: "",
          regAuthorityCode: "",
          ein: "",
          tin: "",
          vat: "",
          tinCountryCode: "",
          vatCountryCode: "",
          revenue: {
            money: {
              amount: 0,
              currency: "USD",
            },
          },
          address: {
            email: [],
            fax: [],
            phone: [],
            address: [],
          },
          addresses: [],
          website: "",
          shortDescription: "",
          vendorId: "",
          industryCode: "",
          vendorRecordRefs: [],
          supplierStatus: "",
          supplierSegmentation: "",
          supplierDimensions: [],
          segmentationDetails: [],
          highlighters: {
            vendorId: "",
            legalName: "",
            commonName: "",
            aliases: "",
          },
          individual: false,
          activeErpRecord: false,
          engagementReferences: [],
          parentName: "",
          ultimateParentName: "",
          parentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          ultimateParentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          parentVendorRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          otherIds: [],
          activationStatus: "",
        },
        address: {
          alpha2CountryCode: "US",
          city: "San Francisco",
          language: "",
          line1: "480 Sutter St, Union Square",
          line2: "",
          line3: "",
          postal: "94108",
          province: "US-CA",
          streetNumber: "480",
          unitNumber: "",
        },
        contract: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        msa: null,
        nda: null,
        msaInFile: false,
        ndaInFile: false,
        selectedVendorRecord: null,
        vendorRecords: [
          {
            id: "271943402675923181",
            vendorId: "",
            enabled: true,
            paymentTerm: {
              id: "3",
              name: "Net 60",
              erpId: "3",
              refId: null,
              version: "",
            },
            name: "Testing One",
            additionalCompanyEntities: [],
            companyEntityRef: {
              id: "HH",
              name: "Honeycomb Holdings Inc.",
              erpId: "3",
              refId: null,
              version: "",
            },
            currencies: ["USD"],
            enabledSystems: [],
          },
        ],
        proposal: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        contact: null,
        activationStatus: "",
        newSupplier: false,
        newSupplierMessage: "",
        allowMultiple: false,
        requireSelection: false,
        supplierStatus: "",
        isIndividual: false,
        companyName: "",
        createNewVendor: false,
        potentialMatches: [],
        potentialMatchIgnore: false,
        refId: "329954281019324482",
        ein: "",
        tin: "",
        vat: "",
        tinCountryCode: "",
        vatCountryCode: "",
      },
      startDate: "2023-07-01",
      endDate: "2023-10-31",
      totalAmount: {
        amount: 1,
        currency: "EUR",
      },
      annualRecurring: {
        amount: 2,
        currency: "EUR",
      },
      renewalDate: "",
      department: {
        id: "",
        name: "",
        erpId: "",
      },
      companyEntity: {
        id: "HH-6",
        name: "Honeycomb Holding GmbH",
        erpId: "6",
      },
      requester: {
        name: "Oro Admin",
        userName: "customeradmin+foo@orolabs.ai",
        api: false,
        groupIds: [],
        selected: false,
        tenantId: "foo",
      },
      businessOwners: [
        {
          name: "Oro Admin",
          userName: "customeradmin+foo@orolabs.ai",
          api: false,
          groupIds: [],
          selected: false,
          tenantId: "foo",
        },
      ],
      documents: [],
      contractType: {
        id: "annual",
        name: "Annual",
        erpId: "",
      },
      selectedProduct: {
        id: "",
        name: "",
        erpId: "",
      },
      contractId: "C-409",
    },
  },
};
