import React from "react";
import { StoryFn } from "@storybook/react";

import { PartnerUseForm, PartnerUseFormData } from "../../lib";
import {
  mockOptionsDefault,
  mockOptionsDefault2,
  mockOptionsRegion,
} from "../MultiLevelSelect/mocks";
import { PartnerUseFormProps } from "../../lib/Form/types";

const formData: PartnerUseFormData = {
  title: "Supplier onboarding - Marketing",
  region: { id: "", displayName: "Global", path: "" },
  service: [{ id: "", displayName: "Creative ", path: " " }],
  subsidiary: { id: "", displayName: "Former Optimizely", path: "" },
  additionalSubsidiary: [],
  user: "Jieun Jeong",
  department: { id: "", displayName: "Corporate Marketing", path: "" },
  comment:
    "In support of the Optimizely & Episerver merger, the Optimizely brand will be updated with a refreshed brand identity. Marketing team will work with Moving Brands as the agency to create all the cross-channel visual assets including new company logo, color palette, typeface, photography style.",
};

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Form/Partner Use Form",
  component: PartnerUseForm,
};

export const TemplateForm = {
  args: {
    fields: [
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "title",
        instruction: null,
        modifiable: false,
        order: 1,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Title",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "region",
        instruction: null,
        modifiable: true,
        order: 2,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Country or region supplier is used",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "categories",
        instruction: null,
        modifiable: true,
        order: 3,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Services offered by the supplier",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "companyEntity",
        instruction: null,
        modifiable: true,
        order: 4,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Primary subsidiary",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "additionalCompanyEntities",
        instruction: null,
        modifiable: true,
        order: 5,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Primary subsidiary",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "crmID",
        instruction: null,
        modifiable: false,
        order: 1,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Saleforce ID",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "department",
        instruction: null,
        modifiable: true,
        order: 4,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Department",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
      {
        booleanValue: "true",
        configOnly: false,
        displayType: "fieldRequirement",
        fieldName: "comment",
        instruction: null,
        modifiable: true,
        order: 6,
        requirement: "required",
        sectionTitle: null,
        stringValue: null,
        title: "Comment/Details",
        type: "string",
        validationPath: null,
        validationSubpath: null,
      },
    ],
    regionOptions: mockOptionsRegion,
    categoryOptions: mockOptionsDefault,
    subsidiaryOptions: mockOptionsDefault,
    additionalSubsidiaryOptions: mockOptionsDefault2,
    formData,
    submitLabel: "Submit",
    onReady: () => {},
  },
};
