import React from "react";
import { StoryFn } from "@storybook/react";
import {
  RiskValidationFormData,
  RiskDataValidationFormReadOnly,
} from "./../../lib";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Form/Risk Data Validation Form Read Only",
  component: RiskDataValidationFormReadOnly,
};

export const TemplateForm = {
  args: {
    data: {
      oroRiskScore: {
        overallScore: 60,
        overallLevel: "medium",
        manualRiskScore: {
          score: null,
          level: "low",
          serviceName: "Manual",
          notes: ["Verification required"],
          creationTime: "2022-02-16T07:12:47.686483Z",
          userId: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Doe",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        manualRiskScoreHistory: [
          {
            score: null,
            level: "low",
            serviceName: "Manual",
            notes: ["Test"],
            creationTime: "2022-02-16T05:45:57.754863Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-john@orolabs.ai",
              name: "John Doe",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
          {
            score: null,
            level: "medium",
            serviceName: "Manual",
            notes: ["Need to verify"],
            creationTime: "2022-02-16T05:48:06.011455Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-gandharva@orolabs.ai",
              name: "Lisa Smith",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
          {
            score: null,
            level: "high",
            serviceName: "Manual",
            notes: ["TBD"],
            creationTime: "2022-02-16T06:05:46.314056Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-john@orolabs.ai",
              name: "John Wick",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
        ],
        oroRiskScore: {
          score: 2,
          level: "low",
          notes: [
            "Supplier domain is verified in ORO",
            "Supplier country and bank code is same",
          ],
          serviceName: "ORO",
          maxScore: 5,
          riskScore: true,
        },
        emailRiskScore: [
          {
            score: 21,
            level: "medium",
            notes: [
              "Domain is custom and was registered more than 2 months ago.",
              "At least 1 online profile was found.",
            ],
            serviceName: "SEON",
            maxScore: 100,
            riskScore: true,
          },
        ],
        domainRiskScore: [
          {
            score: 21,
            level: "medium",
            identifier: "1234567890",
            notes: [
              "Domain is custom and was registered more than 2 months ago.",
              "At least 1 online profile was found.",
            ],
            serviceName: "SEON",
            maxScore: 100,
            riskScore: true,
          },
        ],
        sustainabilityScore: [
          {
            score: 14,
            level: "low",
            identifier: "1234567890",
            notes: [
              "Company name and account holder name match.",
              "Account created 2 years back.",
            ],
            serviceName: "Lexis Nexis",
            maxScore: 100,
            riskScore: false,
          },
          {
            score: 0,
            level: "high",
            identifier: "1234567890",
            notes: ["Sepend for account is very high"],
            serviceName: "Lyon",
            maxScore: 100,
            riskScore: false,
          },
        ],
        bankAccountRiskScore: [
          {
            score: 14,
            level: "low",
            notes: [
              "Company name and account holder name match.",
              "Account created 2 years back.",
            ],
            serviceName: "Early Warning",
            maxScore: 100,
            riskScore: false,
          },
          {
            score: 31,
            level: "high",
            notes: ["Sepend for account is very high"],
            serviceName: "CDQ",
            maxScore: 100,
            riskScore: true,
          },
          {
            score: null,
            level: "-",
            notes: ["No information found"],
            serviceName: "CDQ",
            maxScore: 100,
            riskScore: true,
          },
        ],
      },
      manualScore: null,
    },
  },
};
