import React from "react";
import { StoryFn } from "@storybook/react";
import {
  RiskDataValiationForm,
  RiskDataValidationFormProps,
} from "./../../lib";
import { OROFORMIDS } from "../../lib/Form/util";

export default {
  title: "ORO UI Toolkit/Form/Risk Data Validation Form",
  component: RiskDataValiationForm,
};

const mockRiskLevelOptions = [
  {
    id: "low",
    displayName: "Low",
    path: "low",
    selected: false,
    selectable: true,
  },
  {
    id: "medium",
    displayName: "Medium",
    path: "medium",
    selected: false,
    selectable: true,
  },
  {
    id: "high",
    displayName: "High",
    path: "high",
    selected: false,
    selectable: true,
  },
];

export const TemplateForm = {
  args: {
    formId: OROFORMIDS.OroRiskScoreForm,
    fields: [
      {
        fieldName: "level",
        requirement: "required",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Risk level",
        __typename: "FormField",
      },
      {
        fieldName: "notes",
        requirement: "optional",
        booleanValue: true,
        stringValue: null,
        intValue: null,
        itemConfig: null,
        title: "Reasons",
        __typename: "FormField",
      },
    ],
    formData: {
      oroRiskScore: {
        overallScore: 60,
        overallLevel: "low",
        manualRiskScore: {
          score: null,
          level: "low",
          serviceName: "Manual",
          notes: ["Verification required"],
          creationTime: "2022-02-16T07:12:47.686483Z",
          userId: {
            tenantId: "",
            tenantName: null,
            userName: "enduser-john@orolabs.ai",
            name: "John Doe",
            department: "",
            departmentCode: null,
            groupIds: null,
            type: null,
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: null,
            admin: false,
          },
        },
        assessmentRiskScore: [
          {
            score: 21,
            level: "medium",
            identifier: "1234567890",
            notes: [
              "Domain is custom and was registered more than 2 months ago.",
              "At least 1 online profile was found.",
            ],
            serviceName: "SEON",
            maxScore: 100,
            riskScore: true,
          },
          {
            score: 75,
            level: "low",
            identifier: null,
            notes: [
              "Have privacy professional on staff.",
              "Personal information sold to third party.",
            ],
            serviceName: "Privacy Assessment",
            maxScore: 100,
            riskScore: true,
            type: { id: "dpa", name: "DPA", erpId: "" },
          },
        ],
        domainRiskScore: [
          {
            score: 21,
            level: "medium",
            identifier: "1234567890",
            notes: [
              "Domain is custom and was registered more than 2 months ago.",
              "At least 1 online profile was found.",
            ],
            serviceName: "SEON",
            maxScore: 100,
            riskScore: true,
          },
        ],
        customRiskScore: {
          score: 2,
          level: "low",
          identifier: "identifier",
          notes: [
            "Supplier domain is verified in ORO",
            "Supplier country and bank code is same",
          ],
          serviceName: "ORO",
          maxScore: 5,
          riskScore: true,
        },
        emailRiskScore: [
          {
            score: 21,
            level: "medium",
            identifier: "identifier",
            notes: [
              "Domain is custom and was registered more than 2 months ago.",
              "At least 1 online profile was found.",
            ],
            serviceName: "SEON",
            maxScore: 100,
            riskScore: true,
          },
        ],
        bankAccountRiskScore: [
          {
            score: 14,
            level: "low",
            identifier: "1234567890",
            notes: [
              "Company name and account holder name match.",
              "Account created 2 years back.",
            ],
            serviceName: "Early Warning",
            maxScore: 100,
            riskScore: false,
            error: "API Error. Unable to fetch score",
          },
          {
            score: 0,
            level: "high",
            identifier: "1234567890",
            notes: ["Sepend for account is very high"],
            serviceName: "CDQ",
            maxScore: 100,
            riskScore: true,
          },
          {
            score: null,
            level: null,
            identifier: "1234567890",
            notes: ["No information found"],
            serviceName: "CDQ",
            maxScore: 100,
            riskScore: true,
          },
        ],
        sanctionRiskScore: [
          {
            score: 14,
            level: "low",
            identifier: "1234567890",
            notes: [
              "Company name and account holder name match.",
              "Account created 2 years back.",
            ],
            serviceName: "Lexis Nexis",
            maxScore: 100,
            riskScore: false,
          },
          {
            score: 0,
            level: "high",
            identifier: "1234567890",
            notes: ["Sepend for account is very high"],
            serviceName: "Lyon",
            maxScore: 100,
            riskScore: false,
          },
        ],
        sustainabilityScore: [
          {
            score: 14,
            level: "low",
            identifier: "1234567890",
            notes: [
              "Company name and account holder name match.",
              "Account created 2 years back.",
            ],
            serviceName: "Lexis Nexis",
            maxScore: 100,
            riskScore: false,
          },
          {
            score: 0,
            level: "high",
            identifier: "1234567890",
            notes: ["Sepend for account is very high"],
            serviceName: "Lyon",
            maxScore: 100,
            riskScore: false,
          },
        ],
        manualRiskScoreHistory: [
          {
            score: null,
            level: "low",
            serviceName: "Manual",
            notes: ["Test"],
            creationTime: "2022-02-16T05:45:57.754863Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-john@orolabs.ai",
              name: "John Doe",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
          {
            score: null,
            level: "medium",
            serviceName: "Manual",
            notes: ["Need to verify"],
            creationTime: "2022-02-16T05:48:06.011455Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-gandharva@orolabs.ai",
              name: "Lisa Smith",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
          {
            score: null,
            level: "high",
            serviceName: "Manual",
            notes: ["TBD"],
            creationTime: "2022-02-16T06:05:46.314056Z",
            userId: {
              tenantId: "",
              tenantName: null,
              userName: "enduser-john@orolabs.ai",
              name: "John Wick",
              department: "",
              departmentCode: null,
              groupIds: null,
              type: null,
              email: null,
              phone: null,
              firstName: null,
              lastName: null,
              api: false,
              picture: null,
              ip: null,
              admin: false,
            },
          },
        ],
      },
      noteAttachments: [
        {
          contentKind: "CustomerPrivate",
          eid: 218765838642053120,
          filename: "image (1).png",
          mediatype: "image/png",
          path: "attachment/2022/9/3/219039920033890304/image (1).png",
          size: 1588690,
        },
      ],
      fields: [],
    },
    riskLevelOptions: mockRiskLevelOptions,
    onSubmit: () => Promise.resolve(true),
  },
};
