import React from "react";
import { StoryFn } from "@storybook/react";
import {
  SanctionListFormProps,
  SanctionListFormEmailTemplate,
} from "./../../lib";

const mockSanctionLists = [
  {
    id: "plc",
    displayName: "Non-SDN Palestinian Legislative Council List",
    path: "plc",
    selected: false,
    selectable: true,
  },
  {
    id: "sdn",
    displayName: "Specially Designated Nationals and Blocked Persons List",
    path: "sdn",
    selected: false,
    selectable: true,
  },
  {
    id: "bis_dpl",
    displayName: "Bureau of Industry and Security: Denied Persons List",
    path: "bis_dpl",
    selected: false,
    selectable: true,
  },
];

export default {
  title: "ORO UI Toolkit/Form/Sanction List Email Template",
  component: SanctionListFormEmailTemplate,
};

export const TemplateForm = {
  args: {
    formData: {
      sanctionRiskScores: [
        {
          serviceName: "lexisnexis",
          identifier: "YUan",
          score: 80,
          notes: ["Name: IOANNOU, Ioannis", "Exclusion List: sdn"],
          details: {
            errorMessage: "",
            entities: [
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "sdn",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "80.1234532",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "sdn",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "70.56777",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "plc",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "65",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "UN Consolidated List",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "60",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "sdn",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "60",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "bis_dpl",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "45",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
              {
                entityNumber: "17349",
                fullName: "IOANNOU, Ioannis",
                entityType: "individual",
                country: "",
                listType: "OSFI Country ",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50",
              },
            ],
          },
          riskScore: "true",
          url: "https://www.orolabs.ai",
        },
        {
          serviceName: "lexisnexis",
          identifier: "John",
          score: 70,
          notes: ["Name: John", "Exclusion List: bis_dpl"],
          details: {
            errorMessage: "",
            entities: [
              {
                entityNumber: "17349",
                fullName: "John Adams",
                entityType: "individual",
                country: "",
                listType: "sdn",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "80",
              },
              {
                entityNumber: "17349",
                fullName: "John Anderson",
                entityType: "individual",
                country: "",
                listType: "bis_dpl",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "70",
              },
              {
                entityNumber: "17349",
                fullName: "John Arnold",
                entityType: "individual",
                country: "",
                listType: "plc",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "",
              },
              {
                entityNumber: "17349",
                fullName: "John Allen",
                entityType: "individual",
                country: "",
                listType: "UN Consolidated List",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "60.3244",
              },
              {
                entityNumber: "17349",
                fullName: "John Atwood",
                entityType: "individual",
                country: "",
                listType: "sdn",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "60",
              },
              {
                entityNumber: "17349",
                fullName: "John Anderson",
                entityType: "individual",
                country: "",
                listType: "OSFI Country",
                guid: "af687ef4-0c97-493c-b32e-fea9ee43ec55",
                score: "50.677754",
              },
            ],
          },
          riskScore: "true",
          url: "https://www.orolabs.ai",
        },
      ],
    },
    allSanctionLists: mockSanctionLists,
  },
};
