import React from "react";
import { StoryFn } from "@storybook/react";
import {
  UpdateSupplierScopeOfUse,
  UpdateSupplierScopeOfUseProps,
} from "../../lib";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Form/UpdateSupplierProfile/Update Scope of Use",
  component: UpdateSupplierScopeOfUse,
};

const mockScope = [
  {
    id: "266184216757707719",
    name: "testing",
    dimension: {
      programs: [],
      regions: [
        {
          id: "19",
          name: "Americas",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      categories: [
        {
          id: "30",
          name: "HR",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      products: [],
      productStages: [
        {
          id: "101",
          name: "Product1",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      sites: [],
      departments: [],
      companyEntities: [],
    },
    segmentation: "critical",
    description: "",
    latestUse: null,
  },
  {
    id: "306369029615238240",
    name: "",
    dimension: {
      programs: [],
      regions: [],
      categories: [
        {
          id: "50",
          name: "Facilities",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "70",
          name: "Field Services",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "40",
          name: "Legal & Finance",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      products: [],
      productStages: [],
      sites: [],
      departments: [],
      companyEntities: [],
    },
    segmentation: "critical",
    description: "Sample desc",
    latestUse: null,
  },
  {
    id: "253555852963314482",
    name: "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    dimension: {
      programs: [
        {
          id: "eng",
          name: "Engineering",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "marketing",
          name: "Marketing",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      regions: [
        {
          id: "2",
          name: "Africa",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "19",
          name: "Americas",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      categories: [
        {
          id: "53",
          name: "Apparel and Luggage and Personal Care Products",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "50",
          name: "Facilities",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "70",
          name: "Field Services",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "60",
          name: "General Business Services",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "40",
          name: "Legal & Finance",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "80",
          name: "Transportation & Logistics",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      products: [
        {
          id: "2",
          name: "Dell laptop",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "1",
          name: "Hp laptop",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      productStages: [
        {
          id: "101",
          name: "Product1",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      sites: [
        {
          id: "Premikati_NC",
          name: "Premikati NC",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "Site_1",
          name: "Site 1",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      departments: [
        {
          id: "DMRK",
          name: "Digital Marketing",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "FAC",
          name: "Facilities",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      companyEntities: [
        {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
          refId: "",
          version: "",
        },
        {
          id: "Premikati",
          name: "Premikati",
          erpId: "Premikati",
          refId: "",
          version: "",
        },
      ],
    },
    segmentation: "singleSource",
    description:
      "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    latestUse: {
      categories: [
        {
          id: "60",
          name: "General Business Services",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      engagementReference: {
        id: "306492788883958493",
        name: "testing email control in custom forms",
        erpId: "",
        refId: "A3658",
        version: "",
      },
      engagementTime: "2023-05-02T11:51:37.333741602Z",
      requester: {
        name: "John Doe",
        userName: "john@foo.com",
        api: false,
        groupIds: [],
        selected: false,
        tenantId: "foo",
        department: "",
        picture: "",
        firstName: "",
        lastName: "",
        email: "john@foo.com",
      },
    },
  },
  {
    id: "288753296071285482",
    name: "",
    dimension: {
      programs: [],
      regions: [
        {
          id: "19",
          name: "Americas",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      categories: [
        {
          id: "50",
          name: "Facilities",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "70",
          name: "Field Services",
          erpId: "",
          refId: "",
          version: "",
        },
        {
          id: "60",
          name: "General Business Services",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      products: [
        {
          id: "2",
          name: "Dell laptop",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      productStages: [
        {
          id: "101",
          name: "Product1",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      sites: [
        {
          id: "Premikati_NC",
          name: "Premikati NC",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      departments: [],
      companyEntities: [],
    },
    segmentation: "preferred",
    description: "",
    latestUse: {
      categories: [
        {
          id: "60",
          name: "General Business Services",
          erpId: "",
          refId: "",
          version: "",
        },
      ],
      engagementReference: {
        id: "306492788883958493",
        name: "testing email control in custom forms",
        erpId: "",
        refId: "A3658",
        version: "",
      },
      engagementTime: "2023-05-02T11:51:37.333741602Z",
      requester: {
        name: "John Doe",
        userName: "john@foo.com",
        api: false,
        groupIds: [],
        selected: false,
        tenantId: "foo",
        department: "",
        picture: "",
        firstName: "",
        lastName: "",
        email: "john@foo.com",
      },
    },
  },
];

const mockGoodServices = [
  {
    id: "id1",
    displayName: "HR",
    path: "option1",
    customData: { erpId: "5" },
    icon: "",
    selected: true,
    selectable: true,
    hierarchy: "",
  },
  {
    id: "id2",
    displayName: "Marketing",
    path: "option2",
    customData: { erpId: "6" },
    icon: "",
    selected: false,
    selectable: false,
    children: [
      {
        id: "id21",
        displayName: "Branding",
        path: "option2/option2-1",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id22",
        displayName: "Digital Marketing",
        path: "option2/option2-2",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id23",
        displayName: "Email Marketing",
        path: "option2/option2-3",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id24",
        displayName: "Social Media Marketing",
        path: "option2/option2-4",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
    ],
    hierarchy: "",
  },
  {
    id: "id3",
    displayName: "IT Services",
    path: "option3",
    customData: { erpId: "8" },
    icon: "",
    selected: false,
    selectable: false,
    children: [
      {
        id: "id31",
        displayName: "Option 3-1",
        path: "option2/option3-1",
        icon: "",
        selected: false,
        selectable: false,
        children: [
          {
            id: "id311",
            displayName: "Option 3-1-1",
            path: "option2/option3-1/option3-1-1",
            icon: "",
            selected: false,
            selectable: true,
            hierarchy: "",
          },
          {
            id: "id312",
            displayName: "Option 3-1-2",
            path: "option2/option3-1/option3-1-2",
            icon: "",
            selected: false,
            selectable: true,
            hierarchy: "",
          },
          {
            id: "id3122",
            displayName: "Option 3-1-2-2",
            path: "option2/option3-1/option3-1-2-2",
            icon: "",
            selected: false,
            selectable: true,
            hierarchy: "",
          },
        ],
        hierarchy: "",
      },
    ],
    hierarchy: "",
  },
  {
    id: "id4",
    displayName: "Facility Services",
    path: "option4",
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
  },
  {
    id: "id5",
    displayName: "Finance Services",
    path: "option5",
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
  },
  {
    id: "id6",
    displayName: "Logistics",
    path: "option6",
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
  },
  {
    id: "id7",
    displayName: "IT Software",
    path: "option7",
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
  },
];

const mockPreferredStatus = [
  {
    id: "singleSource",
    displayName: "Single Source",
    path: "singleSource",
    selected: false,
    selectable: true,
  },
  {
    id: "preferred",
    displayName: "Preferred",
    path: "preferred",
    selected: false,
    selectable: true,
  },
  {
    id: "critical",
    displayName: "Critical",
    path: "critical",
    selected: false,
    selectable: true,
  },
  {
    id: "approved",
    displayName: "Approved",
    path: "approved",
    selected: false,
    selectable: true,
  },
  {
    id: "strategic",
    displayName: "Strategic",
    path: "strategic",
    selected: false,
    selectable: true,
  },
  {
    id: "prospect",
    displayName: "Prospect",
    path: "prospect",
    selected: false,
    selectable: true,
  },
  {
    id: "dontUse",
    displayName: "Dont Use",
    path: "dontUse",
    selected: false,
    selectable: true,
  },
];

const mockRestrictions = [
  {
    id: "id1",
    displayName: "Program",
    path: "option1",
    customData: { erpId: "5" },
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
    children: [
      {
        id: "id21",
        displayName: "Program 1",
        path: "option1/option1-1",
        customData: { erpId: "7" },
        icon: "",
        selected: true,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id22",
        displayName: "Program 2",
        path: "option1/option1-2",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
    ],
  },
  {
    id: "id2",
    displayName: "Product",
    path: "option2",
    customData: { erpId: "6" },
    icon: "",
    selected: false,
    selectable: false,
    children: [
      {
        id: "id31",
        displayName: "Product 1",
        path: "option2/option2-1",
        customData: { erpId: "7" },
        icon: "",
        selected: true,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id32",
        displayName: "Product 2",
        path: "option2/option2-2",
        customData: { erpId: "7" },
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
    ],
    hierarchy: "",
  },
  {
    id: "id3",
    displayName: "Site",
    path: "option3",
    customData: { erpId: "8" },
    icon: "",
    selected: false,
    selectable: true,
    children: [
      {
        id: "id41",
        displayName: "Site 1",
        path: "option3/option3-1",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id42",
        displayName: "Site 2",
        path: "option3/option3-2",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id43",
        displayName: "Site 3",
        path: "option3/option3-3",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
    ],
    hierarchy: "",
  },
  {
    id: "id4",
    displayName: "Region",
    path: "option4",
    icon: "",
    selected: false,
    selectable: true,
    hierarchy: "",
    children: [
      {
        id: "id51",
        displayName: "Region 1",
        path: "option4/option4-1",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id52",
        displayName: "Region 2",
        path: "option4/option4-2",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
      {
        id: "id53",
        displayName: "Region 3",
        path: "option4/option4-3",
        icon: "",
        selected: false,
        selectable: true,
        hierarchy: "",
      },
    ],
  },
];

export const TemplateForm = {
  args: {
    formData: {
      segmentations: mockScope,
    },
    regionOptions: [],
    siteOptions: [],
    productOptions: [],
    productStageOptions: [],
    goodServicesOptions: mockGoodServices,
    restrictionOptions: mockRestrictions,
    preferredStatusOptions: mockPreferredStatus,
    hasSupplierUpdatePermission: true,
    submitLabel: "Submit",
    cancelLabel: "cancel",
  },
};
