import React from "react";
import { StoryFn } from "@storybook/react";
import { UserProfile, Group, User } from "../../lib";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/UserProfile/profile",
  component: UserProfile,
};

const groups = [
  {
    tenantId: "foo",
    id: "_customer_admin_",
    name: "[Customer Admin]",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "_support_",
    name: "[Support]",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "admin",
    name: "admin",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "auth0_admins",
    name: "Auth0 Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "aws_dev_a_c_admins",
    name: "AWS Dev A/C Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "basf_coat",
    name: "BASF COAT",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "compliance_team",
    name: "Compliance Team",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "contenteng",
    name: "Contenteng",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "critical_alerts",
    name: "Critical Alerts",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "design",
    name: "Design",
    roles: ["__super_admin"],
    permissions: [],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "engineering",
    name: "Engineering",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "foo_goforitlive_admins",
    name: "foo_go4itlive_admins",
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "foo_goforitlive_experts",
    name: "foo_go4itlive_experts",
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "foo_goforitlive_users",
    name: "foo_go4itlive_users",
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "github_admins",
    name: "GitHub Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "group2",
    name: "group2",
    roles: ["__report_admin"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "india_team",
    name: "India Team",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "it_admin",
    name: "IT Admin",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "og1",
    name: "OG1",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "ops_alerts",
    name: "Ops Alerts",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "oro_advisors",
    name: "ORO ADVISORS",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "oro_board_members",
    name: "Oro Board members",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "oro_company",
    name: "ORO Company",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "oro_employees",
    name: "Oro_Employees",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "qa_team",
    name: "QA Team",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "scimtest4",
    name: "scimtest4",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "scimtest5",
    name: "scimtest5",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sg1",
    name: "SG1",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sg2child",
    name: "SG2Child",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sg2parent",
    name: "SG2Parent",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sgroup_another",
    name: "sgroup+,+another",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sgroup_another_pl_us_per_cent",
    name: "sgroup , another pl us per%cent",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "slt",
    name: "SLT",
    roles: ["__operations"],
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "some_other_group",
    name: "some other group",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sudhir_group",
    name: "Sudhir Group",
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "syl",
    name: "SYL",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_dev_a_c_admins",
    name: "SysAdmin Dev A/C - Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_dev_a_c_content",
    name: "SysAdmin Dev A/C - Content",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_dev_a_c_managers",
    name: "SysAdmin Dev A/C - Managers",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_dev_a_c_users",
    name: "SysAdmin Dev A/C - Users",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_prod_a_c_content",
    name: "SysAdmin Prod A/C - Content",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "sysadmin_prod_a_c_managers",
    name: "SysAdmin Prod A/C - Managers",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "task_owner",
    name: "Task owner",
    roles: ["__operations"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "test2",
    name: "test2",
    permissions: ["Buyer:Any:Any"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "test3",
    name: "test3",
    permissions: ["Buyer:Any:Any"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "test_group",
    name: "test_group",
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "test_group_notifications",
    name: "Test Group Notifications",
    roles: ["__super_admin", "__program_owner"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "testgroup",
    name: "TestGroup",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "thoughtspot_admins",
    name: "Thoughtspot Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "thoughtspot_users",
    name: "Thoughtspot Users",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "us_team",
    name: "US Team",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "ux_design",
    name: "UX Design",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "workato_admins",
    name: "Workato Admins",
    externalGroup: true,
    systemGroup: false,
  },
  {
    tenantId: "foo",
    id: "yuan_pmo",
    name: "Yuan_PMO",
    roles: ["__program_owner"],
    externalGroup: false,
    systemGroup: false,
  },
  {
    tenantId: "oro",
    id: "__admin",
    name: "Admin",
    roles: ["__super_admin"],
    externalGroup: false,
    systemGroup: true,
  },
  {
    tenantId: "oro",
    id: "__operations",
    name: "Operations",
    roles: ["__operations"],
    externalGroup: false,
    systemGroup: true,
  },
  {
    tenantId: "oro",
    id: "__report_admin",
    name: "Report Admin",
    roles: ["__report_admin", "__operations"],
    externalGroup: false,
    systemGroup: true,
  },
  {
    tenantId: "oro",
    id: "__report_user",
    name: "Report User",
    roles: ["__report_user", "__operations"],
    externalGroup: false,
    systemGroup: true,
  },
];
const user = {
  tenantId: "foo",
  email: "john@foo.com",
  userName: "john@foo.com",
  firstName: "John",
  lastName: "Doe",
  costCenter: "Marketing",
  businessUnit: "Marketing",
  departmentName: "Marketing",
  picture:
    "https://assets.dev.orolabs.ai/oro%2Fimages%2Fusers%2Ffoo%2Fjohn%40foo.com1670819966184",
  userType: "Tenant",
  groupIds: [
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
    "__admin",
    "__report_admin",
    "admin",
    "auth0_admins",
  ],
  roles: ["__finance_user"],
  lastLoginAttempt: "1689565947032",
  loginFailureCount: 0,
  lastLoginSuccessful: true,
  userLockedOut: false,
  externalUser: false,
  defaultCompanyEntity: "Honeycomb Holdings Inc.",
};

export const UserProfileTemplate = {
  args: {
    groups: groups,
    user: user,
  },
};
