import React from "react";
import { StoryFn } from "@storybook/react";
import { SupplierVendorDetails } from "../../lib";
import { DEFAULT_CURRENCY } from "../../lib/util";
import { SupplierVendorDetailsProps } from "../../lib/SupplierDetails/VendorDetails/type";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/SupplierDetails/VendorDetails",
  component: SupplierVendorDetails,
};

const mockVendorRecords = [
  {
    tenantId: "oro_demo_dev",
    id: "199975663422144552",
    vendorId: "101031",
    normalizedId: "199771899843051520",
    name: "Microsoft Corporation",
    sites: [],
    locations: [],
    bankAccounts: [],
    taxes: [
      {
        id: "309875765101007696",
        encryptedTaxNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "3mMUxzOTsTs9QZ56E1EDTA==",
          iv: "Wl1pPafWF6gOS6C0ZZ4/JA==",
          unencryptedValue: null,
          restrainDecryptData: false,
          unmaskSize: 2,
          maskedValue: "********89",
          setBy: null,
        },
        type: "ein",
        idString: "309875765101007696",
      },
      {
        id: "309875765101007697",
        encryptedTaxNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "3mMUxzOTsTs9QZ56E1EDTA==",
          iv: "Wl1pPafWF6gOS6C0ZZ4/JA==",
          unencryptedValue: null,
          restrainDecryptData: false,
          unmaskSize: 2,
          maskedValue: "********88",
          setBy: null,
        },
        type: "ein",
        idString: "309875765101007697",
      },
    ],
    contacts: [],
    individual: false,
    tax1099: false,
    erpStatus: "NotIntegrated",
    companyEntityRef: {
      tenantId: "oro_demo_dev",
      id: "HH-HU",
      name: "Honeycomb Holdings UK Ltd",
      erpId: "5",
    },
    enabledSystems: [
      {
        id: "HH",
        name: "Honeycomb Holdings Inc.",
        erpId: "3",
      },
    ],
    additionalCompanyEntities: [],
    currencyRefs: [
      {
        id: "USD",
        name: "US Dollar",
      },
    ],
    currencies: [DEFAULT_CURRENCY],
    vendorType: "supplier",
    enabled: false,
    oroIgnore: false,
    website: "https://www.microsoft.com",
    email: "john@foo.com",
    phone: "+1 508 366 9901",
    fax: "",
    payableAccount: {
      id: "786537486",
      name: "786537486",
      erpId: "",
    },
    expenseAccount: {
      id: "786537486",
      name: "786537486",
      erpId: "",
    },
    note: "This is dummy note added for testing",
  },
  {
    tenantId: "oro_demo_dev",
    id: "199771901294280704",
    normalizedId: "199771899843051520",
    name: "IBM",
    sites: [],
    locations: [],
    bankAccounts: [],
    taxes: [],
    contacts: [],
    terms: {
      id: "199771901243949056",
      paymentTermRef: {
        id: "2",
        name: "Net 30",
        erpId: "2",
      },
    },
    individual: false,
    tax1099: false,
    erpStatus: "NotIntegrated",
    companyEntityRef: {
      id: "HH",
      name: "Honeycomb Holdings Inc.",
      erpId: "3",
    },
    additionalCompanyEntities: [],
    currencyRefs: [
      {
        id: "USD",
        name: "US Dollar",
      },
    ],
    currencies: ["USD"],
    vendorType: "supplier",
    enabled: false,
    oroIgnore: false,
  },
  {
    tenantId: "oro_demo_dev",
    id: "199975663422144586",
    vendorId: "101036",
    normalizedId: "199771899843051520",
    name: "Microsoft Corporation",
    sites: [],
    locations: [],
    bankAccounts: [],
    taxes: [],
    contacts: [],
    individual: false,
    tax1099: false,
    erpStatus: "NotIntegrated",
    companyEntityRef: {
      tenantId: "oro_demo_dev",
      id: "HH",
      name: "Honeycomb Holdings Inc.",
      erpId: "3",
    },
    additionalCompanyEntities: [
      {
        id: "HH-HM",
        name: "Honeycomb Mfg.",
        erpId: "1",
      },
    ],
    terms: {
      id: "89088618932469760",
      paymentTermRef: {
        id: "5",
        name: "1% 10 Net 30",
        erpId: "5",
      },
    },
    currencyRefs: [
      {
        id: "USD",
        name: "US Dollar",
      },
    ],
    currencies: ["USD"],
    vendorType: "supplier",
    enabled: false,
    oroIgnore: false,
  },
  {
    tenantId: "oro_demo_dev",
    id: "199938694784745472",
    normalizedId: "199771899843051520",
    name: "Microsoft",
    sites: [],
    locations: [
      {
        id: "199938701927645184",
        name: "Microsoft",
        billing: true,
        billingDefault: true,
        functions: {},
        address: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        banks: [],
        taxes: [],
        contacts: [],
        idString: "199938701927645184",
      },
      {
        id: "199938701931839488",
        shipping: true,
        shippingDefault: true,
        functions: {},
        address: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        banks: [],
        taxes: [],
        contacts: [],
        idString: "199938701931839488",
      },
    ],
    bankAccounts: [
      {
        id: "199938701906673664",
        externalId: null,
        created: "2022-07-12T10:47:32.936192Z",
        currencyCodeStr: "USD",
        currencyCode: {
          id: "USD",
          name: "US Dollar",
        },
        bankName: "BofA",
        accountHolder: "Microsoft",
        accountHolderAddress: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        key: "abaRoutingNumber",
        bankCodeEncrypted: false,
        omitAccountNumber: false,
        bankCode: "121000358",
        bankCodeError: false,
        accountNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "ys95tyY3MYOHQx9xQrjqoQ==",
          iv: "xyerMnb0glGtyPGTFojHmg==",
          unencryptedValue: "976676868679",
          unmaskSize: 4,
          maskedValue: "********8679",
          setBy: {
            tenantId: "oro_demo_dev",
            tenantName: "Oro Demo",
            userName: "mauro@orolabs.ai",
            name: "Mauro",
            department: null,
            departmentCode: null,
            groupIds: null,
            type: "Supplier",
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: "70.132.1.94",
            otp: true,
            admin: false,
          },
        },
        encryptedBankCode: {
          version: "",
          data: "",
          iv: "",
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: "",
          setBy: null,
        },
        internationalKey: null,
        internationalCode: null,
        internationalCodeEncrypted: false,
        omitInternalAccountNUmber: false,
        encryptedInternationalBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalCodeError: false,
        bankAddress: null,
        companyEntityRef: {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
        },
        customFields: null,
        intermediaryBankInfo: {
          bankCodeError: false,
        },
        paymentInstruction: null,
        idString: "199938701906673664",
      },
      {
        id: "199938701906673664",
        externalId: null,
        created: "2022-07-12T10:47:32.936192Z",
        currencyCodeStr: "USD",
        currencyCode: {
          id: "USD",
          name: "US Dollar",
        },
        bankName: "BofA",
        accountHolder: "Microsoft",
        accountHolderAddress: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        key: "abaRoutingNumber",
        bankCodeEncrypted: false,
        omitAccountNumber: false,
        bankCode: "121000358",
        bankCodeError: false,
        accountNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "ys95tyY3MYOHQx9xQrjqoQ==",
          iv: "xyerMnb0glGtyPGTFojHmg==",
          unencryptedValue: "976676868679",
          unmaskSize: 4,
          maskedValue: "********8679",
          setBy: {
            tenantId: "oro_demo_dev",
            tenantName: "Oro Demo",
            userName: "mauro@orolabs.ai",
            name: "Mauro",
            department: null,
            departmentCode: null,
            groupIds: null,
            type: "Supplier",
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: "70.132.1.94",
            otp: true,
            admin: false,
          },
        },
        encryptedBankCode: {
          version: "",
          data: "",
          iv: "",
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: "",
          setBy: null,
        },
        internationalKey: null,
        internationalCode: null,
        internationalCodeEncrypted: false,
        omitInternalAccountNUmber: false,
        encryptedInternationalBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalCodeError: false,
        bankAddress: null,
        companyEntityRef: {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
        },
        customFields: null,
        intermediaryBankInfo: {
          bankCodeError: false,
        },
        paymentInstruction: null,
        idString: "199938701906673664",
      },
    ],
    taxes: [
      {
        id: "199938701931839489",
        issuer: "US",
        taxNumber: "123456789",
        type: "ein",
        address: {
          address: [
            {
              line1: "1 Microsoft Way",
              line2: "",
              line3: "",
              streetNumber: "",
              unitNumber: "",
              city: "Redmond",
              province: "US-WA",
              alpha2CountryCode: "US",
              postal: "98052",
              language: "",
            },
          ],
        },
        idString: "199938701931839489",
      },
    ],
    contacts: [],
    terms: {
      id: "199776139978211328",
      paymentTermRef: {
        id: "2",
        name: "Net 30",
        erpId: "2",
      },
    },
    website: "https://www.microsoft.com/",
    individual: false,
    tax1099: false,
    erpStatus: "NotIntegrated",
    companyEntityRef: {
      id: "HH",
      name: "Honeycomb Holdings Inc.",
      erpId: "3",
    },
    additionalCompanyEntities: [
      {
        id: "HH-HM",
        name: "Honeycomb Mfg.",
        erpId: "1",
      },
      {
        id: "HH-HM-UK",
        name: "Honeycomb Mfg. UK",
        erpId: "2",
      },
    ],
    currencyRefs: [
      {
        id: "USD",
        name: "US Dollar",
      },
      {
        id: "EUR",
        name: "EURO",
      },
    ],
    currencies: ["USD", "EUR"],
    vendorType: "supplier",
    enabled: false,
    oroIgnore: false,
  },
  {
    tenantId: "oro_demo_dev",
    id: "199776140049514496",
    vendorId: "Microsoft",
    normalizedId: "199771899843051520",
    name: "Microsoft",
    sites: [],
    locations: [
      {
        id: "199776260354736128",
        functions: {},
        address: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        banks: [],
        taxes: [],
        contacts: [],
        idString: "199776260354736128",
      },
      {
        id: "199776260367319040",
        name: "Microsoft",
        billing: true,
        billingDefault: true,
        functions: {},
        address: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        banks: [],
        taxes: [],
        contacts: [],
        idString: "199776260367319040",
      },
    ],
    bankAccounts: [
      {
        id: "199776260363124736",
        externalId: null,
        created: "2022-07-12T00:02:03.854215Z",
        currencyCodeStr: "USD",
        currencyCode: {
          id: "USD",
          name: "US Dollar",
        },
        bankName: "BofA",
        accountHolder: "Microsoft",
        accountHolderAddress: {
          line1: "1 Microsoft Way",
          line2: "",
          line3: "",
          streetNumber: "",
          unitNumber: "",
          city: "Redmond",
          province: "US-WA",
          alpha2CountryCode: "US",
          postal: "98052",
          language: "",
        },
        key: "abaRoutingNumber",
        bankCodeEncrypted: false,
        omitAccountNumber: false,
        bankCode: "121000358",
        bankCodeError: false,
        accountNumber: {
          version: "07a39728-2315-493a-9b18-eaee29618e3b",
          data: "GanSR1DgRwN2evO0jwLh4w==",
          iv: "LnzV9B0LU+4GopnCZMzj6w==",
          unencryptedValue: "8685865865865",
          unmaskSize: 4,
          maskedValue: "********5865",
          setBy: {
            tenantId: "oro_demo_dev",
            tenantName: "Oro Demo",
            userName: "mauro@orolabs.ai",
            name: "Mauro",
            department: null,
            departmentCode: null,
            groupIds: null,
            type: "Supplier",
            email: null,
            phone: null,
            firstName: null,
            lastName: null,
            api: false,
            picture: null,
            ip: "70.132.1.82",
            otp: true,
            admin: false,
          },
        },
        encryptedBankCode: {
          version: "",
          data: "",
          iv: "",
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: "",
          setBy: null,
        },
        internationalKey: null,
        internationalCode: null,
        internationalCodeEncrypted: false,
        omitInternalAccountNUmber: false,
        encryptedInternationalBankCode: {
          version: null,
          data: null,
          iv: null,
          unencryptedValue: null,
          unmaskSize: 4,
          maskedValue: null,
          setBy: null,
        },
        internationalCodeError: false,
        bankAddress: null,
        companyEntityRef: {
          id: "HH",
          name: "Honeycomb Holdings Inc.",
          erpId: "3",
        },
        customFields: null,
        intermediaryBankInfo: {
          bankCodeError: false,
        },
        paymentInstruction: null,
        idString: "199776260363124736",
      },
    ],
    taxes: [
      {
        id: "199776260358930432",
        issuer: "US",
        taxNumber: "123456789",
        type: "ein",
        address: {
          address: [
            {
              line1: "1 Microsoft Way",
              line2: "",
              line3: "",
              streetNumber: "",
              unitNumber: "",
              city: "Redmond",
              province: "US-WA",
              alpha2CountryCode: "US",
              postal: "98052",
              language: "",
            },
          ],
        },
        idString: "199776260358930432",
      },
    ],
    contacts: [],
    terms: {
      id: "199776139978211328",
      paymentTermRef: {
        id: "2",
        name: "Net 30",
        erpId: "2",
      },
    },
    website: "https://www.microsoft.com/",
    individual: false,
    tax1099: false,
    erpStatus: "Integrated",
    companyEntityRef: {
      id: "HH",
      name: "Honeycomb Holdings Inc.",
      erpId: "3",
    },
    additionalCompanyEntities: [],
    currencyRefs: [
      {
        id: "USD",
        name: "US Dollar",
      },
    ],
    currencies: ["USD"],
    vendorType: "supplier",
    enabled: false,
    oroIgnore: false,
  },
];
const taxKeys = [
  {
    code: "inpan",
    name: "Permanent Account Number(PAN)",
    description: "Permanent Account Number",
  },
  {
    code: "vies",
    name: "VAT Registration Number",
    description: null,
  },
  {
    code: "tin",
    name: "Income tax id",
    description: null,
  },
  {
    code: "PAN",
    name: "Permanent Account Number",
    description: null,
  },
  {
    code: "ein",
    name: "US Tax Identification/ EIN Number",
    description:
      "Enter the EIN number for your company’s federal tax filing with IRS",
  },
];
const bankKeys = [
  {
    code: "abaRoutingNumber",
    name: "ABA Routing number",
    description: "ABA Routing number",
    encrypted: false,
    omitAccountNumber: false,
  },
  {
    code: "iban",
    name: "IBAN",
    description: "International Bank Account Number",
    encrypted: false,
    omitAccountNumber: false,
  },
  {
    code: "swift",
    name: "SWIFT",
    description: "SWIFT",
    encrypted: false,
    omitAccountNumber: false,
  },
  {
    code: "bankgiro",
    name: "Bankgiro",
    description: "Bankgiro",
    encrypted: false,
    omitAccountNumber: false,
  },
  {
    code: "ifsc",
    name: "IFSC",
    description: "IFSC",
    encrypted: false,
    omitAccountNumber: false,
  },
];

export const TemplateForm = {
  args: {
    vendorRecords: mockVendorRecords,
    bankKeys: bankKeys,
    taxKeys: taxKeys,
  },
};
