import React from "react";
import { StoryFn } from "@storybook/react";
import { AssessmentList } from "../../lib";
import { AssessmentListProps } from "../../lib/SupplierDetails/AssessmentDetails/supplier-assessment-detail-view.component";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/SupplierDetails/SupplierAssessmentDetailView",
  component: AssessmentList,
};

const mockAssessments = [
  {
    tenantId: "foo",
    id: "200581289865117696",
    partyType: null,
    type: null,
    name: "Test",
    normalizedVendor: {
      id: "90623545003999232",
      name: "IBM Deutschland GmbH",
    },
    engagementRef: null,
    expiration: "2022-07-31T00:00:00Z",
    created: "2022-07-11T00:00:00Z",
    requester: {
      tenantId: "foo",
      tenantName: null,
      userName: "john@foo.com",
      name: "John Doe",
      department: "",
      departmentCode: null,
      groupIds: null,
      type: null,
      email: null,
      phone: null,
      firstName: null,
      lastName: null,
      api: false,
      picture: "",
      ip: null,
      otp: false,
      admin: false,
    },
    dimension: {
      programs: [
        {
          id: "eng",
          name: "Engineering",
          erpId: "",
          refId: "",
        },
      ],
      regions: [],
      categories: [],
      products: null,
      sites: [],
      departments: [
        {
          id: "IT",
          name: "IT",
          erpId: "",
          refId: "",
        },
      ],
      companyEntities: [],
    },
    attachment: {
      asyncGetUrl: null,
      asyncPutUrl: null,
      contentKind: "CustomerPrivate",
      date: null,
      eid: null,
      expiration: null,
      filename: "Get_Started_With_Smallpdf.pdf",
      issueDate: null,
      mediatype: "application/pdf",
      name: null,
      note: null,
      path: "attachment/2022/7/17/201826092518998016/Get_Started_With_Smallpdf.pdf",
      reference: null,
      size: 69432,
    },
  },
  {
    tenantId: "foo",
    id: "200615273747709952",
    partyType: null,
    type: {
      id: "legal",
      name: "Legal",
      erpId: "",
      refId: "",
    },
    name: "Legal Assessments",
    normalizedVendor: {
      id: "90623545003999232",
      name: "IBM Deutschland GmbH",
    },
    engagementRef: null,
    expiration: "2022-07-31T00:00:00Z",
    created: "2022-07-01T00:00:00Z",
    requester: {
      tenantId: "foo",
      tenantName: null,
      userName: "john@foo.com",
      name: "John Doe",
      department: "",
      departmentCode: null,
      groupIds: null,
      type: null,
      email: null,
      phone: null,
      firstName: null,
      lastName: null,
      api: false,
      picture: "",
      ip: null,
      otp: false,
      admin: false,
    },
    dimension: {
      programs: [
        {
          id: "eng",
          name: "Engineering",
          erpId: "",
          refId: "",
        },
      ],
      regions: [],
      categories: [],
      products: null,
      sites: [],
      departments: [
        {
          id: "IT",
          name: "IT",
          erpId: "",
          refId: "",
        },
        {
          id: "LEGAL",
          name: "Legal",
          erpId: "",
          refId: "",
        },
      ],
      companyEntities: [],
    },
    souceURL: "testURL",
  },
  {
    tenantId: "foo",
    id: "200582227128483840",
    partyType: null,
    type: {
      id: "legal",
      name: "Legal",
      erpId: "",
      refId: "",
    },
    name: "Test 1",
    normalizedVendor: {
      id: "90623545003999232",
      name: "IBM Deutschland GmbH",
    },
    engagementRef: null,
    expiration: "2022-07-18T00:00:00Z",
    created: "2022-07-11T00:00:00Z",
    requester: {
      tenantId: "foo",
      tenantName: null,
      userName: "john@foo.com",
      name: "John Doe",
      department: "",
      departmentCode: null,
      groupIds: null,
      type: null,
      email: null,
      phone: null,
      firstName: null,
      lastName: null,
      api: false,
      picture: "",
      ip: null,
      otp: false,
      admin: false,
    },
    dimension: {
      programs: [
        {
          id: "eng",
          name: "Engineering",
          erpId: "",
          refId: "",
        },
        {
          id: "marketing",
          name: "Marketing",
          erpId: "",
          refId: "",
        },
      ],
      regions: [],
      categories: [],
      products: null,
      sites: [],
      departments: [],
      companyEntities: [],
    },
    attachment: {
      asyncGetUrl: null,
      asyncPutUrl: null,
      contentKind: "CustomerPrivate",
      date: null,
      eid: null,
      expiration: null,
      filename: "logo.png",
      issueDate: null,
      mediatype: "image/png",
      name: null,
      note: null,
      path: "attachment/2022/7/18/202041666213773312/logo.png",
      reference: null,
      size: 140488,
    },
  },
];

export const TemplateForm = {
  args: {
    assessment: mockAssessments,
    pageSize: 0,
  },
};
