import React from "react";
import { StoryFn } from "@storybook/react";
import {
  SupplierDuplicateCheckForm,
  SupplierDuplicateCheckFormProps,
  getI18NInstance,
} from "../../../lib";
export default {
  title: "ORO UI Toolkit/Form/Supplier duplicate check form/Edit",
  component: SupplierDuplicateCheckForm,
};

const originallySelectedPartner = {
  refId: "450724983683904161",
  id: "438820883587380398",
  vendorRecordId: "V32389023",
  legalEntityLogo: {
    unprocessed: true,
    avoidOverwrite: false,
    expiration: "0",
    attempt: "0",
    metadata: [],
    backgroundColor: null,
  },
  name: "Deloitte Two",
  legalName: "Deloitte Two",
  countryCode: "US",
  website: "",
  selected: false,
  msaInPlace: false,
  ndaInPlace: false,
  ndaAttached: false,
  msaAttached: false,
  email: "",
  phone: "",
  address: {
    line1: "3615 S Hope St",
    line2: "",
    line3: "",
    streetNumber: "3615",
    unitNumber: "",
    city: "Los Angeles",
    province: "US-CA",
    alpha2CountryCode: "US",
    postal: "90007",
    language: "",
  },
  multiLingualAddresses: [],
  duns: "",
  ein: "",
  tin: "",
  tinCountryCode: "",
  vat: "",
  vatCountryCode: "",
  originalActivationStatus: "active",
  activationStatus: "active",
  vendorProcureToPayStatus: {
    companyEntityMatchStatus: "companyEntitiesMatched",
    matchedCompanyEntities: [
      {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        refId: "",
        empty: false,
      },
    ],
    unmatchedCompanyEntities: [],
    matchedPurchasingEntities: [],
    unmatchedPurchasingEntities: [],
  },
  invoicingEnabled: false,
  purchasingEnabled: false,
  newSupplier: false,
  newSupplierMessage: "",
  contact: {
    id: "450724979001273809",
    firstName: "",
    lastName: "",
    fullName: "Sudhir",
    email: "sudhir@orolabs.ai",
    title: "",
    role: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      line3: "",
      streetNumber: "",
      unitNumber: "",
      city: "",
      province: "",
      alpha2CountryCode: "",
      postal: "",
      language: "",
    },
    requireBackgroundCheck: false,
    designation: {
      role: "primary",
    },
    imageUrl: "",
    primary: true,
    emailVerified: false,
    phoneVerified: false,
    idString: "450724979001273809",
  },
  selectedVendorRecord: {
    id: "438821002641881847",
    vendorId: "V32389023",
    name: "Deloitte Two",
    enabled: false,
    companyEntityRef: {
      id: "1",
      name: "Sudhir USA",
      erpId: "",
      empty: false,
    },
    additionalCompanyEntities: [],
    purchasingEntities: [],
    paymentTerm: {
      id: "",
      name: "",
      erpId: "",
      empty: true,
    },
    currencies: ["USD"],
    enabledSystems: [],
  },
  vendorRecords: [
    {
      id: "438821002641881847",
      vendorId: "V32389023",
      name: "Deloitte Two",
      enabled: false,
      companyEntityRef: {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        empty: false,
      },
      additionalCompanyEntities: [],
      purchasingEntities: [],
      paymentTerm: {
        id: "",
        name: "",
        erpId: "",
        empty: true,
      },
      currencies: ["USD"],
      enabledSystems: [],
    },
  ],
  createNewVendor: false,
  newCountryEnable: false,
  potentialMatchIgnore: false,
  individual: false,
};

const originallySelectedSupplier = {
  supplierName: "Deloitte Two",
  multiLinqualName: null,
  legalName: "Deloitte Two",
  companyName: null,
  address: {
    line1: "3615 S Hope St",
    line2: "",
    line3: "",
    streetNumber: "3615",
    unitNumber: "",
    city: "Los Angeles",
    province: "US-CA",
    alpha2CountryCode: "US",
    postal: "90007",
    language: "",
  },
  selectedOrderAddressVendorRef: null,
  isParent: false,
  multiLingualAddresses: [],
  website: null,
  email: null,
  phoneNumber: null,
  duns: "",
  ein: null,
  tin: null,
  tinCountryCode: null,
  vat: null,
  vatCountryCode: null,
  langCode: null,
  contactName: null,
  contact: {
    id: "450724979001273809",
    firstName: "",
    lastName: "",
    fullName: "Sudhir",
    email: "sudhir@orolabs.ai",
    title: "",
    role: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      line3: "",
      streetNumber: "",
      unitNumber: "",
      city: "",
      province: "",
      alpha2CountryCode: "",
      postal: "",
      language: "",
    },
    requireBackgroundCheck: false,
    designation: {
      role: "primary",
    },
    imageUrl: "",
    primary: true,
    emailVerified: false,
    phoneVerified: false,
    idString: "450724979001273809",
  },
  shareHolders: null,
  subsidiaries: null,
  subcontractors: null,
  boardOfDirectors: null,
  nda: null,
  ndaInFile: false,
  msa: null,
  msaInFile: false,
  proposal: null,
  contract: null,
  vendorId: "438820883587380398",
  refId: "450724983683904161",
  activationStatus: null,
  newSupplierMessage: null,
  selectedVendorRecord: {
    id: "438821002641881847",
    vendorId: "V32389023",
    name: "Deloitte Two",
    enabled: false,
    companyEntityRef: {
      id: "1",
      name: "Sudhir USA",
      erpId: "",
      empty: false,
    },
    additionalCompanyEntities: [],
    purchasingEntities: [],
    paymentTerm: {
      id: "",
      name: "",
      erpId: "",
      empty: true,
    },
    currencies: ["USD"],
    enabledSystems: [],
  },
  vendorRecords: [
    {
      id: "438821002641881847",
      vendorId: "V32389023",
      name: "Deloitte Two",
      enabled: false,
      companyEntityRef: {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        empty: false,
      },
      additionalCompanyEntities: [],
      purchasingEntities: [],
      currencies: ["USD"],
    },
  ],
  createNewVendor: false,
  supplierUserId: null,
  legalEntity: null,
  supplierStatus: null,
  isIndividual: false,
  potentialMatches: null,
  potentialMatchesSupplierSummary: null,
  sanctionListRef: null,
  hasSanctionMatch: null,
  hasAdverseMediaMatch: null,
  sanctionList: null,
  potentialMatchIgnore: false,
  tax: null,
  indirectTax: null,
  jurisdictionCountryCode: null,
  supplierSelectionText: null,
  newSupplier: false,
};

const selectedPartner = {
  refId: "450724983683904161",
  id: "438820883587380398",
  vendorRecordId: "V32389023",
  legalEntityLogo: {
    unprocessed: true,
    avoidOverwrite: false,
    expiration: "0",
    attempt: "0",
    metadata: [],
    backgroundColor: null,
  },
  name: "Deloitte Two",
  legalName: "Deloitte Two",
  countryCode: "US",
  website: "",
  selected: false,
  msaInPlace: false,
  ndaInPlace: false,
  ndaAttached: false,
  msaAttached: false,
  email: "",
  phone: "",
  address: {
    line1: "3615 S Hope St",
    line2: "",
    line3: "",
    streetNumber: "3615",
    unitNumber: "",
    city: "Los Angeles",
    province: "US-CA",
    alpha2CountryCode: "US",
    postal: "90007",
    language: "",
  },
  multiLingualAddresses: [],
  duns: "",
  ein: "",
  tin: "",
  tinCountryCode: "",
  vat: "",
  vatCountryCode: "",
  originalActivationStatus: "active",
  activationStatus: "active",
  vendorProcureToPayStatus: {
    companyEntityMatchStatus: "companyEntitiesMatched",
    matchedCompanyEntities: [
      {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        refId: "",
        empty: false,
      },
    ],
    unmatchedCompanyEntities: [],
    matchedPurchasingEntities: [],
    unmatchedPurchasingEntities: [],
  },
  invoicingEnabled: false,
  purchasingEnabled: false,
  newSupplier: false,
  newSupplierMessage: "",
  contact: {
    id: "450724979001273809",
    firstName: "",
    lastName: "",
    fullName: "Sudhir",
    email: "sudhir@orolabs.ai",
    title: "",
    role: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      line3: "",
      streetNumber: "",
      unitNumber: "",
      city: "",
      province: "",
      alpha2CountryCode: "",
      postal: "",
      language: "",
    },
    requireBackgroundCheck: false,
    designation: {
      role: "primary",
    },
    imageUrl: "",
    primary: true,
    emailVerified: false,
    phoneVerified: false,
    idString: "450724979001273809",
  },
  selectedVendorRecord: {
    id: "438821002641881847",
    vendorId: "V32389023",
    name: "Deloitte Two",
    enabled: false,
    companyEntityRef: {
      id: "1",
      name: "Sudhir USA",
      erpId: "",
      empty: false,
    },
    additionalCompanyEntities: [],
    purchasingEntities: [],
    paymentTerm: {
      id: "",
      name: "",
      erpId: "",
      empty: true,
    },
    currencies: ["USD"],
    enabledSystems: [],
  },
  vendorRecords: [
    {
      id: "438821002641881847",
      vendorId: "V32389023",
      name: "Deloitte Two",
      enabled: false,
      companyEntityRef: {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        empty: false,
      },
      additionalCompanyEntities: [],
      purchasingEntities: [],
      paymentTerm: {
        id: "",
        name: "",
        erpId: "",
        empty: true,
      },
      currencies: ["USD"],
      enabledSystems: [],
    },
  ],
  createNewVendor: false,
  newCountryEnable: false,
  potentialMatchIgnore: false,
  individual: false,
};

const selectedSupplier = {
  supplierName: "Deloitte Two",
  multiLinqualName: null,
  legalName: "Deloitte Two",
  companyName: null,
  address: {
    line1: "3615 S Hope St",
    line2: "",
    line3: "",
    streetNumber: "3615",
    unitNumber: "",
    city: "Los Angeles",
    province: "US-CA",
    alpha2CountryCode: "US",
    postal: "90007",
    language: "",
  },
  selectedOrderAddressVendorRef: null,
  isParent: false,
  multiLingualAddresses: [],
  website: null,
  email: null,
  phoneNumber: null,
  duns: "",
  ein: null,
  tin: null,
  tinCountryCode: null,
  vat: null,
  vatCountryCode: null,
  langCode: null,
  contactName: null,
  contact: {
    id: "450724979001273809",
    firstName: "",
    lastName: "",
    fullName: "Sudhir",
    email: "sudhir@orolabs.ai",
    title: "",
    role: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      line3: "",
      streetNumber: "",
      unitNumber: "",
      city: "",
      province: "",
      alpha2CountryCode: "",
      postal: "",
      language: "",
    },
    requireBackgroundCheck: false,
    designation: {
      role: "primary",
    },
    imageUrl: "",
    primary: true,
    emailVerified: false,
    phoneVerified: false,
    idString: "450724979001273809",
  },
  shareHolders: null,
  subsidiaries: null,
  subcontractors: null,
  boardOfDirectors: null,
  nda: null,
  ndaInFile: false,
  msa: null,
  msaInFile: false,
  proposal: null,
  contract: null,
  vendorId: "438820883587380398",
  refId: "450724983683904161",
  activationStatus: null,
  newSupplierMessage: null,
  selectedVendorRecord: {
    id: "438821002641881847",
    vendorId: "V32389023",
    name: "Deloitte Two",
    enabled: false,
    companyEntityRef: {
      id: "1",
      name: "Sudhir USA",
      erpId: "",
      empty: false,
    },
    additionalCompanyEntities: [],
    purchasingEntities: [],
    paymentTerm: {
      id: "",
      name: "",
      erpId: "",
      empty: true,
    },
    currencies: ["USD"],
    enabledSystems: [],
  },
  vendorRecords: [
    {
      id: "438821002641881847",
      vendorId: "V32389023",
      name: "Deloitte Two",
      enabled: false,
      companyEntityRef: {
        id: "1",
        name: "Sudhir USA",
        erpId: "",
        empty: false,
      },
      additionalCompanyEntities: [],
      purchasingEntities: [],
      currencies: ["USD"],
    },
  ],
  createNewVendor: false,
  supplierUserId: null,
  legalEntity: null,
  supplierStatus: null,
  isIndividual: false,
  potentialMatches: null,
  potentialMatchesSupplierSummary: null,
  sanctionListRef: null,
  hasSanctionMatch: null,
  hasAdverseMediaMatch: null,
  sanctionList: null,
  potentialMatchIgnore: false,
  tax: null,
  indirectTax: null,
  jurisdictionCountryCode: null,
  supplierSelectionText: null,
  newSupplier: false,
};

const duplicateCheckResult = {
  duplicateEntries: [
    {
      matchedSupplier: {
        supplierName: "nitesh17052024",
        contactName: "",
        contactNote: "",
        email: "",
        phoneNumber: null,
        vendorId: "",
        website: "www.google.com",
        isParent: false,
        duns: "",
        legalEntity: {
          active: false,
          forbesGlobal: false,
          fortune500: false,
          legalEntityName: "",
          id: null,
          numSubsidiaries: 0,
          otherNames: [],
          name: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          parent: false,
          ultimateParent: false,
          logo: {
            metadata: [],
          },
          commonName: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          legalName: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          description: "",
          numEmployees: {
            value: 0,
          },
          duns: "",
          regId: "",
          regAuthorityCode: "",
          ein: "",
          tin: "",
          vat: "",
          tinCountryCode: "",
          vatCountryCode: "",
          revenue: {
            money: {
              amount: 0,
              currency: "USD",
            },
          },
          address: {
            email: [],
            fax: [],
            phone: [],
            address: [],
          },
          addresses: [],
          website: "",
          shortDescription: "",
          vendorId: "",
          industryCode: "",
          vendorRecordRefs: [],
          supplierStatus: "",
          supplierSegmentation: "",
          supplierDimensions: [],
          segmentationDetails: [],
          highlighters: {
            vendorId: "",
            legalName: "",
            commonName: "",
            aliases: "",
          },
          individual: false,
          activeErpRecord: false,
          engagementReferences: [],
          parentName: "",
          ultimateParentName: "",
          parentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          ultimateParentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          parentVendorRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          otherIds: [],
          activationStatus: "",
        },
        address: {
          alpha2CountryCode: "IN",
          city: "",
          language: "",
          line1: "",
          line2: "",
          line3: "",
          postal: "",
          province: "",
          streetNumber: "",
          unitNumber: "",
        },
        contract: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        msa: null,
        nda: null,
        msaInFile: false,
        ndaInFile: false,
        selectedVendorRecord: null,
        vendorRecords: [],
        proposal: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        contact: {
          address: {
            alpha2CountryCode: "",
            city: "",
            language: "",
            line1: "",
            line2: "",
            line3: "",
            postal: "",
            province: "",
            streetNumber: "",
            unitNumber: "",
          },
          email: "nitesh@orolabs.ai",
          firstName: "",
          id: "",
          lastName: "",
          phone: "",
          role: "",
          title: "",
          fullName: "Nitesh",
          imageUrl: "",
          emailVerified: false,
          phoneVerified: false,
          emailVerification: {
            domainNotExist: false,
            email: "nitesh@orolabs.ai",
            emailNotDeliverable: false,
            isFreeDomain: false,
            verificationFailureReason: "",
            verified: true,
          },
          designation: {
            role: "primary",
          },
        },
        activationStatus: "newSupplier",
        newSupplier: true,
        newSupplierMessage: "",
        allowMultiple: false,
        requireSelection: false,
        supplierStatus: "",
        isIndividual: false,
        companyName: "",
        createNewVendor: false,
        potentialMatches: [],
        potentialMatchIgnore: false,
        refId: "444317899169107052",
        ein: "",
        tin: "",
        vat: "",
        tinCountryCode: "",
        vatCountryCode: "",
        tax: {
          encryptedTaxCode: {
            version: "9f394d17-6ce2-432f-92ca-de67efe93372",
            data: "I5hNf4TZ1y3zQBYC+6tuUw==",
            iv: "IsBL7w/jdhe5xWhASrMrkg==",
            unencryptedValue: "avnpj7593f",
            maskedValue: "********593f",
          },
          taxCodeError: false,
          taxCodeValidationTimeout: false,
          taxKey: "inpan",
          taxKeysList: ["inpan", "other"],
        },
        indirectTax: {
          encryptedTaxCode: {
            version: "9f394d17-6ce2-432f-92ca-de67efe93372",
            data: "spuxsGkhUZrIeVbDHpgA5g==",
            iv: "Jgk/CuG9W1ehNjYG2U/oew==",
            unencryptedValue: "12345678",
            maskedValue: "********5678",
          },
          taxCodeError: false,
          taxCodeValidationTimeout: false,
          taxKey: "ingstin",
          taxKeysList: ["ingstin"],
        },
        jurisdictionCountryCode: "IN",
        langCode: "en",
        supplierSelectionText: "",
        potentialMatchesSupplierSummary: [],
      },
      normalizedVendorRef: null,
      matchedDuns: "123456789",
      matchedTaxId: "",
      normalizedVendorId: "444317899169107052",
    },
    {
      matchedSupplier: {
        supplierName: "nitesh17052024",
        contactName: "",
        contactNote: "",
        email: "",
        phoneNumber: null,
        vendorId: "",
        website: "www.google.com",
        isParent: false,
        duns: "",
        legalEntity: {
          active: false,
          forbesGlobal: false,
          fortune500: false,
          legalEntityName: "",
          id: null,
          numSubsidiaries: 0,
          otherNames: [],
          name: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          parent: false,
          ultimateParent: false,
          logo: {
            metadata: [],
          },
          commonName: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          legalName: {
            active: false,
            language: "",
            name: "",
            source: "",
            type: "",
          },
          description: "",
          numEmployees: {
            value: 0,
          },
          duns: "",
          regId: "",
          regAuthorityCode: "",
          ein: "",
          tin: "",
          vat: "",
          tinCountryCode: "",
          vatCountryCode: "",
          revenue: {
            money: {
              amount: 0,
              currency: "USD",
            },
          },
          address: {
            email: [],
            fax: [],
            phone: [],
            address: [],
          },
          addresses: [],
          website: "",
          shortDescription: "",
          vendorId: "",
          industryCode: "",
          vendorRecordRefs: [],
          supplierStatus: "",
          supplierSegmentation: "",
          supplierDimensions: [],
          segmentationDetails: [],
          highlighters: {
            vendorId: "",
            legalName: "",
            commonName: "",
            aliases: "",
          },
          individual: false,
          activeErpRecord: false,
          engagementReferences: [],
          parentName: "",
          ultimateParentName: "",
          parentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          ultimateParentRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          parentVendorRef: {
            id: "",
            name: "",
            erpId: "",
            refId: null,
            version: "",
          },
          otherIds: [],
          activationStatus: "",
        },
        address: {
          alpha2CountryCode: "IN",
          city: "",
          language: "",
          line1: "",
          line2: "",
          line3: "",
          postal: "",
          province: "",
          streetNumber: "",
          unitNumber: "",
        },
        contract: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        msa: null,
        nda: null,
        msaInFile: false,
        ndaInFile: false,
        selectedVendorRecord: null,
        vendorRecords: [],
        proposal: {
          date: "",
          expiration: "",
          filename: "",
          mediatype: "",
          path: "",
          reference: "",
          size: 0,
          note: "",
          name: "",
          sourceUrl: "",
        },
        contact: {
          address: {
            alpha2CountryCode: "",
            city: "",
            language: "",
            line1: "",
            line2: "",
            line3: "",
            postal: "",
            province: "",
            streetNumber: "",
            unitNumber: "",
          },
          email: "nitesh@orolabs.ai",
          firstName: "",
          id: "",
          lastName: "",
          phone: "",
          role: "",
          title: "",
          fullName: "Nitesh",
          imageUrl: "",
          emailVerified: false,
          phoneVerified: false,
          emailVerification: {
            domainNotExist: false,
            email: "nitesh@orolabs.ai",
            emailNotDeliverable: false,
            isFreeDomain: false,
            verificationFailureReason: "",
            verified: true,
          },
          designation: {
            role: "primary",
          },
        },
        activationStatus: "newSupplier",
        newSupplier: true,
        newSupplierMessage: "",
        allowMultiple: false,
        requireSelection: false,
        supplierStatus: "",
        isIndividual: false,
        companyName: "",
        createNewVendor: false,
        potentialMatches: [],
        potentialMatchIgnore: false,
        refId: "444317899169107052",
        ein: "",
        tin: "",
        vat: "",
        tinCountryCode: "",
        vatCountryCode: "",
        tax: {
          encryptedTaxCode: {
            version: "9f394d17-6ce2-432f-92ca-de67efe93372",
            data: "I5hNf4TZ1y3zQBYC+6tuUw==",
            iv: "IsBL7w/jdhe5xWhASrMrkg==",
            unencryptedValue: "avnpj7593f",
            maskedValue: "********593f",
          },
          taxCodeError: false,
          taxCodeValidationTimeout: false,
          taxKey: "inpan",
          taxKeysList: ["inpan", "other"],
        },
        indirectTax: {
          encryptedTaxCode: {
            version: "9f394d17-6ce2-432f-92ca-de67efe93372",
            data: "spuxsGkhUZrIeVbDHpgA5g==",
            iv: "Jgk/CuG9W1ehNjYG2U/oew==",
            unencryptedValue: "12345678",
            maskedValue: "********5678",
          },
          taxCodeError: false,
          taxCodeValidationTimeout: false,
          taxKey: "ingstin",
          taxKeysList: ["ingstin"],
        },
        jurisdictionCountryCode: "IN",
        langCode: "en",
        supplierSelectionText: "",
        potentialMatchesSupplierSummary: [],
      },
      normalizedVendorRef: null,
      matchedDuns: "123456789",
      matchedTaxId: "",
      normalizedVendorId: "444317899169107052",
    },
  ],
};

getI18NInstance(true);

export const TemplateForm = {
  args: {
    formData: {
      duplicateCheckResult,
      originallySelectedPartner,
      originallySelectedSupplier,
      selectedPartner,
      selectedSupplier,
    },
    // reasonForSelectingDuplicate: {
    //     id: 'string',
    //     name: 'string',
    //     erpId: 'string'
    // }
  },
};
