export const mockConfig = {
    "versionNum": null,
    "created": "2024-02-27T06:33:57.426467627Z",
    "updated": "2024-02-27T09:18:47.374290112Z",
    "createdBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "customeradmin+foo@orolabs.ai",
        "userNameCP": null,
        "name": "Oro Admin (abhinav.ramesh@orolabs.ai)",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "customeradmin+foo@orolabs.ai",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "49.37.194.202",
        "impersonator": "abhinav.ramesh@orolabs.ai",
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "updatedBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "userNameCP": null,
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "182.156.21.2",
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "audit": null,
    "acl": {
        "users": [
            {
                "tenantId": "foo",
                "tenantName": "Foo Company",
                "userName": "customeradmin+foo@orolabs.ai",
                "userNameCP": null,
                "name": "Oro Admin (abhinav.ramesh@orolabs.ai)",
                "department": null,
                "departmentCode": null,
                "departmentErpId": null,
                "groupIds": null,
                "type": "Tenant",
                "email": "customeradmin+foo@orolabs.ai",
                "phone": null,
                "firstName": null,
                "lastName": null,
                "api": false,
                "picture": null,
                "ip": "49.37.194.202",
                "impersonator": "abhinav.ramesh@orolabs.ai",
                "connectionName": null,
                "procurementAdmin": true,
                "otp": false,
                "admin": true
            }
        ],
        "groups": [],
        "workstream": null,
        "programs": null,
        "departments": null,
        "open": false
    },
    "version": "31",
    "idGenerator": {
        "id": 16
    },
    "tenantId": "foo",
    "name": "Testing_category_recommendations",
    "title": "Testing category recommendations",
    "description": "",
    "visibility": null,
    "customVisibilityConditions": null,
    "formType": null,
    "view": {
        "sections": [
            {
                "id": "1",
                "title": null,
                "description": null,
                "displayIndex": "1",
                "grids": [
                    {
                        "id": "5",
                        "displayIndex": "1.1",
                        "level": null,
                        "fields": [
                            {
                                "id": "6",
                                "size": 12,
                                "field": {
                                    "id": "7",
                                    "name": "<p>Engagement title</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_Engagement_title__p_",
                                    "stringRegex": null,
                                    "type": "string",
                                    "selection": null,
                                    "customFieldType": "string",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.1",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": {
                                        "id": "engagementTitle",
                                        "name": "Engagement title",
                                        "erpId": "ProcessFieldMapping__Any__engagementTitle",
                                        "empty": false
                                    },
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "2",
                        "displayIndex": "1.2",
                        "level": null,
                        "fields": [
                            {
                                "id": "3",
                                "size": 12,
                                "field": {
                                    "id": "4",
                                    "name": "<p>Tell us your business need</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "q4__p_Tell_us_your_business_need_",
                                    "stringRegex": null,
                                    "type": "string",
                                    "selection": null,
                                    "customFieldType": "string",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.2",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": {
                                        "id": "engagementSummary",
                                        "name": "Engagement summary",
                                        "erpId": "ProcessFieldMapping__Any__engagementSummary",
                                        "empty": false
                                    },
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "8",
                        "displayIndex": "1.3",
                        "level": null,
                        "fields": [
                            {
                                "id": "9",
                                "size": 12,
                                "field": {
                                    "id": "10",
                                    "name": "<p>Est. budget</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_Est__budget__p_",
                                    "stringRegex": null,
                                    "type": "money",
                                    "selection": null,
                                    "customFieldType": "money",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.3",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": {
                                        "id": "projectAmount",
                                        "name": "Project amount",
                                        "erpId": "ProcessFieldMapping__Any__projectAmount",
                                        "empty": false
                                    },
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "11",
                        "displayIndex": "1.4",
                        "level": null,
                        "fields": [
                            {
                                "id": "12",
                                "size": 12,
                                "field": {
                                    "id": "13",
                                    "name": "<p>po</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_po__p_",
                                    "stringRegex": null,
                                    "type": "idref",
                                    "selection": "single",
                                    "customFieldType": "objectSelector",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.4",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "objectSelectorConfig": {
                                        "type": "po"
                                    },
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "14",
                        "displayIndex": "1.5",
                        "level": null,
                        "fields": [
                            {
                                "id": "15",
                                "size": 12,
                                "field": {
                                    "id": "16",
                                    "name": "<p>contact</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_contact__p_",
                                    "stringRegex": null,
                                    "type": "contact",
                                    "selection": "multiple",
                                    "customFieldType": "contacts",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": "1.5",
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "level": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": {
                                        "visibleFields": [
                                            "email"
                                        ],
                                        "mandatoryFields": null,
                                        "readonlyFields": null,
                                        "listItemPrefix": "Contact",
                                        "miniumSize": 1,
                                        "disableAdd": false,
                                        "disableDelete": false
                                    },
                                    "riskConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    }
                ],
                "visible": null,
                "hiddenForReadOnly": null,
                "layout": "twoColumn"
            }
        ]
    },
    "model": {
        "fields": [
            {
                "id": "4",
                "name": "<p>Tell us your business need</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "q4__p_Tell_us_your_business_need_",
                "stringRegex": null,
                "type": "string",
                "selection": null,
                "customFieldType": "string",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.2",
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": {
                    "id": "engagementSummary",
                    "name": "Engagement summary",
                    "erpId": "ProcessFieldMapping__Any__engagementSummary",
                    "empty": false
                },
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "7",
                "name": "<p>Engagement title</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_Engagement_title__p_",
                "stringRegex": null,
                "type": "string",
                "selection": null,
                "customFieldType": "string",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.1",
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": {
                    "id": "engagementTitle",
                    "name": "Engagement title",
                    "erpId": "ProcessFieldMapping__Any__engagementTitle",
                    "empty": false
                },
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "10",
                "name": "<p>Est. budget</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_Est__budget__p_",
                "stringRegex": null,
                "type": "money",
                "selection": null,
                "customFieldType": "money",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.3",
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": {
                    "id": "projectAmount",
                    "name": "Project amount",
                    "erpId": "ProcessFieldMapping__Any__projectAmount",
                    "empty": false
                },
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "13",
                "name": "<p>po</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_po__p_",
                "stringRegex": null,
                "type": "idref",
                "selection": "single",
                "customFieldType": "objectSelector",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.4",
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "objectSelectorConfig": {
                    "type": "po"
                },
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "16",
                "name": "<p>contact</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_contact__p_",
                "stringRegex": null,
                "type": "contact",
                "selection": "multiple",
                "customFieldType": "contacts",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": "1.5",
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "level": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": {
                    "visibleFields": [
                        "email"
                    ],
                    "mandatoryFields": null,
                    "readonlyFields": null,
                    "listItemPrefix": "Contact",
                    "miniumSize": 1,
                    "disableAdd": false,
                    "disableDelete": false
                },
                "riskConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            }
        ]
    },
    "status": "published",
    "formGlobalConditions": null,
    "validationApis": null,
    "creator": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "customeradmin+foo@orolabs.ai",
        "userNameCP": null,
        "name": "Oro Admin (abhinav.ramesh@orolabs.ai)",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "customeradmin+foo@orolabs.ai",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "49.37.194.202",
        "impersonator": "abhinav.ramesh@orolabs.ai",
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "lastPublished": "2024-02-27T09:18:54.046341511Z"
}