export const mockConfig =  {
  "versionNum": "1",
  "created": "2024-04-29T04:17:44.077254809Z",
  "updated": "2024-04-29T06:21:19.898396049Z",
  "createdBy": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": "johndoeemp1234",
      "name": "John Doe",
      "department": "Finance",
      "departmentCode": "FIN",
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": "john@foo.com",
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "106.213.81.252",
      "impersonator": null,
      "connectionName": null,
      "procurementAdmin": true,
      "admin": true,
      "otp": false
  },
  "updatedBy": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": "johndoeemp1234",
      "name": "John Doe",
      "department": "Finance",
      "departmentCode": "FIN",
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": "john@foo.com",
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "106.213.81.252",
      "impersonator": null,
      "connectionName": null,
      "procurementAdmin": true,
      "admin": true,
      "otp": false
  },
  "audit": null,
  "acl": {
      "users": [
          {
              "tenantId": "foo",
              "tenantName": "Foo Company",
              "userName": "john@foo.com",
              "userNameCP": null,
              "externalId": null,
              "employeeId": "johndoeemp1234",
              "name": "John Doe",
              "department": "Finance",
              "departmentCode": "FIN",
              "departmentErpId": null,
              "groupIds": null,
              "type": "Tenant",
              "email": "john@foo.com",
              "phone": null,
              "firstName": null,
              "lastName": null,
              "api": false,
              "picture": null,
              "ip": "106.213.81.252",
              "impersonator": null,
              "connectionName": null,
              "procurementAdmin": true,
              "admin": true,
              "otp": false
          }
      ],
      "groups": [],
      "workstream": null,
      "programs": null,
      "departments": null,
      "open": false
  },
  "version": "30",
  "idGenerator": {
      "id": 4
  },
  "tenantId": "foo",
  "name": "Test_Item_Comparison",
  "title": "Test Item Comparison",
  "description": "",
  "visibility": null,
  "customVisibilityConditions": null,
  "formType": null,
  "view": {
      "sections": [
          {
              "id": "1",
              "title": null,
              "description": null,
              "displayIndex": "1",
              "grids": [
                  {
                      "id": "2",
                      "displayIndex": "1.1",
                      "level": null,
                      "fields": [
                          {
                              "id": "3",
                              "size": 12,
                              "field": {
                                  "id": "4",
                                  "name": "<p>Please provide the item details</p>",
                                  "description": null,
                                  "placeHolderText": null,
                                  "helpText": null,
                                  "fieldName": "q4__p_Please_provide_the_item_det",
                                  "stringRegex": null,
                                  "type": "itemList",
                                  "selection": "single",
                                  "customFieldType": "itemList",
                                  "choices": null,
                                  "visible": null,
                                  "editable": null,
                                  "required": null,
                                  "optional": false,
                                  "displayIndex": "1.1",
                                  "fileTypes": null,
                                  "documents": null,
                                  "masterDataType": null,
                                  "masterdataConfig": null,
                                  "numberConfig": null,
                                  "dateConfig": null,
                                  "userListingConfig": null,
                                  "formDataConfig": null,
                                  "level": null,
                                  "extracted": false,
                                  "reportName": null,
                                  "fieldGrouping": null,
                                  "fieldGroupOrder": 1000,
                                  "fieldDefaultValue": null,
                                  "defaultValue": null,
                                  "processFieldMapping": null,
                                  "formFieldMapping": null,
                                  "defaultMapping": null,
                                  "certificateConfig": null,
                                  "multiConfig": null,
                                  "itemListConfig": {
                                      "itemType": "lineItems",
                                      "visibleFields": null,
                                      "mandatoryFields": null,
                                      "readonlyFields": null,
                                      "displayFields": [
                                          "name"
                                      ],
                                      "diffFields": null,
                                      "diffExtensionForm": null,
                                      "disableAdd": false,
                                      "disableDelete": false,
                                      "enableAccountCodeFilter": false,
                                      "syncProjectAmount": false,
                                      "listItemPrefix": "Item",
                                      "minimumSize": 1,
                                      "maximumSize": 0,
                                      "splitAccountingConfig": null,
                                      "questionnaireId": {
                                          "name": "Item Comparison Extension Form",
                                          "id": null,
                                          "formId": "Item_Comparison_Extension_Form",
                                          "custom": true
                                      },
                                      "enableAddSubItems": false,
                                      "enableComparison": true
                                  },
                                  "contactConfig": null,
                                  "riskConfig": null,
                                  "assessmentSubtypeConfig": null,
                                  "assessmentExpirationConfig": null,
                                  "objectSelectorConfig": null,
                                  "splitAccountingConfig": null,
                                  "actionConfig": null,
                                  "linkButtonConfig": null,
                                  "restrictedToRole": null,
                                  "displayDocument": false,
                                  "isReadOnly": false,
                                  "isHidden": false,
                                  "hiddenForReadOnly": null,
                                  "published": true,
                                  "clearOnHide": false,
                                  "showRadioBtnControlForChoices": false,
                                  "isSetterOnly": false,
                                  "submitOnChange": false,
                                  "displayInTenantCurrency": null
                              }
                          }
                      ]
                  }
              ],
              "visible": null,
              "hiddenForReadOnly": null,
              "layout": "twoColumn"
          }
      ]
  },
  "model": {
      "fields": [
          {
              "id": "4",
              "name": "<p>Please provide the item details</p>",
              "description": null,
              "placeHolderText": null,
              "helpText": null,
              "fieldName": "q4__p_Please_provide_the_item_det",
              "stringRegex": null,
              "type": "itemList",
              "selection": "single",
              "customFieldType": "itemList",
              "choices": null,
              "visible": null,
              "editable": null,
              "required": null,
              "optional": false,
              "displayIndex": "1.1",
              "fileTypes": null,
              "documents": null,
              "masterDataType": null,
              "masterdataConfig": null,
              "numberConfig": null,
              "dateConfig": null,
              "userListingConfig": null,
              "formDataConfig": null,
              "level": null,
              "extracted": false,
              "reportName": null,
              "fieldGrouping": null,
              "fieldGroupOrder": 1000,
              "fieldDefaultValue": null,
              "defaultValue": null,
              "processFieldMapping": null,
              "formFieldMapping": null,
              "defaultMapping": null,
              "certificateConfig": null,
              "multiConfig": null,
              "itemListConfig": {
                  "itemType": "lineItems",
                  "visibleFields": null,
                  "mandatoryFields": null,
                  "readonlyFields": null,
                  "displayFields": [
                      "name"
                  ],
                  "diffFields": null,
                  "diffExtensionForm": null,
                  "disableAdd": false,
                  "disableDelete": false,
                  "enableAccountCodeFilter": false,
                  "syncProjectAmount": false,
                  "listItemPrefix": "Item",
                  "minimumSize": 1,
                  "maximumSize": 0,
                  "splitAccountingConfig": null,
                  "questionnaireId": {
                      "name": "Item Comparison Extension Form",
                      "id": null,
                      "formId": "Item_Comparison_Extension_Form",
                      "custom": true
                  },
                  "enableAddSubItems": false
              },
              "contactConfig": null,
              "riskConfig": null,
              "assessmentSubtypeConfig": null,
              "assessmentExpirationConfig": null,
              "objectSelectorConfig": null,
              "splitAccountingConfig": null,
              "actionConfig": null,
              "linkButtonConfig": null,
              "restrictedToRole": null,
              "displayDocument": false,
              "isReadOnly": false,
              "isHidden": false,
              "hiddenForReadOnly": null,
              "published": true,
              "clearOnHide": false,
              "showRadioBtnControlForChoices": false,
              "isSetterOnly": false,
              "submitOnChange": false,
              "displayInTenantCurrency": null
          }
      ]
  },
  "status": "published",
  "formGlobalConditions": null,
  "validationApis": null,
  "creator": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": "johndoeemp1234",
      "name": "John Doe",
      "department": "Finance",
      "departmentCode": "FIN",
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": "john@foo.com",
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "106.213.81.252",
      "impersonator": null,
      "connectionName": null,
      "procurementAdmin": true,
      "admin": true,
      "otp": false
  },
  "lastPublished": "2024-04-29T06:21:19.897771172Z"
}