export const mockConfig1 = {
    "versionNum": null,
    "created": "2023-01-13T09:31:27.933794573Z",
    "updated": "2023-10-13T00:34:01.169194919Z",
    "createdBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "175.111.183.98",
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "updatedBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "customeradmin+foo@orolabs.ai",
        "name": "Oro Admin",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "customeradmin+foo@orolabs.ai",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "47.32.159.10",
        "impersonator": "steven.weigand@orolabs.ai",
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": true
    },
    "audit": null,
    "acl": {
        "users": [
            {
                "tenantId": null,
                "tenantName": null,
                "userName": "autousertest.123+admin@gmail.com",
                "name": "AutoUser Admin",
                "department": null,
                "departmentCode": null,
                "departmentErpId": null,
                "groupIds": null,
                "type": "Tenant",
                "email": null,
                "phone": null,
                "firstName": null,
                "lastName": null,
                "api": false,
                "picture": null,
                "ip": null,
                "impersonator": null,
                "connectionName": null,
                "procurementAdmin": true,
                "otp": false,
                "admin": false
            }
        ],
        "groups": [],
        "workstream": null,
        "programs": null,
        "departments": null,
        "open": false
    },
    "version": "7",
    "idGenerator": {
        "id": 4
    },
    "tenantId": "foo",
    "name": "Draft_Legal_Document",
    "title": "Draft Legal Document",
    "description": "",
    "visibility": null,
    "customVisibilityConditions": null,
    "formType": null,
    "view": {
        "sections": [
            {
                "id": "1",
                "title": null,
                "description": null,
                "displayIndex": null,
                "grids": [
                    {
                        "id": "2",
                        "displayIndex": null,
                        "fields": [
                            {
                                "id": "3",
                                "size": 12,
                                "field": {
                                    "id": "4",
                                    "name": "<p>Draft Legal Document</p>",
                                    "description": null,
                                    "placeHolderText": null,
                                    "helpText": null,
                                    "fieldName": "_p_Draft_Legal_Document__p_",
                                    "stringRegex": null,
                                    "type": "documentObject",
                                    "selection": "multiple",
                                    "customFieldType": "draftLegalDocumentList",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": null,
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "dateConfig": null,
                                    "userListingConfig": null,
                                    "formDataConfig": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "formFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "objectSelectorConfig": null,
                                    "splitAccountingConfig": null,
                                    "actionConfig": null,
                                    "linkButtonConfig": null,
                                    "restrictedToRole": [],
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "hiddenForReadOnly": null,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "submitOnChange": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    }
                ],
                "visible": null,
                "hiddenForReadOnly": null,
                "layout": "twoColumn"
            }
        ]
    },
    "model": {
        "fields": [
            {
                "id": "4",
                "name": "<p>Draft Legal Document</p>",
                "description": null,
                "placeHolderText": null,
                "helpText": null,
                "fieldName": "_p_Draft_Legal_Document__p_",
                "stringRegex": null,
                "type": "documentObject",
                "selection": "multiple",
                "customFieldType": "draftLegalDocumentList",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": null,
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "dateConfig": null,
                "userListingConfig": null,
                "formDataConfig": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "formFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "objectSelectorConfig": null,
                "splitAccountingConfig": null,
                "actionConfig": null,
                "linkButtonConfig": null,
                "restrictedToRole": [],
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "hiddenForReadOnly": null,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "submitOnChange": false,
                "displayInTenantCurrency": null
            }
        ]
    },
    "status": "published",
    "formGlobalConditions": null,
    "validationApis": null,
    "creator": {
        "tenantId": null,
        "tenantName": null,
        "userName": "autousertest.123+admin@gmail.com",
        "name": "AutoUser Admin",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": null,
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": null,
        "impersonator": null,
        "connectionName": null,
        "procurementAdmin": true,
        "otp": false,
        "admin": false
    },
    "lastPublished": "2023-10-13T00:34:03.609937522Z"
}
export const mockConfig = {
  "versionNum": null,
  "created": "2022-07-25T15:11:00.541790Z",
  "updated": "2024-06-05T12:38:17.193447241Z",
  "createdBy": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": "johndoeemp1234",
      "name": "John Doe",
      "department": "Finance",
      "departmentCode": "FIN",
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": "john@foo.com",
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "106.213.85.18",
      "impersonator": null,
      "connectionName": null,
      "otp": false,
      "procurementAdmin": true,
      "admin": true
  },
  "updatedBy": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": "johndoeemp1234",
      "name": "John Doe",
      "department": "Finance",
      "departmentCode": "FIN",
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": "john@foo.com",
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "106.213.85.18",
      "impersonator": null,
      "connectionName": null,
      "otp": false,
      "procurementAdmin": true,
      "admin": true
  },
  "audit": null,
  "acl": {
      "users": [
          {
              "tenantId": "foo",
              "tenantName": "Foo Company",
              "userName": "john@foo.com",
              "userNameCP": null,
              "externalId": null,
              "employeeId": null,
              "name": "John Doe",
              "department": null,
              "departmentCode": null,
              "departmentErpId": null,
              "groupIds": null,
              "type": "Tenant",
              "email": null,
              "phone": null,
              "firstName": null,
              "lastName": null,
              "api": false,
              "picture": null,
              "ip": "64.252.177.156",
              "impersonator": null,
              "connectionName": null,
              "otp": false,
              "procurementAdmin": true,
              "admin": true
          }
      ],
      "groups": [],
      "workstream": null,
      "programs": null,
      "departments": null,
      "open": false
  },
  "version": "37",
  "idGenerator": {
      "id": 19
  },
  "tenantId": "foo",
  "name": "Address_component",
  "title": "Address component",
  "description": "address",
  "visibility": null,
  "customVisibilityConditions": null,
  "formType": "onboarding",
  "view": {
      "sections": [
          {
              "id": "1",
              "title": null,
              "description": null,
              "displayIndex": "1",
              "grids": [
                  {
                      "id": "2",
                      "displayIndex": "1.1",
                      "level": null,
                      "fields": [
                          {
                              "id": "3",
                              "size": 12,
                              "field": {
                                  "id": "4",
                                  "name": "<p>enter single address</p>",
                                  "description": null,
                                  "placeHolderText": null,
                                  "helpText": null,
                                  "fieldName": "_p_enter_single_address__p_",
                                  "stringRegex": null,
                                  "type": "address",
                                  "selection": null,
                                  "customFieldType": "address",
                                  "choices": null,
                                  "visible": null,
                                  "editable": null,
                                  "required": null,
                                  "optional": false,
                                  "displayIndex": "1.1",
                                  "fileTypes": null,
                                  "documents": null,
                                  "masterDataType": null,
                                  "masterdataConfig": null,
                                  "numberConfig": null,
                                  "dateConfig": null,
                                  "userListingConfig": null,
                                  "formDataConfig": null,
                                  "level": null,
                                  "extracted": false,
                                  "reportName": null,
                                  "fieldGrouping": null,
                                  "fieldGroupOrder": 1000,
                                  "fieldDefaultValue": null,
                                  "defaultValue": null,
                                  "processFieldMapping": null,
                                  "formFieldMapping": null,
                                  "defaultMapping": null,
                                  "certificateConfig": null,
                                  "multiConfig": null,
                                  "itemListConfig": null,
                                  "contactConfig": null,
                                  "riskConfig": null,
                                  "assessmentSubtypeConfig": null,
                                  "assessmentExpirationConfig": null,
                                  "objectSelectorConfig": null,
                                  "splitAccountingConfig": null,
                                  "actionConfig": null,
                                  "linkButtonConfig": null,
                                  "restrictedToRole": null,
                                  "displayDocument": false,
                                  "isReadOnly": false,
                                  "isHidden": false,
                                  "hiddenForReadOnly": null,
                                  "published": true,
                                  "clearOnHide": false,
                                  "showRadioBtnControlForChoices": false,
                                  "isSetterOnly": false,
                                  "submitOnChange": false,
                                  "displayInTenantCurrency": null
                              }
                          }
                      ]
                  },
                  {
                      "id": "5",
                      "displayIndex": "1.2",
                      "level": null,
                      "fields": [
                          {
                              "id": "6",
                              "size": 12,
                              "field": {
                                  "id": "7",
                                  "name": "<p>Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>",
                                  "description": null,
                                  "placeHolderText": null,
                                  "helpText": null,
                                  "fieldName": "q7__p_Ipsum_passages__and_more_re",
                                  "stringRegex": null,
                                  "type": "address",
                                  "selection": "multiple",
                                  "customFieldType": "addresses",
                                  "choices": null,
                                  "visible": null,
                                  "editable": null,
                                  "required": null,
                                  "optional": false,
                                  "displayIndex": "1.2",
                                  "fileTypes": null,
                                  "documents": null,
                                  "masterDataType": null,
                                  "masterdataConfig": null,
                                  "numberConfig": null,
                                  "dateConfig": null,
                                  "userListingConfig": null,
                                  "formDataConfig": null,
                                  "level": null,
                                  "extracted": false,
                                  "reportName": null,
                                  "fieldGrouping": null,
                                  "fieldGroupOrder": 1000,
                                  "fieldDefaultValue": null,
                                  "defaultValue": null,
                                  "processFieldMapping": null,
                                  "formFieldMapping": null,
                                  "defaultMapping": null,
                                  "certificateConfig": null,
                                  "multiConfig": {
                                      "minCount": 1,
                                      "labelPrefix": "",
                                      "isButton": null
                                  },
                                  "itemListConfig": null,
                                  "contactConfig": null,
                                  "riskConfig": null,
                                  "assessmentSubtypeConfig": null,
                                  "assessmentExpirationConfig": null,
                                  "objectSelectorConfig": null,
                                  "splitAccountingConfig": null,
                                  "actionConfig": null,
                                  "linkButtonConfig": null,
                                  "restrictedToRole": null,
                                  "displayDocument": false,
                                  "isReadOnly": false,
                                  "isHidden": false,
                                  "hiddenForReadOnly": null,
                                  "published": true,
                                  "clearOnHide": false,
                                  "showRadioBtnControlForChoices": false,
                                  "isSetterOnly": false,
                                  "submitOnChange": false,
                                  "displayInTenantCurrency": null
                              }
                          }
                      ]
                  }
              ],
              "visible": null,
              "hiddenForReadOnly": null,
              "layout": "twoColumn"
          }
      ]
  },
  "model": {
      "fields": [
          {
              "id": "4",
              "name": "<p>enter single address</p>",
              "description": null,
              "placeHolderText": null,
              "helpText": null,
              "fieldName": "_p_enter_single_address__p_",
              "stringRegex": null,
              "type": "address",
              "selection": null,
              "customFieldType": "address",
              "choices": null,
              "visible": null,
              "editable": null,
              "required": null,
              "optional": false,
              "displayIndex": "1.1",
              "fileTypes": null,
              "documents": null,
              "masterDataType": null,
              "masterdataConfig": null,
              "numberConfig": null,
              "dateConfig": null,
              "userListingConfig": null,
              "formDataConfig": null,
              "level": null,
              "extracted": false,
              "reportName": null,
              "fieldGrouping": null,
              "fieldGroupOrder": 1000,
              "fieldDefaultValue": null,
              "defaultValue": null,
              "processFieldMapping": null,
              "formFieldMapping": null,
              "defaultMapping": null,
              "certificateConfig": null,
              "multiConfig": null,
              "itemListConfig": null,
              "contactConfig": null,
              "riskConfig": null,
              "assessmentSubtypeConfig": null,
              "assessmentExpirationConfig": null,
              "objectSelectorConfig": null,
              "splitAccountingConfig": null,
              "actionConfig": null,
              "linkButtonConfig": null,
              "restrictedToRole": null,
              "displayDocument": false,
              "isReadOnly": false,
              "isHidden": false,
              "hiddenForReadOnly": null,
              "published": true,
              "clearOnHide": false,
              "showRadioBtnControlForChoices": false,
              "isSetterOnly": false,
              "submitOnChange": false,
              "displayInTenantCurrency": null
          },
          {
              "id": "7",
              "name": "<p>Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>",
              "description": null,
              "placeHolderText": null,
              "helpText": null,
              "fieldName": "q7__p_Ipsum_passages__and_more_re",
              "stringRegex": null,
              "type": "address",
              "selection": "multiple",
              "customFieldType": "addresses",
              "choices": null,
              "visible": null,
              "editable": null,
              "required": null,
              "optional": false,
              "displayIndex": "1.2",
              "fileTypes": null,
              "documents": null,
              "masterDataType": null,
              "masterdataConfig": null,
              "numberConfig": null,
              "dateConfig": null,
              "userListingConfig": null,
              "formDataConfig": null,
              "level": null,
              "extracted": false,
              "reportName": null,
              "fieldGrouping": null,
              "fieldGroupOrder": 1000,
              "fieldDefaultValue": null,
              "defaultValue": null,
              "processFieldMapping": null,
              "formFieldMapping": null,
              "defaultMapping": null,
              "certificateConfig": null,
              "multiConfig": {
                  "minCount": 1,
                  "labelPrefix": "",
                  "isButton": null
              },
              "itemListConfig": null,
              "contactConfig": null,
              "riskConfig": null,
              "assessmentSubtypeConfig": null,
              "assessmentExpirationConfig": null,
              "objectSelectorConfig": null,
              "splitAccountingConfig": null,
              "actionConfig": null,
              "linkButtonConfig": null,
              "restrictedToRole": null,
              "displayDocument": false,
              "isReadOnly": false,
              "isHidden": false,
              "hiddenForReadOnly": null,
              "published": true,
              "clearOnHide": false,
              "showRadioBtnControlForChoices": false,
              "isSetterOnly": false,
              "submitOnChange": false,
              "displayInTenantCurrency": null
          }
      ]
  },
  "status": "published",
  "formGlobalConditions": null,
  "validationApis": null,
  "creator": {
      "tenantId": "foo",
      "tenantName": "Foo Company",
      "userName": "john@foo.com",
      "userNameCP": null,
      "externalId": null,
      "employeeId": null,
      "name": "John Doe",
      "department": null,
      "departmentCode": null,
      "departmentErpId": null,
      "groupIds": null,
      "type": "Tenant",
      "email": null,
      "phone": null,
      "firstName": null,
      "lastName": null,
      "api": false,
      "picture": null,
      "ip": "64.252.177.156",
      "impersonator": null,
      "connectionName": null,
      "otp": false,
      "procurementAdmin": true,
      "admin": true
  },
  "lastPublished": "2024-06-05T12:38:24.215906316Z"
}
