export const mockConfig = {
	"versionNum": "1",
	"created": "2023-03-09T09:33:38.363616186Z",
	"updated": "2023-03-09T09:34:06.591438881Z",
	"createdBy": {
		"tenantId": "foo",
		"tenantName": "Foo Company",
		"userName": "john@foo.com",
		"name": "John Doe",
		"department": null,
		"departmentCode": null,
		"departmentErpId": null,
		"groupIds": null,
		"type": "Tenant",
		"email": "john@foo.com",
		"phone": null,
		"firstName": null,
		"lastName": null,
		"api": false,
		"picture": null,
		"ip": "106.213.82.203",
		"impersonator": null,
		"procurementAdmin": true,
		"otp": false,
		"admin": true
	},
	"updatedBy": {
		"tenantId": "foo",
		"tenantName": "Foo Company",
		"userName": "john@foo.com",
		"name": "John Doe",
		"department": null,
		"departmentCode": null,
		"departmentErpId": null,
		"groupIds": null,
		"type": "Tenant",
		"email": "john@foo.com",
		"phone": null,
		"firstName": null,
		"lastName": null,
		"api": false,
		"picture": null,
		"ip": "106.213.82.203",
		"impersonator": null,
		"procurementAdmin": true,
		"otp": false,
		"admin": true
	},
	"audit": null,
	"acl": {
		"users": [{
			"tenantId": "foo",
			"tenantName": "Foo Company",
			"userName": "john@foo.com",
			"name": "John Doe",
			"department": null,
			"departmentCode": null,
			"departmentErpId": null,
			"groupIds": null,
			"type": "Tenant",
			"email": "john@foo.com",
			"phone": null,
			"firstName": null,
			"lastName": null,
			"api": false,
			"picture": null,
			"ip": "106.213.82.203",
			"impersonator": null,
			"procurementAdmin": true,
			"otp": false,
			"admin": true
		}],
		"groups": [],
		"workstream": null,
		"programs": null,
		"departments": null,
		"open": false
	},
	"version": "6",
	"idGenerator": {
		"id": 4
	},
	"tenantId": "foo",
	"name": "Noopur_test_risk_assessment_field",
	"title": "Noopur test risk assessment field",
	"description": "",
	"visibility": null,
	"customVisibilityConditions": null,
	"formType": null,
	"view": {
		"sections": [{
			"id": "1",
			"title": null,
			"description": null,
			"displayIndex": "1",
			"grids": [{
				"id": "2",
				"displayIndex": "1:1",
				"fields": [{
					"id": "3",
					"size": 12,
					"field": {
						"id": "4",
						"name": "<p>Set risk level</p>",
						"description": null,
						"helpText": null,
						"fieldName": "_p_Set_risk_level__p_",
						"type": "riskLevel",
						"selection": "single",
						"customFieldType": "assessmentRisk",
						"choices": null,
						"visible": null,
						"required": null,
						"optional": false,
						"displayIndex": "1:1",
						"fileTypes": null,
						"documents": null,
						"masterDataType": null,
						"masterdataConfig": null,
						"numberConfig": null,
						"userListingConfig": null,
						"extracted": false,
						"reportName": null,
						"fieldGrouping": null,
						"fieldGroupOrder": 1000,
						"fieldDefaultValue": null,
						"defaultValue": null,
						"processFieldMapping": null,
						"defaultMapping": null,
						"certificateConfig": null,
						"multiConfig": null,
						"itemListConfig": null,
						"contactConfig": null,
						"riskConfig": null,
						"restrictedToRole": null,
						"displayDocument": false,
						"isReadOnly": false,
						"isHidden": false,
						"published": true,
						"clearOnHide": false,
						"showRadioBtnControlForChoices": false,
						"isSetterOnly": false,
						"displayInTenantCurrency": null
					}
				}]
			}],
			"visible": null,
			"layout": "twoColumn"
		}]
	},
	"model": {
		"fields": [{
			"id": "4",
			"name": "<p>Set risk level</p>",
			"description": null,
			"helpText": null,
			"fieldName": "_p_Set_risk_level__p_",
			"type": "riskLevel",
			"selection": "single",
			"customFieldType": "assessmentRisk",
			"choices": null,
			"visible": null,
			"required": null,
			"optional": false,
			"displayIndex": "1:1",
			"fileTypes": null,
			"documents": null,
			"masterDataType": null,
			"masterdataConfig": null,
			"numberConfig": null,
			"userListingConfig": null,
			"extracted": false,
			"reportName": null,
			"fieldGrouping": null,
			"fieldGroupOrder": 1000,
			"fieldDefaultValue": null,
			"defaultValue": null,
			"processFieldMapping": null,
			"defaultMapping": null,
			"certificateConfig": null,
			"multiConfig": null,
			"itemListConfig": null,
			"contactConfig": null,
			"riskConfig": null,
			"restrictedToRole": null,
			"displayDocument": false,
			"isReadOnly": false,
			"isHidden": false,
			"published": true,
			"clearOnHide": false,
			"showRadioBtnControlForChoices": false,
			"isSetterOnly": false,
			"displayInTenantCurrency": null
		}]
	},
	"status": "published",
	"formGlobalConditions": null,
	"creator": {
		"tenantId": "foo",
		"tenantName": "Foo Company",
		"userName": "john@foo.com",
		"name": "John Doe",
		"department": null,
		"departmentCode": null,
		"departmentErpId": null,
		"groupIds": null,
		"type": "Tenant",
		"email": "john@foo.com",
		"phone": null,
		"firstName": null,
		"lastName": null,
		"api": false,
		"picture": null,
		"ip": "106.213.82.203",
		"impersonator": null,
		"procurementAdmin": true,
		"otp": false,
		"admin": true
	}
}