export const mockConfig = {
    "versionNum": null,
    "created": "2022-11-09T12:45:41.804164827Z",
    "updated": "2023-05-22T13:40:13.292795983Z",
    "createdBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "175.111.183.114",
        "impersonator": null,
        "admin": true,
        "otp": false,
        "procurementAdmin": true
    },
    "updatedBy": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "175.111.183.114",
        "impersonator": null,
        "admin": true,
        "otp": false,
        "procurementAdmin": true
    },
    "audit": null,
    "acl": {
        "users": [
            {
                "tenantId": "foo",
                "tenantName": "Foo Company",
                "userName": "john@foo.com",
                "name": "John Doe",
                "department": null,
                "departmentCode": null,
                "departmentErpId": null,
                "groupIds": null,
                "type": "Tenant",
                "email": "john@foo.com",
                "phone": null,
                "firstName": null,
                "lastName": null,
                "api": false,
                "picture": null,
                "ip": "64.252.177.156",
                "impersonator": null,
                "admin": true,
                "otp": false,
                "procurementAdmin": true
            }
        ],
        "groups": [],
        "workstream": null,
        "programs": null,
        "departments": null,
        "open": false
    },
    "version": "19",
    "idGenerator": {
        "id": 13
    },
    "tenantId": "foo",
    "name": "Nitesh_demo___signed_documents",
    "title": "Nitesh demo - signed documents",
    "description": "",
    "visibility": null,
    "customVisibilityConditions": null,
    "formType": "other",
    "view": {
        "sections": [
            {
                "id": "1",
                "title": "Signed Documents",
                "description": null,
                "displayIndex": null,
                "grids": [
                    {
                        "id": "5",
                        "displayIndex": null,
                        "fields": [
                            {
                                "id": "6",
                                "size": 12,
                                "field": {
                                    "id": "7",
                                    "name": "<p>text</p>",
                                    "description": null,
                                    "helpText": null,
                                    "fieldName": "_p_text__p_",
                                    "stringRegex": null,
                                    "type": "string",
                                    "selection": null,
                                    "customFieldType": "string",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": null,
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "userListingConfig": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "8",
                        "displayIndex": null,
                        "fields": [
                            {
                                "id": "9",
                                "size": 12,
                                "field": {
                                    "id": "10",
                                    "name": "<p>text area</p>",
                                    "description": null,
                                    "helpText": null,
                                    "fieldName": "_p_text_area__p_",
                                    "stringRegex": null,
                                    "type": "string",
                                    "selection": null,
                                    "customFieldType": "textArea",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": null,
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "userListingConfig": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    },
                    {
                        "id": "11",
                        "displayIndex": null,
                        "fields": [
                            {
                                "id": "12",
                                "size": 12,
                                "field": {
                                    "id": "13",
                                    "name": "<p>rich text</p>",
                                    "description": null,
                                    "helpText": null,
                                    "fieldName": "_p_rich_text__p_",
                                    "stringRegex": null,
                                    "type": "string",
                                    "selection": null,
                                    "customFieldType": "richText",
                                    "choices": null,
                                    "visible": null,
                                    "required": null,
                                    "optional": false,
                                    "displayIndex": null,
                                    "fileTypes": null,
                                    "documents": null,
                                    "masterDataType": null,
                                    "masterdataConfig": null,
                                    "numberConfig": null,
                                    "userListingConfig": null,
                                    "extracted": false,
                                    "reportName": null,
                                    "fieldGrouping": null,
                                    "fieldGroupOrder": 1000,
                                    "fieldDefaultValue": null,
                                    "defaultValue": null,
                                    "processFieldMapping": null,
                                    "defaultMapping": null,
                                    "certificateConfig": null,
                                    "multiConfig": null,
                                    "itemListConfig": null,
                                    "contactConfig": null,
                                    "riskConfig": null,
                                    "restrictedToRole": null,
                                    "displayDocument": false,
                                    "isReadOnly": false,
                                    "isHidden": false,
                                    "published": true,
                                    "clearOnHide": false,
                                    "showRadioBtnControlForChoices": false,
                                    "isSetterOnly": false,
                                    "displayInTenantCurrency": null
                                }
                            }
                        ]
                    }
                ],
                "visible": null,
                "layout": "twoColumn"
            }
        ]
    },
    "model": {
        "fields": [
            {
                "id": "7",
                "name": "<p>text</p>",
                "description": null,
                "helpText": null,
                "fieldName": "_p_text__p_",
                "stringRegex": null,
                "type": "string",
                "selection": null,
                "customFieldType": "string",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": null,
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "userListingConfig": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "10",
                "name": "<p>text area</p>",
                "description": null,
                "helpText": null,
                "fieldName": "_p_text_area__p_",
                "stringRegex": null,
                "type": "string",
                "selection": null,
                "customFieldType": "textArea",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": null,
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "userListingConfig": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "displayInTenantCurrency": null
            },
            {
                "id": "13",
                "name": "<p>rich text</p>",
                "description": null,
                "helpText": null,
                "fieldName": "_p_rich_text__p_",
                "stringRegex": null,
                "type": "string",
                "selection": null,
                "customFieldType": "richText",
                "choices": null,
                "visible": null,
                "required": null,
                "optional": false,
                "displayIndex": null,
                "fileTypes": null,
                "documents": null,
                "masterDataType": null,
                "masterdataConfig": null,
                "numberConfig": null,
                "userListingConfig": null,
                "extracted": false,
                "reportName": null,
                "fieldGrouping": null,
                "fieldGroupOrder": 1000,
                "fieldDefaultValue": null,
                "defaultValue": null,
                "processFieldMapping": null,
                "defaultMapping": null,
                "certificateConfig": null,
                "multiConfig": null,
                "itemListConfig": null,
                "contactConfig": null,
                "riskConfig": null,
                "restrictedToRole": null,
                "displayDocument": false,
                "isReadOnly": false,
                "isHidden": false,
                "published": true,
                "clearOnHide": false,
                "showRadioBtnControlForChoices": false,
                "isSetterOnly": false,
                "displayInTenantCurrency": null
            }
        ]
    },
    "status": "published",
    "formGlobalConditions": null,
    "creator": {
        "tenantId": "foo",
        "tenantName": "Foo Company",
        "userName": "john@foo.com",
        "name": "John Doe",
        "department": null,
        "departmentCode": null,
        "departmentErpId": null,
        "groupIds": null,
        "type": "Tenant",
        "email": "john@foo.com",
        "phone": null,
        "firstName": null,
        "lastName": null,
        "api": false,
        "picture": null,
        "ip": "64.252.177.156",
        "impersonator": null,
        "admin": true,
        "otp": false,
        "procurementAdmin": true
    }
}