const data = [
  {
    "tenantId": "oro",
    "id": "Category__Any__50",
    customData: { "erpId": "50" },
    "origCode": "50",
    "type": "Category",
    "app": "Any",
    "displayName": "Facilities",
    "path": "50",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__70",
    customData: { "erpId": "70" },
    "origCode": "70",
    "type": "Category",
    "app": "Any",
    "displayName": "Field Services",
    "path": "70",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__60",
    customData: { "erpId": "60" },
    "origCode": "60",
    "type": "Category",
    "app": "Any",
    "displayName": "General Business Services",
    "path": "60",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__30",
    customData: { "erpId": "30" },
    "origCode": "30",
    "type": "Category",
    "app": "Any",
    "displayName": "HR",
    "path": "30",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__10",
    customData: { "erpId": "10" },
    "origCode": "10",
    "type": "Category",
    "app": "Any",
    "displayName": "IT",
    "path": "10",
    "level": 1,
    "active": true,
    "preferred": false,
    "children": [
      {
        "tenantId": "oro",
        "id": "Category__Any__1023",
        customData: { "erpId": "1023" },
        "origCode": "1023",
        "type": "Category",
        "app": "Any",
        "displayName": "AI, Data & Analytics",
        "path": "10-1023",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": [],
        "children": [{
          "tenantId": "oro",
          "id": "Category__Any__1023_10231",
          customData: { "erpId": "10231" },
          "origCode": "10231",
          "type": "Category",
          "app": "Any",
          "displayName": "Augmented Reality",
          "path": "10-1023-10231",
          "level": 2,
          "active": true,
          "parentCode": "1023",
          "preferred": false,
          "recommended": false,
          "ancestorNames": [],
        }]
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1024",
        customData: { "erpId": "1024" },
        "origCode": "1024",
        "type": "Category",
        "app": "Any",
        "displayName": "Application management & support",
        "path": "10-1024",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1014",
        customData: { "erpId": "1014" },
        "origCode": "1014",
        "type": "Category",
        "app": "Any",
        "displayName": "Cloud Infrastructure - AWS, GCP, Azure, etc",
        "path": "10-1014",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1022",
        customData: { "erpId": "1022" },
        "origCode": "1022",
        "type": "Category",
        "app": "Any",
        "displayName": "Cybersecurity",
        "path": "10-1022",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1015",
        customData: { "erpId": "1015" },
        "origCode": "1015",
        "type": "Category",
        "app": "Any",
        "displayName": "Devices & hardware",
        "path": "10-1015",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1016",
        customData: { "erpId": "1016" },
        "origCode": "1016",
        "type": "Category",
        "app": "Any",
        "displayName": "Devops, Cloud & Infrastructure services",
        "path": "10-1016",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1025",
        customData: { "erpId": "1025" },
        "origCode": "1025",
        "type": "Category",
        "app": "Any",
        "displayName": "IT Consulting",
        "path": "10-1025",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1019",
        customData: { "erpId": "1019" },
        "origCode": "1019",
        "type": "Category",
        "app": "Any",
        "displayName": "IT Staff Augmentation",
        "path": "10-1019",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1020",
        customData: { "erpId": "1020" },
        "origCode": "1020",
        "type": "Category",
        "app": "Any",
        "displayName": "QA, Application testing",
        "path": "10-1020",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1012",
        customData: { "erpId": "1012" },
        "origCode": "1012",
        "type": "Category",
        "app": "Any",
        "displayName": "Software - Desktop, Mobile",
        "path": "10-1012",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1010",
        customData: { "erpId": "1010" },
        "origCode": "1010",
        "type": "Category",
        "app": "Any",
        "displayName": "Software - Enterprise application, SaaS",
        "path": "10-1010",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1011",
        customData: { "erpId": "1011" },
        "origCode": "1011",
        "type": "Category",
        "app": "Any",
        "displayName": "Software - Personal productivity ",
        "path": "10-1011",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1017",
        customData: { "erpId": "1017" },
        "origCode": "1017",
        "type": "Category",
        "app": "Any",
        "displayName": "Software Development",
        "path": "10-1017",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1013",
        customData: { "erpId": "1013" },
        "origCode": "1013",
        "type": "Category",
        "app": "Any",
        "displayName": "System Implementation & Integration",
        "path": "10-1013",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1021",
        customData: { "erpId": "1021" },
        "origCode": "1021",
        "type": "Category",
        "app": "Any",
        "displayName": "UI/UX Design",
        "path": "10-1021",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__1018",
        customData: { "erpId": "1018" },
        "origCode": "1018",
        "type": "Category",
        "app": "Any",
        "displayName": "Web Development",
        "path": "10-1018",
        "level": 2,
        "active": true,
        "parentCode": "10",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      }
    ],
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__40",
    customData: { "erpId": "40" },
    "origCode": "40",
    "type": "Category",
    "app": "Any",
    "displayName": "Legal & Finance",
    "path": "40",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__20",
    customData: { "erpId": "20" },
    "origCode": "20",
    "type": "Category",
    "app": "Any",
    "displayName": "Marketing",
    "path": "20",
    "level": 1,
    "active": true,
    "preferred": false,
    "children": [
      {
        "tenantId": "oro",
        "id": "Category__Any__2024",
        customData: { "erpId": "2024" },
        "origCode": "2024",
        "type": "Category",
        "app": "Any",
        "displayName": "Content",
        "path": "20-2024",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2017",
        customData: { "erpId": "2017" },
        "origCode": "2017",
        "type": "Category",
        "app": "Any",
        "displayName": "Corporate communications",
        "path": "20-2017",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2010",
        customData: { "erpId": "2010" },
        "origCode": "2010",
        "type": "Category",
        "app": "Any",
        "displayName": "Creative services",
        "path": "20-2010",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2023",
        customData: { "erpId": "2023" },
        "origCode": "2023",
        "type": "Category",
        "app": "Any",
        "displayName": "Design",
        "path": "20-2023",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2025",
        customData: { "erpId": "2025" },
        "origCode": "2025",
        "type": "Category",
        "app": "Any",
        "displayName": "Digital/Interactive",
        "path": "20-2025",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2015",
        customData: { "erpId": "2015" },
        "origCode": "2015",
        "type": "Category",
        "app": "Any",
        "displayName": "Direct marketing",
        "path": "20-2015",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2028",
        customData: { "erpId": "2028" },
        "origCode": "2028",
        "type": "Category",
        "app": "Any",
        "displayName": "E-commerce",
        "path": "20-2028",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2013",
        customData: { "erpId": "2013" },
        "origCode": "2013",
        "type": "Category",
        "app": "Any",
        "displayName": "Event & sponsorship",
        "path": "20-2013",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2022",
        customData: { "erpId": "2022" },
        "origCode": "2022",
        "type": "Category",
        "app": "Any",
        "displayName": "Experiential",
        "path": "20-2022",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2014",
        customData: { "erpId": "2014" },
        "origCode": "2014",
        "type": "Category",
        "app": "Any",
        "displayName": "Market research & analytics",
        "path": "20-2014",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2026",
        customData: { "erpId": "2026" },
        "origCode": "2026",
        "type": "Category",
        "app": "Any",
        "displayName": "Marketing services",
        "path": "20-2026",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2016",
        customData: { "erpId": "2016" },
        "origCode": "2016",
        "type": "Category",
        "app": "Any",
        "displayName": "Media planning & buying",
        "path": "20-2016",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2018",
        customData: { "erpId": "2018" },
        "origCode": "2018",
        "type": "Category",
        "app": "Any",
        "displayName": "Print, Promotional",
        "path": "20-2018",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2019",
        customData: { "erpId": "2019" },
        "origCode": "2019",
        "type": "Category",
        "app": "Any",
        "displayName": "Production",
        "path": "20-2019",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2011",
        customData: { "erpId": "2011" },
        "origCode": "2011",
        "type": "Category",
        "app": "Any",
        "displayName": "Public relations",
        "path": "20-2011",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2012",
        customData: { "erpId": "2012" },
        "origCode": "2012",
        "type": "Category",
        "app": "Any",
        "displayName": "SEO, SEM",
        "path": "20-2012",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2021",
        customData: { "erpId": "2021" },
        "origCode": "2021",
        "type": "Category",
        "app": "Any",
        "displayName": "Shopper marketting",
        "path": "20-2021",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2020",
        customData: { "erpId": "2020" },
        "origCode": "2020",
        "type": "Category",
        "app": "Any",
        "displayName": "Social Media",
        "path": "20-2020",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      },
      {
        "tenantId": "oro",
        "id": "Category__Any__2027",
        customData: { "erpId": "2027" },
        "origCode": "2027",
        "type": "Category",
        "app": "Any",
        "displayName": "Website development, hosting, monitoring",
        "path": "20-2027",
        "level": 2,
        "active": true,
        "parentCode": "20",
        "preferred": false,
        "recommended": false,
        "ancestorNames": []
      }
    ],
    "recommended": false,
    "ancestorNames": []
  },
  {
    "tenantId": "oro",
    "id": "Category__Any__80",
    customData: { "erpId": "80" },
    "origCode": "80",
    "type": "Category",
    "app": "Any",
    "displayName": "Transportation & Logistics",
    "path": "80",
    "level": 1,
    "active": true,
    "preferred": false,
    "recommended": false,
    "ancestorNames": []
  }
]

export default data
