import React from "react";
import { StoryFn } from "@storybook/react";

import { MilestonesWidget } from "./../../lib";
import { MilestoneWidgetProps } from "../../lib/MilestoneWidget/milestones-widget.component";

//👇 This default export determines where your story goes in the story list
export default {
  title: "ORO UI Toolkit/Milestone/widget",
  component: MilestonesWidget,
};

const milestones = [
  {
    id: "360923211180626182",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "aaaaaa",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [
      {
        tenantId: "foo",
        name: "akanksha123 testing",
        userName: "aka@gmail.com",
        department: "",
      },
    ],
    groups: [],
    startDate: "2023-09-21",
    dueDate: "2023-09-28",
    updated: "2023-09-30T12:51:36.784363259Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:30.894377775Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [
      {
        id: "Program:eng18",
        text: "new tag testing",
      },
    ],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "360923229494980397",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "aaaaa",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [],
    groups: [],
    startDate: "",
    dueDate: "",
    updated: "2023-09-29T16:22:35.285715293Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:35.260534219Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "360923251366252806",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "aaaa",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [],
    groups: [],
    startDate: "",
    dueDate: "",
    updated: "2023-09-29T16:22:40.502438766Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:40.475682102Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "360923266700628230",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "aaa",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [
      {
        tenantId: "foo",
        name: "Akanksha Hardwani",
        userName: "akanksha",
        department: "",
      },
    ],
    groups: [],
    startDate: "",
    dueDate: "",
    updated: "2023-09-30T12:51:45.863367715Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:44.131999883Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "360923285931512070",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "aa",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [],
    groups: [],
    startDate: "",
    dueDate: "",
    updated: "2023-09-29T16:22:48.740192122Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:48.716554433Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "360923303008546605",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "a",
    description: "",
    isImportant: true,
    taskStatus: "notStarted",
    owner: null,
    users: [],
    groups: [],
    startDate: "",
    dueDate: "",
    updated: "2023-09-29T16:23:00.768940858Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-09-29T16:22:52.787713704Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
  {
    id: "362437970009021731",
    type: "measure",
    processTaskType: "",
    processId: "214125011726761984",
    actionId: "",
    engagement: null,
    engagementId: "214124862820581376",
    engagementName: "",
    requestor: "",
    collcectionId: "",
    name: "new task test",
    description: "",
    isImportant: false,
    taskStatus: "notStarted",
    owner: null,
    users: [
      {
        tenantId: "foo",
        name: "Yuan Tung4",
        userName: "tung.yuan.tsung@gmail.com",
        department: "",
      },
    ],
    groups: [],
    startDate: "2023-10-10",
    dueDate: "",
    updated: "2023-10-03T20:41:37.580151620Z",
    completed: "",
    position: 9,
    taskAssignment: null,
    notes: [],
    priority: null,
    created: "2023-10-03T20:41:37.542527819Z",
    actionType: "",
    relatedMeasure: {
      id: "",
      name: "",
      erpId: "",
      refId: null,
      version: "",
    },
    labels: [],
    relatedMeasures: [],
    workstreams: [],
    program: {
      id: "eng",
      name: "Engineering",
      erpId: "",
      refId: null,
      version: "",
    },
  },
];

export const Default = {
  args: {
    milestones: [],
    owners: [],
    customTags: [],
    selectedProgramId: "",
    isAddNewmilestoneOpen: true,
  },
};
